Repository tendermint/tendermint, pull requests merged in 2019-08, with the labels that each got.

#3864 Add gocritic (2/2)
  .golangci.yml
  abci/cmd/abci-cli/abci-cli.go
  abci/example/kvstore/kvstore_test.go
  blockchain/v0/pool.go
  consensus/replay.go
  consensus/replay_test.go
  consensus/state.go
  crypto/merkle/simple_proof.go
  go.mod
  go.sum
  libs/autofile/group.go
  libs/common/async_test.go
  libs/common/errors.go
  libs/log/tmfmt_logger.go
  mempool/clist_mempool_test.go
  node/node.go
  p2p/fuzz.go
  p2p/netaddress.go
  p2p/node_info_test.go
  p2p/switch.go
  rpc/lib/client/http_client.go
  rpc/lib/server/handlers.go
  state/execution.go
  state/txindex/kv/kv.go
  tools/tm-monitor/monitor/network.go
  types/validator.go
Labels: code-hygiene, ready-for-review

#3370 Refactoring Remote signers
  .gitignore
  CHANGELOG_PENDING.md
  cmd/priv_val_server/main.go
  node/node.go
  node/node_test.go
  privval/doc.go
  privval/errors.go
  privval/file_deprecated_test.go
  privval/file_test.go
  privval/messages.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_dialer_endpoint.go
  privval/signer_endpoint.go
  privval/signer_listener_endpoint.go
  privval/signer_listener_endpoint_test.go
  privval/signer_remote.go
  privval/signer_remote_test.go
  privval/signer_requestHandler.go
  privval/signer_server.go
  privval/signer_service_endpoint.go
  privval/signer_validator_endpoint.go
  privval/signer_validator_endpoint_test.go
  privval/socket_dialers_test.go
  privval/socket_listeners.go
  privval/utils.go
  privval/utils_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/priv_validator.go
Labels: ready-for-review

#3877 mempool: make `max_tx_bytes` configurable instead of `max_msg_bytes`
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  docs/tendermint-core/configuration.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/reactor.go
Labels: breaking

#3769 [ADR - 42] State-sync
  docs/architecture/adr-042-state-sync.md
  docs/architecture/img/state-sync.png
Labels: ready-for-review

#3888 (1/2) of replace errors.go with github.com/pkg/errors
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  crypto/merkle/proof.go
  crypto/merkle/proof_key_path.go
  crypto/merkle/proof_simple_value.go
  crypto/merkle/proof_test.go
  p2p/switch.go
  p2p/test_util.go
  privval/messages.go
  store/store.go
  store/store_test.go
  types/block.go
  types/genesis.go
Labels: code-hygiene, ready-for-review

#3890 Remove instances of cmn.Error (2/2)
  cmd/tendermint/commands/lite.go
  crypto/merkle/simple_proof.go
  lite/base_verifier.go
  lite/errors/errors.go
  lite/proxy/errors.go
  lite/proxy/query.go
  lite/proxy/verifier.go
  p2p/conn/connection.go
  p2p/peer_test.go
  privval/socket_dialers_test.go
  privval/utils.go
  privval/utils_test.go
  types/params.go
  types/validator_set.go
Labels: code-hygiene

#3879 ValidateBasic tests
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  config/config_test.go
  consensus/reactor_test.go
  types/block_test.go
  types/evidence_test.go
Labels: ready-for-review, test

#3902 Update reproducible builds to build with Go 1.12.8
  scripts/gitian-build.sh
  scripts/gitian-descriptors/gitian-darwin.yml
  scripts/gitian-descriptors/gitian-linux.yml
  scripts/gitian-descriptors/gitian-windows.yml
Labels: ready-for-review

#3904 Remove mentions of go-wire
  Makefile
  ROADMAP.md
  abci/types/protoreplace/protoreplace.go
  consensus/state.go
  docs/spec/p2p/connection.md
  docs/spec/reactors/mempool/messages.md
  rpc/core/routes.go
  types/results.go
Labels: code-hygiene

#3841 Updated lite client spec
  docs/spec/consensus/light-client.md
Labels: ready-for-review
