Repository tendermint/tendermint, pull requests merged in 2019-07, with the labels that each got.

#3744 abci: Refactor CheckTx to notify of recheck
  CHANGELOG_PENDING.md
  abci/client/client.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/socket_client.go
  abci/cmd/abci-cli/abci-cli.go
  abci/example/example_test.go
  abci/example/kvstore/kvstore_test.go
  abci/tests/server/client.go
  abci/tests/test_app/app.go
  abci/types/messages.go
  abci/types/types.pb.go
  abci/types/types.proto
  consensus/replay_test.go
  docs/spec/abci/abci.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  proxy/app_conn.go
  state/execution.go
Labels: abci, ready-for-review

#3762 p2p: dial addrs which came from seed instead of calling ensurePeers
  CHANGELOG_PENDING.md
  p2p/pex/pex_reactor.go
Labels: ready-for-review

#3758 abci: minor cleanups in the socket client
  abci/client/socket_client.go
Labels: code-hygiene, ready-for-review

#3771 node: allow registration of custom reactors while creating node
  CHANGELOG_PENDING.md
  node/node.go
  node/node_test.go
  p2p/mock/reactor.go
Labels: ready-for-review

#3772 [behaviour] fix in struct returned in messagOutOfOrder PeerBehaviour
  CHANGELOG_PENDING.md
  behaviour/peer_behaviour.go
Labels: ready-for-review

#3753 [ADR - 43] blockchain riri-org
  docs/architecture/adr-043-blockchain-riri-org.md
  docs/architecture/img/blockchain-reactor-v1.png
  docs/architecture/img/blockchain-reactor-v2.png
Labels: ready-for-review

#3776 Quick link fixes throughout docs and repo
  DOCKER/Dockerfile.develop
  DOCKER/README.md
  docs/DOCS_README.md
  docs/app-dev/abci-cli.md
  docs/app-dev/app-development.md
  docs/architecture/adr-018-ABCI-Validators.md
  docs/introduction/install.md
  docs/introduction/introduction.md
  docs/introduction/what-is-tendermint.md
  docs/networks/docker-compose.md
  docs/networks/terraform-and-ansible.md
  docs/spec/abci/README.md
  docs/spec/abci/abci.md
  docs/spec/abci/client-server.md
  docs/spec/blockchain/encoding.md
  docs/spec/consensus/consensus.md
  docs/spec/reactors/mempool/reactor.md
  docs/spec/software/wal.md
  docs/tendermint-core/configuration.md
  docs/tendermint-core/how-to-read-logs.md
  docs/tendermint-core/rpc.md
Labels: ready-for-review

#3770 Infrastructure for reproducible builds
  .circleci/config.yml
  scripts/gitian-build.sh
  scripts/gitian-descriptors/gitian-darwin.yml
  scripts/gitian-descriptors/gitian-linux.yml
  scripts/gitian-descriptors/gitian-windows.yml
  scripts/gitian-keys/README.md
  scripts/gitian-keys/keys.txt
Labels: ready-for-review, tools

#3780 Remove heap.go
  CHANGELOG_PENDING.md
  libs/common/heap.go
Labels: ready-for-review

#3754 p2p: extract ID validation into a separate func
  p2p/netaddress.go
  p2p/netaddress_test.go
  p2p/pex/addrbook.go
  p2p/pex/errors.go
  p2p/pex/pex_reactor.go
Labels: ready-for-review

#3784 Remove unused functions in `libs/common`
  CHANGELOG_PENDING.md
  libs/common/date.go
  libs/common/date_test.go
  libs/common/io.go
  libs/common/os.go
  libs/common/os_test.go
Labels: code-hygiene, ready-for-review

#3786 Updating the default private validator key JSON filename
  docs/tendermint-core/using-tendermint.md
Labels: docs, ready-for-review

#3785 Clean up `fail.go`
  CHANGELOG_PENDING.md
  libs/fail/fail.go
Labels: code-hygiene, ready-for-review

#3798 Remove go func from finishAsyncCall()
  abci/client/grpc_client.go
Labels: ready-for-review

#3820 Added A TOC to the Readme.md of ADR Section
  README.md
  docs/architecture/README.md
Labels: docs, ready-for-review

#3818 rpc: make max_body_bytes and max_header_bytes configurable
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  docs/tendermint-core/configuration.md
  node/node.go
  rpc/lib/server/handlers.go
  rpc/lib/server/http_server.go
Labels: ready-for-review

#3664 p2p/conn: Add Bufferpool
  CHANGELOG_PENDING.md
  go.mod
  go.sum
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
Labels: ready-for-review

#3481 rpc: /broadcast_evidence
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/persistent_kvstore.go
  rpc/client/amino.go
  rpc/client/httpclient.go
  rpc/client/interface.go
  rpc/client/localclient.go
  rpc/client/main_test.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
  rpc/core/evidence.go
  rpc/core/routes.go
  rpc/core/types/responses.go
Labels: ready-for-review

#3827 Renamed wire.go to codec.go
  blockchain/v0/codec.go
  blockchain/v1/codec.go
  cmd/tendermint/commands/codec.go
  consensus/codec.go
  consensus/types/codec.go
  crypto/merkle/codec.go
  crypto/multisig/codec.go
  evidence/codec.go
  mempool/codec.go
  node/codec.go
  p2p/codec.go
  p2p/conn/codec.go
  p2p/pex/codec.go
  privval/codec.go
  rpc/client/codec.go
  rpc/core/types/codec.go
  state/codec.go
  state/txindex/kv/codec.go
  store/codec.go
  tools/tm-monitor/codec.go
  tools/tm-monitor/monitor/codec.go
  types/codec.go
Labels: code-hygiene, ready-for-review

#3828 Add staticcheck linting
  .golangci.yml
  abci/client/grpc_client.go
  abci/example/example_test.go
  blockchain/v0/reactor.go
  blockchain/v1/reactor.go
  consensus/mempool_test.go
  consensus/reactor_test.go
  consensus/state.go
  consensus/state_test.go
  go.sum
  libs/common/async.go
  libs/common/async_test.go
  libs/pubsub/pubsub_test.go
  lite/proxy/query_test.go
  mempool/clist_mempool.go
  p2p/conn/connection_test.go
  p2p/conn/secret_connection_test.go
  p2p/switch_test.go
  privval/signer_validator_endpoint_test.go
  rpc/grpc/client_server.go
  rpc/lib/client/ws_client.go
  rpc/lib/client/ws_client_test.go
  state/state_test.go
  tools/tm-monitor/mock/eventmeter.go
  types/genesis_test.go
  types/validator_set.go
Labels: code-hygiene, ready-for-review

#3819 Move MakeVote function
  blockchain/v0/reactor_test.go
  consensus/replay_test.go
  state/helpers_test.go
  state/validation_test.go
  types/block.go
  types/test_util.go
Labels: code-hygiene, ready-for-review

#3838 docs: "Writing a Tendermint Core application in Kotlin (gRPC)" guide
  docs/guides/kotlin.md
Labels: ready-for-review

#3851 Refactor Tx Search Aggregation
  CHANGELOG_PENDING.md
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
Labels: enhancement, perf, ready-for-review, rpc
