Repository tendermint/tendermint, pull requests merged in 2019-09, with the labels that each got.

#3933 Quick fix to swagger docs
  docs/spec/rpc/swagger.yaml
  rpc/core/mempool.go
Labels: docs

#3947 update gogo/protobuf version from v1.2.1 to v1.3.0
  config/config.go
  go.mod
  go.sum
  scripts/get_tools.sh
Labels: dependencies

#3950 deps: bump viper to 1.4.0 and logfmt to 0.4.0
  go.mod
  go.sum
  libs/log/tm_logger_test.go
Labels: dependencies

#3840 Zm fork accountability
  docs/spec/consensus/fork-accountability.md
Labels: ready-for-review

#3967 Update `go.sum`
  go.sum
Labels: code-hygiene

#3988 get_tools = tools
  DOCKER/Dockerfile.abci
  Vagrantfile
  docs/app-dev/abci-cli.md
  docs/app-dev/getting-started.md
  docs/introduction/install.md
  docs/tools/monitoring.md
  networks/remote/integration.sh
  scripts/dist.sh
  scripts/install/install_tendermint_arm.sh
  scripts/install/install_tendermint_bsd.sh
  scripts/install/install_tendermint_osx.sh
  scripts/install/install_tendermint_ubuntu.sh
  tools/build/Makefile
  tools/tm-bench/Dockerfile.dev
  tools/tm-monitor/Dockerfile.dev
  tools/tm-monitor/README.md
Labels: docs, ready-for-review

#3987 Add MempoolClient to Client Interface
  CHANGELOG_PENDING.md
  rpc/client/interface.go
  rpc/client/mock/client.go
  types/vote.go
Labels: ready-for-review

#3994 Minor cleanup of makefile
  Makefile
  rpc/core/README.md
  rpc/core/slate_header.txt
  tools.mk
Labels: R4R

#3889 Remove omitempty from *pb.go
  CHANGELOG_PENDING.md
  abci/types/messages_test.go
  abci/types/result.go
  crypto/merkle/result.go
  libs/common/result.go
  types/proto3/result.go
  types/tx.go
Labels: abci, dev-ux

#3878 [blockchain] v2 Routines
  blockchain/v2/metrics.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  blockchain/v2/routine.go
  blockchain/v2/routine_test.go
  blockchain/v2/schedule.go
  blockchain/v2/types.go
  go.mod
  go.sum
Labels: WIP

#4022 Develop -> Master
  .circleci/config.yml
  README.md
  UPGRADING.md
  docs/guides/go-built-in.md
  docs/guides/go.md
  docs/guides/java.md
  docs/guides/kotlin.md
Labels: docs
