Repository tendermint/tendermint, pull requests merged in 2019-11, with the labels that each got.

#4083 mempool: moved TxInfo parameter into Mempool.CheckTx()
  CHANGELOG_PENDING.md
  consensus/mempool_test.go
  consensus/reactor_test.go
  consensus/replay_test.go
  mempool/bench_test.go
  mempool/cache_test.go
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/mempool.go
  mempool/reactor.go
  mock/mempool.go
  node/node_test.go
  rpc/client/rpc_test.go
  rpc/core/mempool.go
Labels: R4R, breaking, mempool

#4116 Doc link fixes
  docs/app-dev/app-architecture.md
  docs/spec/blockchain/encoding.md
Labels: docs

#4077 Add EXISTS condition to query grammar
  CHANGELOG_PENDING.md
  libs/pubsub/query/parser_test.go
  libs/pubsub/query/peg.go
  libs/pubsub/query/query.go
  libs/pubsub/query/query.peg
  libs/pubsub/query/query.peg.go
  libs/pubsub/query/query_test.go
  rpc/swagger/swagger.yaml
Labels: R4R

#4126 rpc: remove godoc comments in favor of swagger docs
  rpc/core/CONTRIBUTING.md
  rpc/core/abci.go
  rpc/core/blocks.go
  rpc/core/consensus.go
  rpc/core/events.go
  rpc/core/evidence.go
  rpc/core/health.go
  rpc/core/mempool.go
  rpc/core/net.go
  rpc/core/status.go
  rpc/core/tx.go
Labels: docs, rpc

#3774 Remove extra `if` statement
  state/store.go
  state/store_test.go
Labels: major-release

#3615 rpc: /block_results fix docs + write test + restructure response
  CHANGELOG_PENDING.md
  consensus/replay.go
  consensus/replay_test.go
  go.sum
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/types/responses.go
  rpc/swagger/swagger.yaml
  state/execution.go
  state/export_test.go
  state/state_test.go
  state/store.go
Labels: R4R, breaking, major-release, rpc

#3668 p2p/conn: Make non-malleable
  CHANGELOG_PENDING.md
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
Labels: R4R, major-release, p2p

#3783 Removal total tx num tx
  CHANGELOG_PENDING.md
  abci/types/messages_test.go
  abci/types/types.pb.go
  abci/types/types.proto
  consensus/mempool_test.go
  consensus/state.go
  docs/app-dev/app-development.md
  docs/spec/abci/abci.md
  docs/spec/blockchain/blockchain.md
  docs/tendermint-core/metrics.md
  lite/helpers.go
  rpc/swagger/swagger.yaml
  state/execution.go
  state/state.go
  state/store.go
  state/tx_filter_test.go
  state/txindex/indexer_service.go
  state/txindex/indexer_service_test.go
  state/validation.go
  state/validation_test.go
  store/store_test.go
  tools/tm-bench/statistics.go
  tools/tm-monitor/monitor/monitor.go
  tools/tm-monitor/monitor/network.go
  tools/tm-monitor/monitor/network_test.go
  tools/tm-monitor/monitor/node.go
  tools/tm-monitor/monitor/node_test.go
  types/block.go
  types/block_meta.go
  types/block_test.go
  types/events.go
  types/proto3/block.pb.go
  types/proto3/block.proto
  types/proto3_test.go
  types/protobuf.go
  types/protobuf_test.go
  types/test_util.go
Labels: breaking, major-release

#3856 Remove duplication of data in `ResultBlock `
  CHANGELOG_PENDING.md
  lite/proxy/wrapper.go
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/types/responses.go
  rpc/swagger/swagger.yaml
  tools/tm-bench/statistics.go
  types/block_meta.go
Labels: breaking, major-release

#4139 Add numtxs to swagger blockmeta
  rpc/swagger/swagger.yaml
Labels: rpc

#3993 Add pagination to /validators
  CHANGELOG_PENDING.md
  lite/client/provider.go
  lite/proxy/proxy.go
  p2p/switch_test.go
  rpc/client/httpclient.go
  rpc/client/interface.go
  rpc/client/localclient.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
  rpc/core/consensus.go
  rpc/core/routes.go
  rpc/lib/server/handlers_test.go
  rpc/swagger/swagger.yaml
Labels: breaking, major-release, rpc

#4151 Enforce Ordering in DuplicateVoteEvidence
  CHANGELOG_PENDING.md
  rpc/client/rpc_test.go
  types/evidence.go
  types/evidence_test.go
  types/vote.go
Labels: breaking

#4157 Remvoe errors package from libs
  CHANGELOG_PENDING.md
  libs/common/async.go
  libs/common/async_test.go
  libs/common/errors.go
  libs/common/errors_test.go
  lite/base_verifier.go
  lite/proxy/query.go
Labels: code-hygiene

#4101 Rc2/v0.32.8
  CHANGELOG.md
  CHANGELOG_PENDING.md
  abci/tests/test_app/main.go
  consensus/reactor_test.go
  consensus/state.go
  libs/pubsub/pubsub.go
  rpc/lib/client/ws_client.go
  version/version.go
Labels: R4R

#4169 [tm-bench]: Remove tm-bench in favor of tm-load-test
  CHANGELOG_PENDING.md
  README.md
  docs/tools/benchmarking.md
  tools.mk
  tools/tm-bench/Dockerfile
  tools/tm-bench/Dockerfile.dev
  tools/tm-bench/Makefile
  tools/tm-bench/README.md
  tools/tm-bench/main.go
  tools/tm-bench/statistics.go
  tools/tm-bench/transacter.go
  tools/tm-bench/transacter_test.go
Labels: code-hygiene

#4171 docs: minor doc touchups
  docs/README.md
  docs/app-dev/abci-cli.md
Labels: docs

#4158 Update tm-db to 0.3.0
  consensus/replay_file.go
  go.mod
  go.sum
  node/node.go
  state/state_test.go
  state/store_test.go
Labels: dependencies

#4007 types: prefix abci proto types
  CHANGELOG_PENDING.md
  Makefile
  abci/types/types.pb.go
  abci/types/types.proto
  crypto/merkle/merkle.pb.go
  crypto/merkle/merkle.proto
  libs/common/types.pb.go
  libs/common/types.proto
  rpc/grpc/types.pb.go
  rpc/grpc/types.proto
  types/proto3/block.pb.go
  types/proto3/block.proto
Labels: breaking, major-release

#4172 docs: remove specs, they live in spec repo
  docs/post.sh
  docs/pre.sh
  docs/spec/README.md
  docs/spec/abci/README.md
  docs/spec/abci/abci.md
  docs/spec/abci/apps.md
  docs/spec/abci/client-server.md
  docs/spec/blockchain/blockchain.md
  docs/spec/blockchain/encoding.md
  docs/spec/blockchain/readme.md
  docs/spec/blockchain/state.md
  docs/spec/consensus/abci.md
  docs/spec/consensus/bft-time.md
  docs/spec/consensus/consensus.md
  docs/spec/consensus/creating-proposal.md
  docs/spec/consensus/fork-accountability.md
  docs/spec/consensus/light-client.md
  docs/spec/consensus/readme.md
  docs/spec/consensus/signing.md
  docs/spec/consensus/wal.md
  docs/spec/p2p/config.md
  docs/spec/p2p/connection.md
  docs/spec/p2p/node.md
  docs/spec/p2p/peer.md
  docs/spec/p2p/readme.md
  docs/spec/reactors/block_sync/bcv1/img/bc-reactor-new-datastructs.png
  docs/spec/reactors/block_sync/bcv1/img/bc-reactor-new-fsm.png
  docs/spec/reactors/block_sync/bcv1/img/bc-reactor-new-goroutines.png
  docs/spec/reactors/block_sync/bcv1/impl-v1.md
  docs/spec/reactors/block_sync/img/bc-reactor-routines.png
  docs/spec/reactors/block_sync/img/bc-reactor.png
  docs/spec/reactors/block_sync/impl.md
  docs/spec/reactors/block_sync/reactor.md
  docs/spec/reactors/consensus/consensus-reactor.md
  docs/spec/reactors/consensus/consensus.md
  docs/spec/reactors/consensus/proposer-selection.md
  docs/spec/reactors/evidence/reactor.md
  docs/spec/reactors/mempool/concurrency.md
  docs/spec/reactors/mempool/config.md
  docs/spec/reactors/mempool/functionality.md
  docs/spec/reactors/mempool/messages.md
  docs/spec/reactors/mempool/reactor.md
  docs/spec/reactors/pex/pex.md
  docs/spec/reactors/pex/reactor.md
  docs/spec/reactors/readme.md
  docs/spec/scripts/crypto.go
Labels: docs

#4146 types: change `Commit` to consist of just signatures
  CHANGELOG_PENDING.md
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  consensus/mempool_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/types/round_state_test.go
  lite/helpers.go
  lite/proxy/validate_test.go
  lite2/test_helpers.go
  node/node_test.go
  rpc/swagger/swagger.yaml
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state.go
  state/validation.go
  state/validation_test.go
  store/store_test.go
  types/block.go
  types/block_test.go
  types/errors.go
  types/validator_set.go
  types/validator_set_test.go
  types/vote.go
  types/vote_set.go
  types/vote_set_test.go
  types/vote_test.go
Labels: breaking, major-release
