Repository tendermint/tendermint, pull requests merged in 2019-06, with the labels that each got.

#3705 docs: update RPC docs for /subscribe & /unsubscribe
  rpc/core/events.go
Labels: docs, rpc

#3632 libs/db: remove deprecated `LevelDBBackend` const
  CHANGELOG_PENDING.md
  UPGRADING.md
  libs/db/c_level_db.go
  libs/db/db.go
  libs/db/go_level_db.go
Labels: breaking

#3708 docs: update /block_results RPC docs
  CHANGELOG_PENDING.md
  rpc/core/blocks.go
  state/store.go
Labels: breaking, docs, rpc

#3711 p2p: remove NewNetAddressStringWithOptionalID
  CHANGELOG_PENDING.md
  node/node.go
  p2p/netaddress.go
  p2p/netaddress_test.go
  p2p/pex/pex_reactor.go
  p2p/transport_test.go
Labels: p2p

#3613 Switch to go mod
  .circleci/config.yml
  CHANGELOG_PENDING.md
  CONTRIBUTING.md
  DOCKER/Dockerfile.develop
  DOCKER/Dockerfile.testing
  Gopkg.lock
  Gopkg.toml
  Makefile
  Vagrantfile
  abci/tests/test_app/test.sh
  appveyor.yml
  docs/app-dev/abci-cli.md
  docs/app-dev/getting-started.md
  docs/introduction/install.md
  docs/tools/benchmarking.md
  docs/tools/monitoring.md
  go.mod
  go.sum
  libs/circle.yml
  networks/remote/integration.sh
  scripts/dist.sh
  scripts/get_tools.sh
  scripts/install/install_tendermint_arm.sh
  scripts/install/install_tendermint_bsd.sh
  scripts/install/install_tendermint_osx.sh
  scripts/install/install_tendermint_ubuntu.sh
  test/app/counter_test.sh
  test/docker/Dockerfile
  tools/build/Makefile
  tools/tm-bench/Dockerfile.dev
  tools/tm-bench/README.md
  tools/tm-monitor/Dockerfile.dev
  tools/tm-monitor/README.md
Labels: breaking

#3760 Update to contributing.md
  CONTRIBUTING.md
Labels: ready-for-review

#3757 Remove commented and unneeded code
  CHANGELOG_PENDING.md
  libs/common/colors.go
  libs/db/db_test.go
  libs/db/debug_db.go
  libs/errors/errors.go
Labels: code-hygiene, ready-for-review
