Repository tendermint/tendermint, pull requests merged in 2020-05, with the labels that each got.

#4764 types: return an error if voting power overflows
  CHANGELOG_PENDING.md
  types/validator_set.go
  types/validator_set_test.go
Labels: C:light, R:minor, S:automerge

#4784 lint: enable nolintlinter, disable on tests
  .github/workflows/lint.yaml
  .golangci.yml
  abci/types/application.go
  blockchain/v2/reactor.go
  blockchain/v2/routine.go
  consensus/wal.go
  crypto/ed25519/ed25519.go
  crypto/merkle/result.go
  crypto/xchacha20poly1305/xchachapoly.go
  libs/kv/result.go
  libs/pubsub/query/peg.go
  mempool/cache_test.go
  statesync/snapshots_test.go
  types/block_test.go
Labels: S:automerge, T:code-hygiene

#4762 lite2: migrate to proto
  lite2/client.go
  lite2/proxy/proxy.go
  lite2/store/db/db.go
  lite2/store/db/db_test.go
  lite2/trust_options.go
  lite2/verifier.go
  types/block.go
  types/block_test.go
  types/evidence.go
  types/validator.go
  types/validator_set.go
  types/validator_set_test.go
  types/validator_test.go
Labels: C:light, T:encoding

#4791 p2p: define p2p proto msgs
  proto/p2p/conn_msgs.pb.go
  proto/p2p/conn_msgs.proto
  proto/p2p/pex_msgs.pb.go
  proto/p2p/pex_msgs.proto
  proto/p2p/types.pb.go
  proto/p2p/types.proto
Labels: C:p2p, T:encoding

#4787 evidence: refactor evidence mocks throughout packages
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/common_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_test.go
  consensus/wal_generator.go
  evidence/mock/pool_mock.go
  state/execution_test.go
  state/mocks/evidence_pool.go
  state/services.go
  state/validation_test.go
Labels: C:evidence

#4795 p2p: return err on `signChallenge`
  CHANGELOG_PENDING.md
  p2p/conn/secret_connection.go
Labels: C:p2p, R:minor, T:code-hygiene

#4785 consensus: add comment as to why use mocks during replay
  consensus/common_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_stubs.go
  consensus/replay_test.go
  consensus/wal_generator.go
Labels: C:docs, R:minor, S:automerge

#4792 types: sort validators by voting power
  CHANGELOG_PENDING.md
  lite2/helpers_test.go
  rpc/swagger/swagger.yaml
  state/validation.go
  types/priv_validator.go
  types/validator_set.go
  types/validator_set_test.go
Labels: R:major, S:automerge, T:breaking

#4778 store: migration to proto
  CHANGELOG_PENDING.md
  blockchain/codec.go
  consensus/replay_test.go
  consensus/state.go
  evidence/pool_test.go
  evidence/reactor_test.go
  proto/consensus/msgs.pb.go
  proto/consensus/msgs.proto
  proto/store/types.pb.go
  proto/store/types.proto
  proto/types/types.pb.go
  proto/types/types.proto
  store/codec.go
  store/store.go
  store/store_test.go
  types/block.go
  types/block_meta.go
  types/block_test.go
  types/evidence.go
  types/part_set.go
Labels: T:encoding

#4804 consensus: fix TestSimulateValidatorsChange
  consensus/common_test.go
  consensus/replay_test.go
  types/event_bus_test.go
Labels: S:automerge

#4798 types: simplify VerifyCommitTrusting
  CHANGELOG_PENDING.md
  lite2/client.go
  lite2/verifier.go
  types/evidence.go
  types/validator_set.go
  types/validator_set_test.go
Labels: R:minor, S:automerge

#4805 rpc: handle panics during panic handling
  CHANGELOG_PENDING.md
  rpc/lib/server/http_server.go
Labels: R:minor, S:automerge

#4799 types: remove extra validation in VerifyCommit
  state/validation.go
  types/block.go
  types/validator_set.go
Labels: S:automerge

#4788 blockchain/v2: integrate with state sync
  blockchain/v2/io.go
  blockchain/v2/processor.go
  blockchain/v2/processor_context.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  blockchain/v2/scheduler.go
  blockchain/v2/scheduler_test.go
  node/node.go
Labels: S:automerge

#4796 consensus: fix and rename TestStateLockPOLRelock
  consensus/state.go
  consensus/state_test.go
Labels: C:consensus

#4807 p2p/pex: migrate to Protobuf
  p2p/netaddress.go
  p2p/pex/codec.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
  proto/p2p/pex_msgs.pb.go
  proto/p2p/pex_msgs.proto
Labels: T:encoding

#4808 ci: switch to official linter
  .github/workflows/lint.yaml
  .golangci.yml
  cmd/tendermint/commands/root_test.go
  libs/cli/helper.go
  libs/tempfile/tempfile_test.go
  statesync/chunks.go
  tools/tm-signer-harness/main.go
Labels: T:code-hygiene

#4809 abci: fix protobuf lint issues
  abci/example/kvstore/persistent_kvstore.go
  abci/types/types.pb.go
  abci/types/types.proto
  statesync/syncer.go
  statesync/syncer_test.go
Labels: C:abci, S:automerge, T:breaking, T:code-hygiene

#4759 mempool: allow ReapX and CheckTx functions to run in parallel
  CHANGELOG_PENDING.md
  consensus/replay_stubs.go
  libs/os/os.go
  mempool/clist_mempool.go
  mempool/doc.go
  mempool/mempool.go
  mempool/mock/mempool.go
  node/node.go
Labels: C:mempool, R:minor, S:automerge

#4810 pex: use highwayhash for pex bucket
  CHANGELOG_PENDING.md
  go.mod
  go.sum
  p2p/pex/addrbook.go
Labels: S:automerge

#4648 proto: move keys to oneof
  abci/example/kvstore/kvstore_test.go
  abci/example/kvstore/persistent_kvstore.go
  abci/types/pubkey.go
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/util.go
  consensus/reactor_test.go
  consensus/replay_test.go
  crypto/crypto.go
  crypto/ed25519/ed25519.go
  crypto/encoding/amino/encode_test.go
  crypto/multisig/threshold_pubkey.go
  crypto/secp256k1/secp256k1.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  go.sum
  p2p/conn/secret_connection_test.go
  proto/blockchain/msgs.pb.go
  proto/blockchain/msgs.proto
  proto/consensus/walmsgs.pb.go
  proto/consensus/walmsgs.proto
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  rpc/client/evidence_test.go
  rpc/client/helpers.go
  rpc/client/http/http.go
  rpc/client/rpc_test.go
  state/execution.go
  state/execution_test.go
  state/state_test.go
  types/evidence.go
  types/proposal_test.go
  types/protobuf.go
  types/protobuf_test.go
  types/vote_set.go
Labels: C:crypto, T:encoding

#4816 test: fix p2p test build breakage caused by Debian testing
  test/docker/Dockerfile
Labels: S:automerge

#4780 evidence: cap evidence to an absolute number
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  abci/types/types.proto
  consensus/reactor_test.go
  consensus/replay_stubs.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor_test.go
  node/node_test.go
  proto/types/params.pb.go
  proto/types/params.proto
  state/execution.go
  state/mocks/evidence_pool.go
  state/services.go
  state/tx_filter.go
  state/tx_filter_test.go
  state/validation.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/block.go
  types/block_test.go
  types/evidence.go
  types/params.go
  types/params_test.go
  types/protobuf.go
Labels: C:evidence, R:major, T:breaking

#4812 privval: retry GetPubKey/SignVote/SignProposal N times before
  CHANGELOG.md
  CHANGELOG_PENDING.md
  node/node.go
  node/node_test.go
  privval/doc.go
  privval/retry_signer_client.go
Labels: R:minor, S:automerge

#4819 swagger: remove duplicate blockID
  rpc/swagger/swagger.yaml
Labels: C:docs, C:rpc, S:automerge

#4817 test: revert Go 1.13→1.14 bump
  test/docker/Dockerfile
Labels: S:automerge

#4746 evidence: create proof of lock change and implement it in evidence store
  consensus/common_test.go
  consensus/reactor_test.go
  consensus/replay_stubs.go
  consensus/state.go
  consensus/state_test.go
  evidence/pool.go
  evidence/pool_test.go
  types/evidence.go
  types/evidence_test.go
  types/vote_set_test.go
Labels: C:consensus, C:evidence

#4820 statesync: use Protobuf instead of Amino for p2p traffic
  proto/statesync/types.pb.go
  proto/statesync/types.proto
  statesync/messages.go
  statesync/messages_test.go
  statesync/reactor.go
  statesync/reactor_test.go
  statesync/syncer.go
  statesync/syncer_test.go
Labels: S:automerge, T:encoding

#4822 abci: regenerate proto files
  abci/types/types.pb.go
  proto/types/params.pb.go
  types/params.go
  types/params_test.go
  types/protobuf.go
Labels: C:abci, C:evidence, S:automerge

#4825 abci: remove protoreplace script
  abci/types/protoreplace/protoreplace.go
Labels: S:automerge, T:code-hygiene

#4826 abci: remove python examples
  abci/example/js/.gitignore
  abci/example/js/README.md
  abci/example/python/abci/__init__.py
  abci/example/python/abci/msg.py
  abci/example/python/abci/reader.py
  abci/example/python/abci/server.py
  abci/example/python/abci/wire.py
  abci/example/python/app.py
  abci/example/python3/abci/__init__.py
  abci/example/python3/abci/msg.py
  abci/example/python3/abci/reader.py
  abci/example/python3/abci/server.py
  abci/example/python3/abci/wire.py
  abci/example/python3/app.py
  scripts/install-golangci-lint.sh
Labels: C:abci, S:automerge, T:code-hygiene

#4824 types: assert specific error in TestValSetUpdateOverflowRelated
  types/validator_set.go
  types/validator_set_test.go
Labels: S:automerge

#4831 libs: remove bech32
  CHANGELOG_PENDING.md
  libs/bech32/bech32.go
  libs/bech32/bech32_test.go
Labels: S:automerge, T:code-hygiene

#4832 rpc: use a struct to wrap all the global objects
  CHANGELOG_PENDING.md
  lite/proxy/proxy.go
  node/node.go
  rpc/core/abci.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/consensus.go
  rpc/core/dev.go
  rpc/core/env.go
  rpc/core/env_test.go
  rpc/core/events.go
  rpc/core/evidence.go
  rpc/core/mempool.go
  rpc/core/net.go
  rpc/core/net_test.go
  rpc/core/status.go
  rpc/core/tx.go
Labels: R:minor, S:automerge

#4833 mempool: do not launch broadcastTxRoutine if Broadcast is off
  mempool/reactor.go
  mempool/reactor_test.go
Labels: S:automerge

#4836 rpc: refactor lib folder
  CHANGELOG_PENDING.md
  Makefile
  cmd/tendermint/commands/lite.go
  lite/proxy/proxy.go
  lite/proxy/wrapper.go
  lite2/proxy/proxy.go
  lite2/proxy/routes.go
  lite2/rpc/client.go
  node/node.go
  rpc/client/http/http.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
  rpc/core/abci.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/consensus.go
  rpc/core/dev.go
  rpc/core/events.go
  rpc/core/evidence.go
  rpc/core/health.go
  rpc/core/mempool.go
  rpc/core/net.go
  rpc/core/net_test.go
  rpc/core/routes.go
  rpc/core/status.go
  rpc/core/tx.go
  rpc/grpc/api.go
  rpc/jsonrpc/client/args_test.go
  rpc/jsonrpc/client/decode.go
  rpc/jsonrpc/client/encode.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/http_json_client_test.go
  rpc/jsonrpc/client/http_uri_client.go
  rpc/jsonrpc/client/integration_test.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/client/ws_client_test.go
  rpc/jsonrpc/doc.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_json_handler_test.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/parse_test.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/jsonrpc/server/test.crt
  rpc/jsonrpc/server/test.key
  rpc/jsonrpc/server/ws_handler.go
  rpc/jsonrpc/server/ws_handler_test.go
  rpc/jsonrpc/test/data.json
  rpc/jsonrpc/test/integration_test.sh
  rpc/jsonrpc/test/main.go
  rpc/jsonrpc/types/types.go
  rpc/jsonrpc/types/types_test.go
  rpc/lib/server/http_params.go
  rpc/test/helpers.go
Labels: R:minor

#4834 proto: remove test files
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/typespb_test.go
  crypto/merkle/merkle.pb.go
  crypto/merkle/merkle.proto
  libs/kv/types.pb.go
  libs/kv/types.proto
  libs/kv/typespb_test.go
  rpc/grpc/types.pb.go
  rpc/grpc/types.proto
  rpc/grpc/typespb_test.go
Labels: S:automerge, T:code-hygiene

#4839 prevent proposer from proposing duplicate pieces of evidence
  CHANGELOG_PENDING.md
  node/node_test.go
  state/helpers_test.go
  state/state_test.go
  state/validation.go
  state/validation_test.go
  types/evidence.go
Labels: C:evidence

#4843 docs: move tcp-window.png to imgs/
  docs/imgs/tcp-window.png
  docs/introduction/architecture.md
Labels: C:docs, S:automerge

#4844 rpc/core: do not lock ConsensusState mutex
  CHANGELOG_PENDING.md
  rpc/core/blocks.go
  rpc/core/consensus.go
  rpc/core/env.go
  rpc/core/status.go
  rpc/swagger/swagger.yaml
Labels: R:minor, S:automerge

#4851 lint: various fixes
  .github/workflows/lint.yaml
  blockchain/v1/reactor_fsm.go
  consensus/state.go
  lite/proxy/proxy.go
  lite2/provider/http/http_test.go
  mempool/clist_mempool.go
  node/node.go
  p2p/node_info_test.go
  p2p/pex/pex_reactor.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/ws_client.go
  state/state_test.go
  store/store.go
  store/store_test.go
Labels: S:automerge, T:code-hygiene

#4847 p2p: return masked IP (not the actual IP) in addrbook#groupKey
  CHANGELOG_PENDING.md
  p2p/netaddress.go
  p2p/pex/addrbook.go
  p2p/pex/addrbook_test.go
Labels: R:minor, S:automerge

#4855 ci: add paths
  .github/workflows/lint.yaml
  .github/workflows/proto.yml
  README.md
Labels: S:automerge

#4850 lite2: fix pivot height
  lite2/client.go
  lite2/client_test.go
Labels: C:light, T:bug

#4852 signing: change signbytes
  CHANGELOG_PENDING.md
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set_test.go
  crypto/ed25519/ed25519.go
  lite2/helpers_test.go
  privval/file.go
  privval/file_test.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_requestHandler.go
  rpc/client/evidence_test.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness.go
  types/block.go
  types/canonical.go
  types/evidence.go
  types/evidence_test.go
  types/priv_validator.go
  types/proposal.go
  types/proposal_test.go
  types/test_util.go
  types/validator_set_test.go
  types/vote.go
  types/vote_test.go
Labels: T:encoding

#4864 ci: bump the timeout for test_coverage
  .circleci/config.yml
Labels: S:automerge

#4871 blockchain[v1]: increased timing of peer tests to avoid random failures
  blockchain/v1/peer_test.go
Labels: C:sync, T:test

#4853 proto: add proto files for ibc unblock
  crypto/encoding/codec.go
  libs/bits/bit_array.go
  libs/bits/bit_array_test.go
  proto/blockchain/msgs.pb.go
  proto/blockchain/msgs.proto
  proto/consensus/msgs.pb.go
  proto/consensus/msgs.proto
  proto/consensus/walmsgs.pb.go
  proto/consensus/walmsgs.proto
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  proto/crypto/merkle/types.pb.go
  proto/crypto/merkle/types.proto
  proto/p2p/conn_msgs.pb.go
  proto/p2p/conn_msgs.proto
  proto/p2p/pex_msgs.pb.go
  proto/p2p/pex_msgs.proto
  proto/p2p/types.pb.go
  proto/p2p/types.proto
  proto/privval/msgs.pb.go
  proto/privval/msgs.proto
  proto/privval/types.pb.go
  proto/privval/types.proto
  proto/state/types.pb.go
  proto/state/types.proto
  proto/statesync/types.pb.go
  proto/statesync/types.proto
  proto/store/types.pb.go
  proto/store/types.proto
  proto/types/events.pb.go
  proto/types/events.proto
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  proto/types/params.pb.go
  proto/types/params.proto
  proto/types/types.pb.go
  proto/types/types.proto
  proto/version/version.pb.go
  proto/version/version.proto
  types/block.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
  types/part_set.go
  types/part_set_test.go
  types/proposal.go
  types/proposal_test.go
  types/validator.go
  types/validator_set.go
  types/validator_set_test.go
  types/validator_test.go
  types/vote.go
  types/vote_test.go
Labels: R:minor, S:automerge, T:encoding

#4874 libs: remove kv
  CHANGELOG_PENDING.md
  UPGRADING.md
  abci/types/result.go
  libs/kv/kvpair.go
  libs/kv/result.go
  libs/kv/types.pb.go
  libs/kv/types.proto
Labels: S:automerge, T:code-hygiene

#4878 ci: migrate localnet to github actions
  .circleci/config.yml
  .github/workflows/lint.yaml
  .github/workflows/net.yml
  .github/workflows/proto.yml
  .github/workflows/tests.yml
Labels: S:automerge

#4885 test/abci: use random socket names to avoid collisions
  abci/example/example_test.go
Labels: S:automerge, T:test

#4886 test/blockchain/v0: mitigate test data race
  blockchain/v0/reactor_test.go
Labels: S:automerge, T:test

#4876 types: remove unnecessary sort call
  mempool/reactor_test.go
  types/validator_set_test.go
Labels: S:automerge

#4881 p2p/test: wait for listener to get ready
  p2p/transport_test.go
Labels: S:automerge, T:test

#4890 lite2/http: fix provider test
  lite2/provider/http/http_test.go
Labels: C:light, T:test

#4893 p2p/test: fix Switch test race condition
  p2p/switch.go
  p2p/switch_test.go
Labels: T:test

#4894 rpc/test: fix test race in TestAppCalls
  rpc/client/rpc_test.go
Labels: S:automerge, T:test

#4900 lite2: fix pivot height during bisection (#4850)
  lite2/client.go
  lite2/client_test.go
Labels: C:light

#4899 consensus: bring back log.Error statement
  consensus/state.go
Labels: R:minor

#4813 privval: migrate to protobuf
  CHANGELOG_PENDING.md
  config/toml.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set_test.go
  crypto/ed25519/ed25519.go
  libs/encode/json.go
  libs/math/safemath.go
  lite2/helpers_test.go
  privval/codec.go
  privval/errors.go
  privval/file.go
  privval/file_test.go
  privval/messages.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_endpoint.go
  privval/signer_listener_endpoint.go
  privval/signer_requestHandler.go
  privval/signer_server.go
  proto/privval/msgs.pb.go
  proto/privval/msgs.proto
  proto/privval/types.pb.go
  proto/privval/types.proto
  proto/types/canonical.pb.go
  proto/types/canonical.proto
  proto/types/types.pb.go
  proto/types/types.proto
  rpc/client/evidence_test.go
  state/execution_test.go
  state/tx_filter_test.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/block.go
  types/block_test.go
  types/canonical.go
  types/evidence.go
  types/evidence_test.go
  types/part_set.go
  types/priv_validator.go
  types/proposal.go
  types/proposal_test.go
  types/test_util.go
  types/validator_set_test.go
  types/vote.go
  types/vote_set.go
  types/vote_test.go
Labels: T:encoding

#4903 types/test: remove slow test cases in TestValSetUpdatePriorityOrderTests
  types/validator_set_test.go
Labels: S:automerge, T:test

#4908 rpc/test: wait for mempool CheckTx callback
  rpc/client/rpc_test.go
Labels: S:automerge, T:test

#4901 p2p: remove nil guard
  p2p/switch.go
Labels: C:p2p, S:automerge

#4907 rpc/test: wait for subscription in TestTxEventsSentWithBroadcastTxAsync
  rpc/client/event_test.go
Labels: S:automerge, T:test

#4912 ci: add timeouts
  .github/workflows/lint.yaml
  .github/workflows/net.yml
  .github/workflows/proto.yml
  .github/workflows/tests.yml
Labels: S:automerge

#4909 CONTRIBUTING: update minor release process
  CONTRIBUTING.md
Labels: S:automerge

#4895 only retrieve pubkey once for all validators (partially fixes #4865)
  CHANGELOG_PENDING.md
  consensus/state.go
Labels: C:consensus, R:minor, S:automerge, T:validator

#4915 CHANGELOG: update to reflect 0.33.5
  CHANGELOG.md
  CHANGELOG_PENDING.md
  version/version.go
Labels: S:automerge

#4917 rpc: increase waitForEventTimeout to 8 seconds
  rpc/client/event_test.go
Labels: S:automerge, T:test

#4918 CHANGELOG: add 0.32.12 changelog entry
  CHANGELOG.md
Labels: S:automerge
