Repository tendermint/tendermint, pull requests merged in 2020-11, with the labels that each got.

#5461 light: model-based tests
  libs/bytes/bytes.go
  light/mbt/doc.go
  light/mbt/driver_test.go
  light/mbt/json/MC4_4_faulty_Test2NotEnoughTrustFailure.json
  light/mbt/json/MC4_4_faulty_Test2NotEnoughTrustSuccess.json
  light/mbt/json/MC4_4_faulty_Test3NotEnoughTrustFailure.json
  light/mbt/json/MC4_4_faulty_Test3NotEnoughTrustSuccess.json
  light/mbt/json/MC4_4_faulty_TestFailure.json
  light/mbt/json/MC4_4_faulty_TestHeaderFromFuture.json
  light/mbt/json/MC4_4_faulty_TestSuccess.json
  light/mbt/json/MC4_4_faulty_TestUntrustedBeforeTrusted.json
  light/mbt/json/MC4_4_faulty_TestValsetDifferentAllSteps.json
  light/verifier.go
Labels: stale

#5538 light: run detector for sequentially validating light client
  light/client.go
  light/detector.go
  light/detector_test.go
  light/errors.go
Labels: T:security

#5609 ci: use gh pages
  .github/workflows/docs.yml
  Makefile
Labels: C:docs

#5614 docs: bump vuepress-theme-cosmos
  docs/package-lock.json
  docs/package.json
Labels: S:automerge

#5616 evidence: structs can independently form abci evidence
  CHANGELOG_PENDING.md
  consensus/byzantine_test.go
  consensus/reactor_test.go
  consensus/state.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/reactor_test.go
  evidence/verify.go
  evidence/verify_test.go
  light/detector.go
  node/node_test.go
  proto/tendermint/evidence/types.pb.go
  proto/tendermint/evidence/types.proto
  proto/tendermint/types/block.pb.go
  proto/tendermint/types/block.proto
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  rpc/client/evidence_test.go
  state/execution.go
  state/execution_test.go
  state/mocks/evidence_pool.go
  state/services.go
  state/validation.go
  state/validation_test.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/tests/evidence_test.go
  test/maverick/consensus/state.go
  types/block.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf.go
  types/protobuf_test.go
Labels: S:backport

#5618 test: fix various E2E test issues (#5576)
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/testnet.go
  test/e2e/runner/cleanup.go
  test/e2e/runner/main.go
  test/e2e/runner/start.go
  test/e2e/tests/app_test.go
  test/e2e/tests/block_test.go
  test/e2e/tests/validator_test.go
Labels: S:backport

#5607 blockchain/v2: remove peers from the processor
  blockchain/v2/reactor.go
  blockchain/v2/scheduler.go
  blockchain/v2/scheduler_test.go
Labels: S:automerge

#5612 cmd: add support for --key
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/gen_validator.go
  cmd/tendermint/commands/init.go
  cmd/tendermint/commands/reset_priv_validator.go
  cmd/tendermint/commands/testnet.go
  consensus/common_test.go
  consensus/wal_generator.go
  node/node.go
  node/node_test.go
  privval/file.go
  privval/file_test.go
  rpc/client/evidence_test.go
  rpc/test/helpers.go
  test/e2e/app/main.go
  test/e2e/generator/generate.go
  test/e2e/networks/single.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  test/maverick/consensus/wal_generator.go
  test/maverick/main.go
Labels: T:ux, T:validator

#5632 crypto: adopt zip215 ed25519 verification
  CHANGELOG_PENDING.md
  crypto/ed25519/ed25519.go
  go.mod
  go.sum
Labels: C:crypto, R:major, T:breaking

#5638 privval: increase read/write timeout to 5s and calculate ping interval based on it
  CHANGELOG_PENDING.md
  privval/signer_dialer_endpoint.go
  privval/signer_endpoint.go
  privval/signer_listener_endpoint.go
  privval/signer_listener_endpoint_test.go
  privval/socket_listeners.go
Labels: S:automerge

#5639 bump go version to 1.15
  .github/workflows/coverage.yml
  .github/workflows/e2e-nightly.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  README.md
  Vagrantfile
  go.mod
  networks/remote/integration.sh
  test/docker/Dockerfile
Labels: S:automerge

#5641 remove Vagrantfile
  CONTRIBUTING.md
  Vagrantfile
  tests.mk
Labels: S:automerge

#5642 privval: reset pingTimer to avoid sending unnecessary pings
  privval/signer_listener_endpoint.go
Labels: S:automerge

#5647 ci: fix docker deployment
  .github/workflows/docker.yml
Labels: S:automerge

#5650 proto: buf for everything
  CONTRIBUTING.md
  Makefile
  proto/tendermint/types/evidence.proto
  proto/tendermint/types/types.proto
  scripts/protocgen.sh
  test/Makefile
  tools/Makefile
Labels: S:automerge

#5654 libs/os: remove unused aliases, add test cases
  CHANGELOG_PENDING.md
  config/toml.go
  libs/autofile/autofile_test.go
  libs/fail/fail.go
  libs/os/os.go
  libs/os/os_test.go
  p2p/conn/secret_connection_test.go
  proxy/multi_app_conn.go
  types/genesis.go
Labels: S:automerge

#5657 go.mod: upgrade iavl and deps
  go.mod
  go.sum
Labels: S:automerge, T:dependencies

#5659 backport dep bumps
  go.mod
  go.sum
Labels: S:backport

#5666 privval: increase read/write timeout to 5s and calculate ping interva…
  CHANGELOG_PENDING.md
  privval/signer_dialer_endpoint.go
  privval/signer_endpoint.go
  privval/signer_listener_endpoint.go
  privval/signer_listener_endpoint_test.go
  privval/socket_listeners.go
Labels: S:backport

#5668 privval: reset pingTimer to avoid sending unnecessary pings (#5642)
  privval/signer_listener_endpoint.go
Labels: S:backport

#5669 Backport v0.34.0-rc7: #5661
  CHANGELOG.md
  CHANGELOG_PENDING.md
  rpc/jsonrpc/client/http_json_client.go
Labels: S:backport

#5637 docs: add P2P architecture ADR
  docs/architecture/README.md
  docs/architecture/adr-062-p2p-architecture.md
  docs/architecture/img/adr-062-architecture.svg
Labels: C:docs, C:p2p, S:automerge

#5672 privval: duplicate SecretConnection from p2p package
  privval/secret_connection.go
  privval/socket_dialers.go
  privval/socket_listeners.go
  proto/tendermint/privval/types.pb.go
  proto/tendermint/privval/types.proto
Labels: S:automerge

#5674 ci: remove `add-path`
  .github/workflows/tests.yml
  crypto/ed25519/ed25519.go
Labels: S:automerge

#5678 e2e: use ed25519 for secretConn (remote signer)
  privval/signer_requestHandler.go
  test/e2e/app/main.go
Labels: S:automerge

#5679 docs: warn developers about calling blocking funcs in Receive
  blockchain/v0/reactor.go
  blockchain/v1/reactor.go
  blockchain/v2/reactor.go
  consensus/reactor.go
  evidence/reactor.go
  mempool/reactor.go
  p2p/base_reactor.go
  p2p/pex/pex_reactor.go
  statesync/reactor.go
Labels: S:automerge

#5684 p2p: remove unused MakePoWTarget()
  CHANGELOG_PENDING.md
  p2p/key.go
  p2p/key_test.go
Labels: S:automerge

#5683 light: fractions to u64
  CHANGELOG_PENDING.md
  libs/math/fraction.go
  libs/math/fraction_test.go
  light/verifier_test.go
  types/validator_set.go
Labels: S:backport

#5677 light: ensure required fields are present for verification
  light/verifier.go
Labels: C:light

#5699 codecov: validate codecov.yml
  .github/codecov.yml
Labels: S:automerge

#5701 blockchain/v1: handle peers without blocks
  CHANGELOG_PENDING.md
  blockchain/v1/peer.go
  blockchain/v1/pool.go
  blockchain/v1/reactor_fsm.go
  blockchain/v1/reactor_fsm_test.go
Labels: S:automerge

#5702 test/e2e: enable v1 and v2 blockchains
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
Labels: S:automerge

#5604 docs: add nodes section
  docs/architecture/adr-056-light-client-amnesia-attacks.md
  docs/nodes/README.md
  docs/nodes/configuration.md
  docs/nodes/light-client.md
  docs/nodes/local_config.png
  docs/nodes/metrics.md
  docs/nodes/sentry_layout.png
  docs/nodes/state-sync.md
  docs/nodes/validators.md
  docs/package-lock.json
  docs/tendermint-core/README.md
  docs/tendermint-core/configuration.md
  docs/tendermint-core/light-client.md
  docs/tendermint-core/metrics.md
  docs/tendermint-core/state-sync.md
  docs/tendermint-core/validators.md
  docs/tools/README.md
  docs/tools/debuging/README.md
  docs/tools/debuging/pro.md
Labels: C:docs, S:automerge

#5707 crypto: fix infinite recursion in Secp256k1 string formatting
  CHANGELOG_PENDING.md
  crypto/secp256k1/secp256k1.go
Labels: S:automerge

#5709 crypto: fix infinite recursion in Secp256k1 string formatting (#5707)
  CHANGELOG_PENDING.md
  crypto/secp256k1/secp256k1.go
Labels: S:automerge, S:backport

#5706 version: add abci version to handshake
  CHANGELOG_PENDING.md
  UPGRADING.md
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
  proxy/version.go
Labels: S:automerge, T:enhancement

#5710 test: fix TestByzantinePrevoteEquivocation flake
  consensus/byzantine_test.go
Labels: S:automerge, T:test

#5714 ci: remove circle
  .circleci/config.yml
  .github/workflows/docs.yml
  Makefile
Labels: S:automerge

#5700 ci: build for 32 bit, libs: fix overflow
  .github/workflows/coverage.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  libs/math/fraction.go
Labels: S:automerge

#5724 ci: build for 32 bit, libs: fix overflow (#5700)
  .github/workflows/coverage.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  libs/math/fraction.go
Labels: S:backport

#5715 test: fix TestByzantinePrevoteEquivocation flake (#5710)
  consensus/byzantine_test.go
Labels: S:backport, T:test

#5673 abci: modify Client interface and socket client
  CHANGELOG_PENDING.md
  abci/client/client.go
  abci/client/doc.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/mocks/client.go
  abci/client/socket_client.go
  abci/client/socket_client_test.go
  abci/cmd/abci-cli/abci-cli.go
  abci/example/example_test.go
  abci/example/kvstore/kvstore_test.go
  abci/tests/server/client.go
  abci/tests/test_app/app.go
  abci/types/application.go
  consensus/replay.go
  consensus/replay_test.go
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/mempool.go
  node/node.go
  proxy/app_conn.go
  proxy/app_conn_test.go
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  rpc/core/abci.go
  rpc/core/mempool.go
  rpc/grpc/client_server.go
  state/execution.go
  statesync/reactor.go
  statesync/reactor_test.go
  statesync/syncer.go
  statesync/syncer_test.go
  test/maverick/consensus/replay.go
  test/maverick/node/node.go
Labels: T:breaking
