Repository tendermint/tendermint, pull requests merged in 2020-04, with the labels that each got.

#4628 rpc/client: split out client packages
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/debug/dump.go
  cmd/tendermint/commands/debug/kill.go
  cmd/tendermint/commands/debug/util.go
  cmd/tendermint/commands/lite.go
  lite/client/provider.go
  lite/proxy/query_test.go
  lite2/client_benchmark_test.go
  lite2/client_test.go
  lite2/example_test.go
  lite2/helpers_test.go
  lite2/provider/http/http.go
  lite2/provider/http/http_test.go
  lite2/verifier_test.go
  rpc/client/examples_test.go
  rpc/client/http/http.go
  rpc/client/local/local.go
  rpc/client/rpc_test.go
  rpc/swagger/swagger.yaml
Labels: S:automerge

#4610 ADR-053: strengthen and simplify the state sync ABCI interface
  docs/architecture/adr-053-state-sync-prototype.md
Labels: S:automerge

#4617 evidence: remove pubkey from DuplicateVoteEvidence
  CHANGELOG_PENDING.md
  evidence/reactor_test.go
  rpc/client/rpc_test.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf_test.go
  types/vote.go
Labels: C:evidence

#4602 valIndex int32 to uint32
  Makefile
  blockchain/v1/reactor_test.go
  consensus/common_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/types/height_vote_set_test.go
  consensus/types/round_state.go
  evidence/pool.go
  go.sum
  libs/math/safemath.go
  lite/helpers.go
  lite2/helpers_test.go
  mempool/reactor.go
  privval/file_test.go
  rpc/client/rpc_test.go
  rpc/core/status.go
  state/execution_test.go
  state/helpers_test.go
  state/state.go
  state/state_test.go
  state/validation.go
  state/validation_test.go
  types/block.go
  types/block_test.go
  types/errors.go
  types/events.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf.go
  types/test_util.go
  types/validator_set.go
  types/validator_set_test.go
  types/vote.go
  types/vote_set.go
  types/vote_set_test.go
  types/vote_test.go
Labels: T:code-hygiene

#4588 add support for block pruning via ABCI Commit response
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/types/types.pb.go
  abci/types/types.proto
  blockchain/v0/pool.go
  blockchain/v0/pool_test.go
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  blockchain/v1/peer.go
  blockchain/v1/peer_test.go
  blockchain/v1/pool.go
  blockchain/v1/pool_test.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_fsm.go
  blockchain/v1/reactor_test.go
  blockchain/v2/io.go
  blockchain/v2/processor_context.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  blockchain/v2/scheduler.go
  blockchain/v2/scheduler_test.go
  config/config_test.go
  consensus/reactor.go
  consensus/replay.go
  consensus/replay_test.go
  consensus/state.go
  evidence/pool.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/consensus.go
  rpc/core/status.go
  rpc/core/types/responses.go
  rpc/swagger/swagger.yaml
  state/errors.go
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/services.go
  state/store.go
  state/store_test.go
  store/store.go
  store/store_test.go
Labels: C:consensus, C:sync, S:automerge, T:feature

#4633 keys: remove suffixes
  CHANGELOG_PENDING.md
  abci/example/kvstore/persistent_kvstore.go
  crypto/README.md
  crypto/ed25519/ed25519.go
  crypto/encoding/amino/amino.go
  crypto/encoding/amino/encode_test.go
  crypto/multisig/codec.go
  crypto/multisig/threshold_pubkey.go
  crypto/multisig/threshold_pubkey_test.go
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_cgo.go
  crypto/secp256k1/secp256k1_cgo_test.go
  crypto/secp256k1/secp256k1_nocgo.go
  crypto/secp256k1/secp256k1_test.go
  crypto/sr25519/codec.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
  privval/file_test.go
  privval/socket_listeners.go
  privval/socket_listeners_test.go
  rpc/client/rpc_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/main.go
  types/protobuf.go
  types/validator_set_test.go
Labels: C:crypto, T:code-hygiene

#4624 proto: move proto types to proto dir
  SECURITY.md
  abci/example/kvstore/kvstore_test.go
  abci/types/messages_test.go
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/typespb_test.go
  blockchain/v1/reactor_test.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set.go
  consensus/types/height_vote_set_test.go
  go.mod
  go.sum
  lite/helpers.go
  lite2/helpers_test.go
  privval/file.go
  privval/file_test.go
  privval/signer_client_test.go
  proto/libs/bits/types.pb.go
  proto/libs/bits/types.proto
  proto/types/types.pb.go
  proto/types/types.proto
  rpc/client/rpc_test.go
  state/validation_test.go
  store/store_test.go
  tools/tm-signer-harness/internal/test_harness.go
  types/block.go
  types/block.pb.go
  types/block.proto
  types/block_test.go
  types/canonical.go
  types/evidence.go
  types/evidence_test.go
  types/header.go
  types/part_set.go
  types/proposal.go
  types/proposal_test.go
  types/proto3_test.go
  types/protobuf.go
  types/protobuf_test.go
  types/result.go
  types/signed_msg_type.go
  types/test_util.go
  types/types.pb.go
  types/types.proto
  types/validator_set_test.go
  types/vote.go
  types/vote_set.go
  types/vote_set_test.go
  types/vote_test.go
Labels: T:encoding

#4636 upgrading: add note on rpc/client subpackages
  UPGRADING.md
Labels: S:automerge

#4639 config: allow fastsync.version = v2
  config/config.go
Labels: C:sync, S:automerge

#4620 lite2: Prevent falsely returned double voting error
  types/validator_set.go
  types/validator_set_test.go
Labels: C:light, S:automerge

#4634 keys: change to []bytes for keys
  abci/example/kvstore/persistent_kvstore.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/encoding.go
  crypto/encoding/amino/encode_test.go
  crypto/secp256k1/encoding.go
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_test.go
  crypto/sr25519/encoding.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  privval/file_test.go
  rpc/client/rpc_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/main.go
  types/block.go
  types/protobuf.go
  types/validator_set_test.go
  types/vote_test.go
Labels: C:crypto, R:major, T:breaking

#4649 Default to http scheme in lite2 provider.New
  lite2/provider/http/http.go
  lite2/provider/http/http_test.go
Labels: C:light, T:ux

#4621 p2p: PEX message abuse should ban as well as disconnect
  CHANGELOG_PENDING.md
  p2p/pex/errors.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
Labels: C:p2p, S:automerge

#4652 lint: add review dog
  .github/workflows/lint.yaml
  blockchain/v2/reactor_test.go
  lite2/client.go
  state/execution.go
  state/store_test.go
  types/validator_set_test.go
Labels: T:code-hygiene

#4632 evidence: check evidence hasn't already been stored
  CHANGELOG_PENDING.md
  evidence/errors.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/store.go
  evidence/store_test.go
  rpc/core/evidence.go
Labels: C:evidence, S:automerge

#4650 proto: add Validatorset as proto type
  crypto/encoding/codec.go
  crypto/encoding/codec_fuzz_test.go
  go.mod
  libs/math/safemath.go
  proto/crypto/types.pb.go
  proto/crypto/types.proto
  proto/types/types.pb.go
  proto/types/types.proto
  types/validator.go
  types/validator_set.go
Labels: T:encoding

#4654 evidence: transition to proto
  evidence/codec.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/store.go
  node/node_test.go
  proto/evidence/msgs.pb.go
  proto/evidence/msgs.proto
  proto/types/types.pb.go
  proto/types/types.proto
  types/evidence.go
Labels: C:evidence, T:encoding

#4656 blockchain: v1 removal
  blockchain/v1/codec.go
  blockchain/v1/peer.go
  blockchain/v1/peer_test.go
  blockchain/v1/pool.go
  blockchain/v1/pool_test.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_fsm.go
  blockchain/v1/reactor_fsm_test.go
  blockchain/v1/reactor_test.go
  config/config.go
  config/config_test.go
  config/toml.go
  docs/tendermint-core/configuration.md
  node/node.go
Labels: C:sync, T:breaking

#4658 Docs website update
  docs/package-lock.json
  docs/package.json
Labels: C:docs

#4660 README: specify supported versions
  README.md
Labels: S:automerge

#4657 proto: seperate some types
  crypto/encoding/codec.go
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  proto/evidence/msgs.pb.go
  proto/evidence/msgs.proto
  proto/types/block.pb.go
  proto/types/block.proto
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  proto/types/types.pb.go
  proto/types/types.proto
  proto/types/validator.pb.go
  proto/types/validator.proto
Labels: T:code-hygiene

#4669 mergify: use PR title and body for squash merge commit
  .mergify.yml
Labels: S:automerge

#4671 blockchain/v2: allow setting nil switch, for CustomReactors()
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
Labels: S:automerge

#4667 evidence: both MaxAgeDuration and MaxAgeNumBlocks need to be surpassed
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  state/validation.go
Labels: C:evidence, T:security

#4676 dep: bump protobuf, cobra, btcutil & std lib deps
  go.mod
  go.sum
Labels: T:dependencies

#4677 version: make version a proto type
  abci/example/kvstore/kvstore.go
  consensus/replay.go
  consensus/replay_test.go
  node/node_test.go
  p2p/node_info.go
  proto/types/types.pb.go
  proto/types/types.proto
  proto/types/validator.pb.go
  proto/version/version.pb.go
  proto/version/version.proto
  proxy/version.go
  state/state.go
  types/block_test.go
  types/header.go
  types/protobuf.go
  types/protobuf_test.go
  version/version.go
Labels: T:encoding

#4679 state: define types in proto
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/typespb_test.go
  proto/state/types.pb.go
  proto/state/types.proto
  proto/types/params.pb.go
  proto/types/params.proto
  rpc/core/tx.go
  state/execution.go
  state/state_test.go
  state/txindex/indexer.go
  state/txindex/indexer_service_test.go
  state/txindex/kv/codec.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
  state/txindex/null/null.go
  types/event_bus.go
  types/event_bus_test.go
  types/events.go
  types/tx.go
Labels: T:encoding

#4683 changelog: add entries from secruity releases
  CHANGELOG.md
Labels: S:automerge

#4680 types: migrate params to proto
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/typespb_test.go
  consensus/replay.go
  consensus/replay_test.go
  evidence/pool.go
  evidence/pool_test.go
  proto/state/types.pb.go
  proto/state/types.proto
  proto/types/params.pb.go
  proto/types/params.proto
  rpc/core/types/responses.go
  state/execution.go
  state/execution_test.go
  state/export_test.go
  state/helpers_test.go
  state/state.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/validation.go
  types/genesis.go
  types/params.go
  types/params_test.go
  types/protobuf.go
  types/protobuf_test.go
Labels: T:encoding

#4684 docs: amend adr-54 with changes made in Cosmos-SDK
  docs/architecture/adr-054-crypto-encoding-2.md
Labels: C:docs

#4685 blockchain/v2: don't broadcast base if height is 0
  blockchain/v2/io.go
Labels: S:automerge

#4596 minor release process change
  CONTRIBUTING.md
Labels: R:minor, S:automerge

#4693 lite2: verify ConsensusHash in rpc client
  lite2/rpc/client.go
Labels: S:automerge

#4625 docs/architecture: create adr 56: prove amnesia attack
  docs/architecture/adr-056-proving-amnesia-attacks.md
  docs/imgs/tm-amnesia-attack.png
Labels: S:automerge

#4699 bump ABCI version to 0.16.2 due to ResponseCommit.retain_height
  CHANGELOG_PENDING.md
  version/version.go
Labels: S:automerge

#4700 fix linter warnings
  evidence/store_test.go
  types/proto3_test.go
  types/protobuf_test.go
Labels: S:automerge, T:code-hygiene

#4701 clarify service logging
  libs/service/service.go
Labels: S:automerge

#4702 blockstore: allow initial SaveBlock() at any height
  store/store.go
  store/store_test.go
Labels: S:automerge

#4689 ci: transition some ci to github actions
  .circleci/config.yml
  .github/workflows/lint.yaml
  .github/workflows/tests.yml
Labels: S:automerge

#4706 p2p/pex: fix DATA RACE
  p2p/pex/pex_reactor_test.go
Labels: S:automerge

#4703 lite2/rpc: verify block results and validators
  CHANGELOG_PENDING.md
  lite2/rpc/client.go
  rpc/client/rpc_test.go
  rpc/core/consensus.go
  rpc/core/types/responses.go
  rpc/swagger/swagger.yaml
Labels: C:light, C:rpc

#4713 rc1/v0.33.4
  CHANGELOG.md
  CHANGELOG_PENDING.md
  UPGRADING.md
  version/version.go
Labels: S:automerge

#4663 proto: utility functions ToProto and FromProto
  crypto/encoding/codec.go
  libs/bits/bit_array.go
  libs/bits/bit_array_test.go
  proto/types/params.pb.go
  proto/types/types.pb.go
  proto/types/types.proto
  proto/types/validator.pb.go
  proto/types/validator.proto
  types/block.go
  types/block_test.go
  types/evidence.go
  types/header.go
  types/header_test.go
  types/part_set.go
  types/part_set_test.go
  types/proposal.go
  types/proposal_test.go
  types/protobuf.go
  types/utils.go
  types/validator.go
  types/validator_set.go
  types/validator_set_test.go
  types/validator_test.go
  types/vote.go
  types/vote_set.go
  types/vote_test.go
Labels: T:encoding

#4712 docs: mention unbonding period in MaxAgeNumBlocks/MaxAgeDuration
  docs/tendermint-core/using-tendermint.md
  types/params.go
Labels: S:automerge

#4532 evidence: handling evidence from light client(s)
  CHANGELOG_PENDING.md
  abci/types/types.proto
  docs/architecture/adr-047-handling-evidence-from-light-client.md
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor_test.go
  evidence/store_test.go
  lite2/client.go
  lite2/client_test.go
  lite2/errors.go
  lite2/provider/http/http.go
  lite2/provider/http/http_test.go
  lite2/provider/mock/deadmock.go
  lite2/provider/mock/mock.go
  lite2/provider/provider.go
  lite2/verifier_test.go
  node/node.go
  node/node_test.go
  rpc/client/evidence_test.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/evidence.go
  state/store.go
  state/validation.go
  types/block.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf.go
  types/vote.go
Labels: C:evidence, R:minor

#4716 template: add labels to pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S:automerge

#4717 Updated docs website
  docs/package-lock.json
  docs/package.json
Labels: C:docs, S:automerge

#4466 indexer: allow to index an event at runtime
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/types/messages_test.go
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/typespb_test.go
  docs/app-dev/indexing-transactions.md
  libs/kv/types.proto
  rpc/client/rpc_test.go
  state/state_test.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
  types/event_bus_test.go
Labels: R:major, T:breaking

#4719 abci/server: print panic & stack trace to STDERR if logger is not set
  CHANGELOG_PENDING.md
  abci/server/grpc_server.go
  abci/server/socket_server.go
Labels: C:abci, R:minor, S:automerge

#4637 blockchain: proto transition
  CHANGELOG_PENDING.md
  blockchain/codec.go
  blockchain/codec_test.go
  blockchain/msgs.go
  blockchain/msgs_test.go
  blockchain/v0/codec.go
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  blockchain/v2/codec.go
  blockchain/v2/io.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  config/toml.go
  consensus/reactor.go
  crypto/encoding/codec_fuzz_test.go
  docs/tendermint-core/configuration.md
  evidence/store_test.go
  go.mod
  go.sum
  proto/blockchain/msgs.pb.go
  proto/blockchain/msgs.proto
  types/block.go
  types/block_test.go
  types/header.go
Labels: C:sync, T:encoding

#4718 proto: bring over proto types & msgs
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  proto/evidence/msgs.pb.go
  proto/evidence/msgs.proto
  proto/libs/bits/types.pb.go
  proto/libs/bits/types.proto
  proto/state/types.pb.go
  proto/state/types.proto
  proto/types/block.pb.go
  proto/types/block.proto
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  proto/types/params.pb.go
  proto/types/params.proto
  proto/types/types.pb.go
  proto/types/types.proto
  proto/types/validator.pb.go
  proto/types/validator.proto
  proto/version/version.pb.go
  proto/version/version.proto
Labels: R:minor, T:encoding

#4726 evidence: remove unused param
  consensus/reactor_test.go
  evidence/pool_test.go
  evidence/reactor_test.go
  evidence/store_test.go
  state/execution_test.go
  state/validation_test.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
Labels: C:evidence

#4710 consensus: define msgs in proto
  abci/types/types.pb.go
  abci/types/types.proto
  proto/blockchain/msgs.pb.go
  proto/blockchain/msgs.proto
  proto/consensus/msgs.pb.go
  proto/consensus/msgs.proto
  proto/consensus/walmsgs.pb.go
  proto/consensus/walmsgs.proto
  proto/crypto/merkle/types.pb.go
  proto/crypto/merkle/types.proto
  proto/state/types.pb.go
  proto/state/types.proto
  proto/types/events.pb.go
  proto/types/events.proto
  proto/types/types.pb.go
  proto/types/types.proto
Labels: T:encoding

#4730 proto: regenerate proto
  proto/crypto/keys/types.pb.go
  proto/evidence/msgs.pb.go
  proto/libs/bits/types.pb.go
  proto/state/types.pb.go
  proto/types/block.pb.go
  proto/types/evidence.pb.go
  proto/types/params.pb.go
  proto/types/types.pb.go
  proto/types/validator.pb.go
  proto/version/version.pb.go
Labels: R:minor, T:encoding

#4638 types: implement Header#ValidateBasic
  CHANGELOG_PENDING.md
  lite/base_verifier_test.go
  lite/dynamic_verifier_test.go
  lite2/client_test.go
  lite2/helpers_test.go
  lite2/verifier_test.go
  types/block.go
  types/evidence.go
  types/evidence_test.go
Labels: R:minor, T:security

#4737 privval: define proto msgs
  proto/privval/msgs.pb.go
  proto/privval/msgs.proto
  proto/privval/types.pb.go
  proto/privval/types.proto
Labels: T:encoding, T:validator

#4741 lite: fix HTTP provider error handling
  CHANGELOG_PENDING.md
  lite2/provider/http/http.go
  lite2/provider/http/http_test.go
Labels: C:light, R:minor, S:automerge, T:bug

#4722 evidence: consolidate store into pool
  CHANGELOG_PENDING.md
  evidence/errors.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/store.go
  evidence/store_test.go
  rpc/core/evidence.go
Labels: C:evidence, T:breaking

#4721 crypto: remove SimpleHashFromMap() and SimpleProofsFromMap()
  CHANGELOG_PENDING.md
  crypto/merkle/simple_map.go
  crypto/merkle/simple_map_test.go
  crypto/merkle/simple_proof.go
  crypto/merkle/simple_tree.go
Labels: R:minor, S:automerge, T:code-hygiene

#4725 evidence: remove pubkey from duplicate vote evidence
  CHANGELOG_PENDING.md
  evidence/reactor_test.go
  rpc/client/evidence_test.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf_test.go
  types/vote.go
Labels: C:evidence, R:major, S:automerge, T:breaking

#4723 evidence: add doc.go
  evidence/doc.go
Labels: C:evidence

#4744 privval: remove deprecated `OldFilePV`
  CHANGELOG_PENDING.md
  config/config.go
  node/node.go
  privval/file.go
  privval/file_deprecated.go
  privval/file_deprecated_test.go
  scripts/privValUpgrade.go
  scripts/privValUpgrade_test.go
Labels: R:minor, S:automerge, T:validator

#4748 p2p: set RecvMessageCapacity to maxMsgSize in all reactors
  blockchain/v0/reactor.go
  blockchain/v1/reactor.go
  blockchain/v2/reactor.go
  consensus/reactor.go
  evidence/reactor.go
  mempool/reactor.go
  p2p/pex/pex_reactor.go
Labels: R:minor, S:automerge

#4733 consensus: proto msgs
  CHANGELOG_PENDING.md
  blockchain/codec_test.go
  consensus/byzantine_test.go
  consensus/codec.go
  consensus/codec_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/wal.go
  consensus/wal_test.go
  crypto/merkle/simple_proof.go
  crypto/merkle/simple_proof_test.go
  crypto/merkle/simple_tree.go
  crypto/merkle/simple_tree_test.go
  go.mod
  go.sum
  libs/encode/json.go
  libs/math/safemath.go
  proto/consensus/msgs.pb.go
  proto/consensus/msgs.proto
  proto/consensus/walmsgs.pb.go
  proto/consensus/walmsgs.proto
  scripts/json2wal/main.go
  scripts/wal2json/main.go
  types/block.go
  types/block_test.go
  types/header.go
  types/part_set.go
  types/part_set_test.go
  types/proposal.go
  types/proposal_test.go
  types/tx_test.go
  types/vote.go
Labels: C:consensus, T:breaking, T:encoding

#4751 evidence: protect valToLastHeight w/ mtx
  evidence/pool.go
Labels: R:minor, S:automerge

#4734 docs: state we don't support non constant time crypto
  docs/tendermint-core/running-in-production.md
Labels: C:docs, S:automerge

#4760 lite: remove pkg
  CHANGELOG_PENDING.md
  docs/app-dev/app-development.md
  docs/guides/java.md
  docs/guides/kotlin.md
  lite/base_verifier.go
  lite/base_verifier_test.go
  lite/client/provider.go
  lite/client/provider_test.go
  lite/commit.go
  lite/dbprovider.go
  lite/doc.go
  lite/dynamic_verifier.go
  lite/dynamic_verifier_test.go
  lite/errors/errors.go
  lite/helpers.go
  lite/multiprovider.go
  lite/provider.go
  lite/provider_test.go
  lite/proxy/block.go
  lite/proxy/errors.go
  lite/proxy/proof.go
  lite/proxy/proxy.go
  lite/proxy/query.go
  lite/proxy/query_test.go
  lite/proxy/validate_test.go
  lite/proxy/verifier.go
  lite/proxy/wrapper.go
  lite/types.go
  lite2/rpc/query_test.go
Labels: C:light, T:breaking

#4704 add ABCI interface for state sync snapshots
  CHANGELOG_PENDING.md
  abci/client/client.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/socket_client.go
  abci/example/kvstore/persistent_kvstore.go
  abci/server/socket_server.go
  abci/types/application.go
  abci/types/messages.go
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/typespb_test.go
  proxy/app_conn.go
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  proxy/multi_app_conn.go
  version/version.go
Labels: C:abci, C:sync, R:major, S:automerge, T:breaking, T:feature

#4705 add state sync reactor
  CHANGELOG_PENDING.md
  blockchain/v0/reactor.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_test.go
  blockchain/v2/io.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  config/config.go
  config/config_test.go
  config/toml.go
  consensus/byzantine_test.go
  consensus/metrics.go
  consensus/reactor.go
  consensus/reactor_test.go
  node/node.go
  p2p/mocks/peer.go
  p2p/peer.go
  rpc/core/status.go
  state/store.go
  statesync/chunks.go
  statesync/chunks_test.go
  statesync/messages.go
  statesync/messages_test.go
  statesync/mocks/state_provider.go
  statesync/reactor.go
  statesync/reactor_test.go
  statesync/snapshots.go
  statesync/snapshots_test.go
  statesync/stateprovider.go
  statesync/syncer.go
  statesync/syncer_test.go
  store/store.go
Labels: C:p2p, C:sync, R:major, S:automerge, T:feature

#4761 blockchain/v2: fix excessive CPU usage due to spinning on closed channels
  CHANGELOG_PENDING.md
  blockchain/v2/reactor.go
  blockchain/v2/routine.go
Labels: R:minor, S:automerge, T:bug

#4758 build(deps): manually bump github.com/prometheus/client_golang from 1.5.1 to 1.6.0
  go.mod
  go.sum
Labels: S:automerge, T:dependencies

#4768 adr-053: update after state sync merge
  docs/architecture/adr-053-state-sync-prototype.md
Labels: S:automerge

#4772 blockchain/v2: respect fast_sync option
  CHANGELOG_PENDING.md
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
Labels: S:automerge

#4743 evidence: check evidence is pending before validating evidence
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/common_test.go
  consensus/reactor_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_test.go
  consensus/wal_generator.go
  evidence/mock/pool_mock.go
  state/execution_test.go
  state/helpers_test.go
  state/services.go
  state/validation.go
  state/validation_test.go
Labels: C:evidence

#4770 ci: check git diff on each job
  .circleci/config.yml
  .github/workflows/tests.yml
Labels: S:automerge

#4774 mempool: move mock into mempool directory
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_test.go
  consensus/wal_generator.go
  evidence/pool.go
  evidence/reactor.go
  mempool/mock/mempool.go
  state/execution_test.go
  state/validation_test.go
Labels: C:mempool, T:code-hygiene

#4781 state: export InitStateVersion
  CHANGELOG_PENDING.md
  state/state.go
Labels: S:automerge

#4777 linting: remove unused variable
  config/config.go
Labels: S:automerge
