Repository tendermint/tendermint, pull requests merged in 2020-07, with the labels that each got.

#5043 docs: update .vuepress/config.js
  docs/.vuepress/config.js
  docs/.vuepress/public/logo.svg
  docs/.vuepress/styles/index.styl
  docs/DOCS_README.md
  docs/README.md
  docs/app-dev/indexing-transactions.md
  docs/guides/go-built-in.md
  docs/guides/go.md
  docs/guides/java.md
  docs/guides/kotlin.md
  docs/package-lock.json
  docs/package.json
  docs/tendermint-core/light-client-protocol.md
  docs/tendermint-core/running-in-production.md
  docs/tendermint-core/using-tendermint.md
  docs/tools/debugging.md
  scripts/gitian-keys/README.md
Labels: C:docs, S:automerge

#5070 bump go version
  README.md
  Vagrantfile
  docs/guides/go.md
  go.mod
  test/docker/Dockerfile
Labels: C:docs, S:automerge

#5071 README: update chat link with Discord instead of Riot
  README.md
Labels: C:docs, S:automerge

#5072 docs: add warning for chainid
  docs/tendermint-core/using-tendermint.md
Labels: C:docs, S:automerge

#5064 linter: (1/2) enable errcheck
  abci/example/example_test.go
  abci/example/kvstore/kvstore_test.go
  blockchain/v0/reactor_test.go
  config/toml_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_test.go
  crypto/internal/benchmarking/bench.go
  crypto/tmhash/hash_test.go
  libs/events/event_cache_test.go
  libs/events/events_test.go
  libs/log/tm_logger.go
  libs/log/tmfmt_logger.go
  libs/pubsub/pubsub_test.go
  libs/service/service_test.go
  node/node_test.go
  p2p/conn/connection.go
  p2p/conn/connection_test.go
  p2p/fuzz.go
  p2p/peer.go
  p2p/pex/file.go
  p2p/pex/pex_reactor_test.go
  p2p/upnp/upnp.go
  rpc/client/mock/abci.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/http_uri_client.go
  rpc/jsonrpc/client/ws_client_test.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/test/main.go
  scripts/wal2json/main.go
  state/execution_test.go
  state/txindex/kv/kv_test.go
  state/validation_test.go
  store/store_test.go
  tools/tm-signer-harness/internal/test_harness_test.go
Labels: S:automerge, T:code-hygiene

#5066 mempool: add RemoveTxByKey function
  CHANGELOG_PENDING.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
Labels: C:mempool, S:automerge

#5073 blockchain: test vectors for proto encoding
  blockchain/msgs_test.go
Labels: C:sync, S:automerge, T:encoding

#5075 changelog: update 0.33.6
  CHANGELOG.md
  CHANGELOG_PENDING.md
  version/version.go
Labels: S:automerge

#5077 changelog: note breaking change in the 0.33.6 release
  CHANGELOG.md
Labels: S:automerge

#5076 consensus: msg testvectors
  consensus/msgs_test.go
Labels: C:consensus, S:automerge, T:encoding

#5079 remove stalebot
  .github/stale.yml
  .github/workflows/stale.yml
Labels: S:automerge

#5081 abci/types: add comment for TotalVotingPower
  abci/types/types.pb.go
  proto/tendermint/abci/types/types.proto
  proto/tendermint/consensus/walmsgs.pb.go
  proto/tendermint/crypto/keys/types.pb.go
Labels: C:docs, S:automerge

#5080 adjust stale action settings
  .github/workflows/stale.yml
Labels: S:automerge

#5065 changelog: reorgranize
  CHANGELOG_PENDING.md
  CONTRIBUTING.md
  UPGRADING.md
  version/version.go
Labels: S:automerge

#5060 .github/issue_template: Update `/dump_consensus_state` request.
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: S:automerge

#4857 ADR-057: RPC
  docs/architecture/README.md
  docs/architecture/adr-057-RPC.md
Labels: S:automerge

#5088 Update reactor.go
  blockchain/v0/reactor.go
Labels: C:sync, S:automerge

#5095 ci: try to fix codecov
  .github/workflows/coverage.yml
Labels: S:automerge

#5078 proxy: improve ABCI app connection handling
  CHANGELOG_PENDING.md
  abci/client/mocks/client.go
  consensus/state.go
  proxy/client.go
  proxy/mocks/client_creator.go
  proxy/multi_app_conn.go
  proxy/multi_app_conn_test.go
Labels: R:minor, S:automerge

#5097 ci: only run tests when go files are touched
  .github/workflows/coverage.yml
Labels: S:automerge

#5100 evidence: fix data race in Pool.updateValToLastHeight()
  evidence/pool.go
Labels: C:evidence, S:automerge, T:bug

#5096 proto: increase lint level to basic and fix lint warnings
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  buf.yaml
  proto/tendermint/abci/types/types.proto
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
Labels: S:automerge, T:breaking, T:encoding

#5101 test: deflake TestAddAndRemoveListenerConcurrency and TestSyncer_SyncAny
  libs/events/events_test.go
  statesync/syncer_test.go
Labels: S:automerge, T:test

#5099 proto: improve enums
  abci/types/types.pb.go
  proto/tendermint/abci/types/types.proto
  proto/tendermint/consensus/msgs.pb.go
  proto/tendermint/types/canonical.pb.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  statesync/syncer.go
  statesync/syncer_test.go
  types/vote_test.go
Labels: S:automerge, T:encoding

#5102 proto: reorganize Protobuf schemas
  abci/cmd/abci-cli/abci-cli.go
  abci/example/kvstore/persistent_kvstore.go
  abci/types/types.pb.go
  crypto/encoding/codec.go
  crypto/merkle/proof.go
  crypto/merkle/proof_op.go
  crypto/merkle/proof_test.go
  crypto/merkle/proof_value.go
  proto/tendermint/abci/types.proto
  proto/tendermint/blockchain/types.pb.go
  proto/tendermint/blockchain/types.proto
  proto/tendermint/consensus/types.pb.go
  proto/tendermint/consensus/types.proto
  proto/tendermint/consensus/wal.pb.go
  proto/tendermint/consensus/wal.proto
  proto/tendermint/crypto/keys.pb.go
  proto/tendermint/crypto/keys.proto
  proto/tendermint/crypto/proof.pb.go
  proto/tendermint/crypto/proof.proto
  proto/tendermint/evidence/types.pb.go
  proto/tendermint/evidence/types.proto
  proto/tendermint/mempool/types.pb.go
  proto/tendermint/mempool/types.proto
  proto/tendermint/p2p/conn.pb.go
  proto/tendermint/p2p/conn.proto
  proto/tendermint/p2p/pex.pb.go
  proto/tendermint/p2p/pex.proto
  proto/tendermint/privval/msgs.pb.go
  proto/tendermint/privval/msgs.proto
  proto/tendermint/privval/types.pb.go
  proto/tendermint/privval/types.proto
  proto/tendermint/rpc/grpc/types.proto
  proto/tendermint/state/types.pb.go
  proto/tendermint/state/types.proto
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  proto/tendermint/types/validator.pb.go
  proto/tendermint/types/validator.proto
  proto/tendermint/version/types.pb.go
  proto/tendermint/version/types.proto
  rpc/grpc/types.pb.go
  scripts/protocgen.sh
Labels: S:automerge, T:encoding

#5093 evidence: check lunatic vote matches header
  state/validation_test.go
  types/evidence.go
  types/evidence_test.go
Labels: C:evidence

#5105 proto: minor cleanups
  proto/tendermint/consensus/types.pb.go
  proto/tendermint/consensus/types.proto
  proto/tendermint/consensus/wal.pb.go
  proto/tendermint/consensus/wal.proto
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/p2p/types.proto
Labels: S:automerge

#5104 light: fix rpc calls: /block_results & /validators
  light/rpc/client.go
Labels: C:light, C:rpc

#5109 rpc: /broadcast_evidence nil evidence check
  rpc/client/evidence_test.go
  rpc/core/evidence.go
Labels: C:rpc

#5108 evidence: new evidence event subscription
  CHANGELOG_PENDING.md
  state/execution.go
  types/event_bus.go
  types/event_bus_test.go
  types/events.go
  types/events_test.go
Labels: C:evidence, C:rpc

#5107 proto: change type + a cleanup
  blockchain/msgs.go
  blockchain/msgs_test.go
  blockchain/v0/reactor.go
  blockchain/v1/reactor.go
  blockchain/v2/io.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  p2p/conn/connection.go
  p2p/conn/connection_test.go
  proto/tendermint/blockchain/types.pb.go
  proto/tendermint/blockchain/types.proto
  proto/tendermint/p2p/conn.pb.go
  proto/tendermint/p2p/conn.proto
Labels: S:automerge

#5116 proto/tendermint/abci: fix Request oneof numbers
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
Labels: R:major, S:automerge, T:breaking

#5091 lint: errcheck
  CHANGELOG_PENDING.md
  abci/client/socket_client.go
  abci/client/socket_client_test.go
  abci/cmd/abci-cli/abci-cli.go
  abci/example/example_test.go
  abci/example/kvstore/kvstore_test.go
  blockchain/v0/pool_test.go
  blockchain/v2/reactor_test.go
  consensus/replay_test.go
  libs/autofile/autofile_test.go
  libs/autofile/cmd/logjack.go
  libs/autofile/group_test.go
  libs/events/events_test.go
  libs/pubsub/example_test.go
  libs/pubsub/pubsub_test.go
  light/store/db/db_test.go
  node/node.go
  p2p/conn/connection_test.go
  p2p/conn/secret_connection_test.go
  p2p/peer.go
  p2p/pex/addrbook_test.go
  p2p/switch_test.go
  p2p/trust/metric_test.go
  p2p/trust/store_test.go
  privval/signer_client_test.go
  proxy/app_conn_test.go
  rpc/core/net_test.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/test/helpers.go
  state/txindex/kv/kv_test.go
  statesync/reactor_test.go
  statesync/syncer_test.go
Labels: S:automerge, T:code-hygiene

#5121 docs: tweak light client documentation
  docs/tendermint-core/light-client-protocol.md
Labels: S:automerge

#5123 docs: modify needed proto files for guides
  docs/guides/java.md
  docs/guides/kotlin.md
Labels: C:docs, S:automerge

#5119 light: use bisection (not VerifyCommitTrusting) when verifying a head…
  light/client.go
  light/client_test.go
  light/errors.go
Labels: R:minor

#5127 ci: bump linter version
  .github/workflows/lint.yaml
Labels: S:automerge

#5128 ci: version linter fix
  .github/workflows/lint.yaml
  blockchain/msgs_test.go
  consensus/replay.go
  evidence/reactor.go
  p2p/pex/addrbook.go
  state/validation_test.go
  types/block_meta_test.go
  types/evidence_test.go
Labels: S:automerge

#5131 jsonrpc: change log to debug
  rpc/jsonrpc/server/http_uri_handler.go
Labels: S:automerge, T:ux

#5124 light: return if target header is invalid
  light/client.go
  light/client_test.go
  light/errors.go
Labels: R:minor, S:automerge

#5132 docs: EventAttribute#Index is not deterministic
  abci/types/types.pb.go
  docs/app-dev/indexing-transactions.md
  proto/tendermint/abci/types.proto
Labels: C:docs, S:automerge

#5137 rpc: make gasWanted/Used snake_case
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
  rpc/swagger/swagger.yaml
Labels: C:rpc, S:automerge

#5141 rpc/jsonrpc/server: merge WriteRPCResponseHTTP and WriteRPCResponseAr
  CHANGELOG_PENDING.md
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_json_handler_test.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/http_uri_handler.go
Labels: S:automerge

#5140 privval: if remote signer errors, don't retry
  privval/errors.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
Labels: R:minor

#5152 types: validatebasic on from proto
  types/validator_set.go
Labels: S:automerge

#5154 ADR: add missing numbers as blank templates
  docs/architecture/README.md
  docs/architecture/adr-028-libp2p.md
  docs/architecture/adr-031-changelog.md
  docs/architecture/adr-036-empty-blocks-abci.md
  docs/architecture/adr-038-non-zero-start-height.md
Labels: S:automerge

#5156 docs: simplify choosing an ADR number
  CONTRIBUTING.md
Labels: S:automerge

#5158 Docs update
  docs/.vuepress/config.js
  docs/package-lock.json
Labels: C:docs, S:automerge

#5148 light cli: add feature flags and save providers
  cmd/tendermint/commands/lite.go
  libs/math/fraction.go
  libs/math/fraction_test.go
Labels: C:light

#5144 proto: add a comment for Validator#Address
  proto/tendermint/abci/types.proto
  types/validator.go
Labels: S:automerge

#5150 consensus: added byzantine test, modified previous one
  consensus/byzantine_test.go
Labels: C:consensus

#5164 docs: add more details on Vote struct from /consensus_state
  rpc/swagger/swagger.yaml
  types/block.go
  types/part_set.go
  types/proposal.go
  types/validator.go
  types/validator_set.go
  types/vote.go
  types/vote_set.go
Labels: C:docs, S:automerge

#5165 docs: document ConsensusParams
  docs/tendermint-core/using-tendermint.md
  proto/tendermint/types/params.pb.go
  proto/tendermint/types/params.proto
Labels: C:docs, S:automerge

#5166 docs: document canonical field
  rpc/swagger/swagger.yaml
Labels: C:docs, S:automerge

#5159 state: revert event hashing
  CHANGELOG_PENDING.md
  Vagrantfile
  state/store.go
  state/store_test.go
  types/results.go
Labels: S:automerge

#5143 consensus: only call privValidator.GetPubKey once per block
  CHANGELOG_PENDING.md
  consensus/state.go
Labels: S:automerge

#5173 version: bump version numbers
  version/version.go
Labels: S:automerge

#5172 changelog: move entries from pending
  CHANGELOG.md
  CHANGELOG_PENDING.md
Labels: S:automerge

#5176 changelog: bump to 0.34.0-rc2
  CHANGELOG.md
Labels: S:automerge

#5182 rpc/client/http: log error
  rpc/client/http/http.go
Labels: S:automerge

#5181 evidence: remove phantom validator evidence
  CHANGELOG_PENDING.md
  docs/architecture/adr-047-handling-evidence-from-light-client.md
  evidence/pool.go
  evidence/pool_test.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  state/validation.go
  state/validation_test.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf.go
Labels: C:evidence
