Repository tendermint/tendermint, pull requests merged in 2020-09, with the labels that each got.

#5293 rpc: add private & unconditional to /dial_peer
  CHANGELOG_PENDING.md
  p2p/switch.go
  p2p/switch_test.go
  p2p/test_util.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  rpc/core/env.go
  rpc/core/net.go
  rpc/core/net_test.go
  rpc/core/routes.go
  rpc/openapi/openapi.yaml
Labels: C:rpc, S:automerge

#5298 light: implement light block
  CHANGELOG_PENDING.md
  light/client.go
  light/client_benchmark_test.go
  light/client_test.go
  light/errors.go
  light/example_test.go
  light/provider/errors.go
  light/provider/http/http.go
  light/provider/http/http_test.go
  light/provider/mock/deadmock.go
  light/provider/mock/mock.go
  light/provider/provider.go
  light/rpc/client.go
  light/store/db/db.go
  light/store/db/db_test.go
  light/store/errors.go
  light/store/store.go
  light/verifier.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  statesync/stateprovider.go
  types/block.go
  types/block_test.go
  types/light.go
  types/light_test.go
Labels: C:light

#5317 evidence: remove ConflictingHeaders type
  CHANGELOG_PENDING.md
  evidence/doc.go
  evidence/pool.go
  light/client.go
  light/client_test.go
  light/errors.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  rpc/client/evidence_test.go
  types/block.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
Labels: C:evidence, S:automerge

#5318 evidence: remove lunatic
  CHANGELOG_PENDING.md
  evidence/pool.go
  evidence/reactor_test.go
  evidence/verify.go
  evidence/verify_test.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  types/evidence.go
  types/evidence_test.go
  types/protobuf.go
Labels: C:evidence, S:automerge

#5320 statesync: broadcast snapshot request to all peers on startup
  CHANGELOG_PENDING.md
  statesync/reactor.go
Labels: C:sync, S:automerge

#5319 evidence: remove amnesia & POLC
  CHANGELOG_PENDING.md
  consensus/common_test.go
  consensus/reactor_test.go
  consensus/replay_stubs.go
  consensus/state.go
  consensus/state_test.go
  docs/tendermint-core/using-tendermint.md
  evidence/doc.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/verify.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  proto/tendermint/types/params.pb.go
  proto/tendermint/types/params.proto
  tools/tm-signer-harness/internal/test_harness_test.go
  types/block.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
  types/params.go
  types/params_test.go
  types/protobuf.go
  types/vote_set_test.go
Labels: C:evidence, S:automerge

#5323 docs: move subscription to tendermint-core
  docs/app-dev/indexing-transactions.md
  docs/imgs/a_plus_t.png
  docs/tendermint-core/README.md
  docs/tendermint-core/block-structure.md
  docs/tendermint-core/fast-sync.md
  docs/tendermint-core/light-client.md
  docs/tendermint-core/mempool.md
  docs/tendermint-core/rpc.md
  docs/tendermint-core/state-sync.md
  docs/tendermint-core/subscription.md
Labels: C:docs, S:automerge

#5324 abci: update evidence
  CHANGELOG_PENDING.md
  UPGRADING.md
  abci/example/kvstore/persistent_kvstore.go
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
  types/protobuf.go
  types/protobuf_test.go
Labels: C:abci, C:evidence

#5325 docs: add missing metrics
  consensus/metrics.go
  docs/tendermint-core/metrics.md
Labels: C:docs, S:automerge

#5329 consensus: fix wrong proposer schedule for `InitChain` validators
  CHANGELOG_PENDING.md
  consensus/replay.go
Labels: S:automerge

#5326 metrics: switch from gauge to histogram
  consensus/metrics.go
  consensus/state.go
Labels: S:automerge, T:ux

#5316 lint: add errchecks
  abci/client/grpc_client.go
  abci/client/socket_client.go
  abci/tests/test_app/main.go
  behaviour/reporter_test.go
  cmd/tendermint/commands/debug/io.go
  cmd/tendermint/commands/reset_priv_validator.go
  cmd/tendermint/commands/run_node.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/invalid_test.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/wal.go
  consensus/wal_generator.go
  consensus/wal_test.go
  crypto/hash.go
  crypto/merkle/proof_value.go
  crypto/xchacha20poly1305/xchachapoly_test.go
  mempool/bench_test.go
  mempool/cache_test.go
  mempool/clist_mempool_test.go
  mempool/reactor_test.go
  node/node.go
  p2p/peer_test.go
  p2p/switch.go
  p2p/switch_test.go
  p2p/trust/store.go
  privval/signer_listener_endpoint_test.go
  proxy/multi_app_conn.go
  proxy/multi_app_conn_test.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/server/ws_handler.go
  state/txindex/indexer_service_test.go
  types/block.go
  types/block_test.go
  types/event_bus.go
  types/event_bus_test.go
  types/genesis_test.go
  types/params.go
  types/vote_set_test.go
Labels: S:automerge, T:code-hygiene

#5336 lint: enable errcheck
  .golangci.yml
  abci/server/grpc_server.go
  abci/tests/test_app/main.go
  blockchain/v0/pool.go
  blockchain/v0/reactor.go
  blockchain/v2/reactor.go
  blockchain/v2/scheduler.go
  cmd/tendermint/commands/testnet.go
  consensus/reactor.go
  consensus/replay_file.go
  consensus/replay_test.go
  consensus/state.go
  evidence/reactor.go
  libs/autofile/autofile.go
  libs/autofile/autofile_test.go
  libs/autofile/cmd/logjack.go
  libs/autofile/group.go
  libs/cli/helper.go
  libs/log/tmfmt_logger_test.go
  libs/tempfile/tempfile_test.go
  light/example_test.go
  light/rpc/client.go
  node/node.go
  p2p/conn/connection.go
  p2p/mock/peer.go
  p2p/peer_set_test.go
  p2p/pex/addrbook.go
  p2p/pex/pex_reactor.go
  p2p/test_util.go
  rpc/client/event_test.go
  rpc/client/helpers.go
  rpc/client/local/local.go
  rpc/core/mempool.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/ws_handler.go
  state/execution.go
  statesync/snapshots.go
  tools/tm-signer-harness/main.go
Labels: S:automerge, T:code-hygiene

#5343 ci: fix net run
  .github/workflows/net.yml
Labels: S:automerge

#5340 header: check block protocol
  CHANGELOG_PENDING.md
  blockchain/msgs_test.go
  light/helpers_test.go
  light/store/db/db_test.go
  store/store_test.go
  types/block.go
  types/block_test.go
  types/light_test.go
  types/test_util.go
Labels: S:automerge

#5338 p2p: reduce log severity
  p2p/conn/connection.go
  p2p/peer.go
Labels: C:p2p, S:automerge, T:observability

#5337 rfc: add end-to-end testing RFC
  docs/rfc/rfc-001-end-to-end-testing.md
Labels: C:docs, S:automerge, S:proposal, T:test

#5349 crypto: reword readme
  crypto/README.md
Labels: C:docs, S:automerge

#5350 docs: add more description to initial_height
  docs/tendermint-core/using-tendermint.md
Labels: C:docs, S:automerge

#5351 markdownlint: ignore .github directory
  .markdownlintignore
Labels: S:automerge

#5353 docs: make rfc section disppear
  docs/rfc/README.md
Labels: C:docs, S:automerge

#5348 state: define interface for state store
  CHANGELOG_PENDING.md
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/mempool_test.go
  consensus/reactor_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_test.go
  consensus/state.go
  consensus/wal_generator.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor_test.go
  evidence/services.go
  evidence/verify.go
  evidence/verify_test.go
  node/node.go
  node/node_test.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/consensus.go
  rpc/core/env.go
  rpc/core/status.go
  state/execution.go
  state/execution_test.go
  state/export_test.go
  state/helpers_test.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/tx_filter_test.go
  state/validation.go
  state/validation_test.go
  store/store_test.go
Labels: C:state, S:automerge

#5356 docs: document max entries for `/blockchain` RPC
  rpc/openapi/openapi.yaml
Labels: C:docs, S:automerge

#5357 makefile: add options for other DBs
  Makefile
Labels: S:automerge

#5358 rpc: fix openapi spec syntax error
  rpc/openapi/openapi.yaml
Labels: S:automerge

#5354 abci: application evidence prepared by evidence pool
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/reactor_test.go
  consensus/replay.go
  consensus/replay_file.go
  consensus/replay_stubs.go
  consensus/replay_test.go
  consensus/wal_generator.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/verify.go
  evidence/verify_test.go
  light/detector.go
  light/detector_test.go
  p2p/mocks/peer.go
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  rpc/client/evidence_test.go
  state/execution.go
  state/execution_test.go
  state/mocks/evidence_pool.go
  state/services.go
  state/validation_test.go
  statesync/mocks/state_provider.go
  types/evidence.go
  types/evidence_test.go
Labels: C:abci

#5363 rpc: fix test data races
  rpc/jsonrpc/server/http_server_test.go
Labels: S:automerge, T:test

#5364 upgrading: state store change
  UPGRADING.md
Labels: C:docs, S:automerge

#5341 adr: add API stability ADR
  docs/architecture/adr-060-go-api-stability.md
Labels: C:docs, S:automerge

#5273 ADR 047 - Light client evidence handling revision
  docs/architecture/adr-047-handling-evidence-from-light-client.md
  docs/imgs/bifurcation-point.png
  docs/imgs/light-client-detector.png
Labels: C:docs

#5362 mempool/reactor: fix reactor broadcast test
  mempool/reactor_test.go
Labels: C:mempool, S:automerge

#5384 ux: use docker to format proto files
  .clang-format
  .vscode/settings.json
  Makefile
  proto/tendermint/abci/types.proto
  proto/tendermint/evidence/types.proto
  proto/tendermint/types/evidence.proto
  proto/tendermint/types/types.proto
Labels: S:automerge, T:ux

#5347 rpc/client: take context as first param
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/debug/util.go
  cmd/tendermint/commands/lite.go
  light/client.go
  light/client_benchmark_test.go
  light/client_test.go
  light/detector.go
  light/detector_test.go
  light/example_test.go
  light/provider/http/http.go
  light/provider/http/http_test.go
  light/provider/mock/deadmock.go
  light/provider/mock/mock.go
  light/provider/provider.go
  light/proxy/routes.go
  light/rpc/client.go
  light/setup.go
  node/node.go
  rpc/client/event_test.go
  rpc/client/evidence_test.go
  rpc/client/examples_test.go
  rpc/client/helpers.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mock/abci.go
  rpc/client/mock/abci_test.go
  rpc/client/mock/client.go
  rpc/client/mock/status.go
  rpc/client/mock/status_test.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/http_uri_client.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/test/helpers.go
  statesync/mocks/state_provider.go
  statesync/snapshots.go
  statesync/snapshots_test.go
  statesync/stateprovider.go
  statesync/syncer.go
  statesync/syncer_test.go
Labels: T:breaking

#5321 mempool: batch txs per peer in broadcastTxRoutine
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  docs/tendermint-core/configuration.md
  go.sum
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/reactor.go
  mempool/reactor_test.go
  proto/tendermint/mempool/types.pb.go
  proto/tendermint/mempool/types.proto
Labels: T:breaking

#5389 changelog: minor tweaks
  CHANGELOG_PENDING.md
Labels: S:automerge

#5395 abci: fix socket client error for state sync responses
  CHANGELOG_PENDING.md
  abci/client/socket_client.go
Labels: S:automerge

#5405 docs: update state sync config with discovery_time
  docs/tendermint-core/configuration.md
Labels: C:docs, S:automerge

#5401 blockchain/v1: add noBlockResponse handling
  blockchain/v1/reactor.go
  blockchain/v1/reactor_fsm.go
  blockchain/v1/reactor_fsm_test.go
Labels: C:sync, S:automerge

#5397 docs: add explanation of p2p configuration options
  docs/tendermint-core/configuration.md
Labels: C:docs, S:automerge

#5415 state: more test cases for block validation
  rpc/client/http/http.go
  state/validation.go
  state/validation_test.go
  types/block.go
  types/block_test.go
Labels: S:automerge

#5417 rpc/core: more docs and a test for /blockchain endpoint
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/openapi/openapi.yaml
Labels: S:automerge

#5427 docs: specify TM version in go tutorials
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: C:docs, S:automerge

#5434 privval: allow passing options to NewSignerDialerEndpoint
  CHANGELOG_PENDING.md
  privval/signer_dialer_endpoint.go
Labels: S:automerge
