Repository tendermint/tendermint, pull requests merged in 2020-03, with the labels that each got.

#4509 example/kvstore: return ABCI query height
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/kvstore_test.go
  abci/tests/test_cli/ex1.abci.out
  docs/app-dev/abci-cli.md
Labels: S:automerge

#4505 lite2: fix tendermint lite sub command
  cmd/tendermint/commands/lite.go
  docs/tendermint-core/light-client-protocol.md
  lite2/client.go
  lite2/client_test.go
Labels: C:light, S:automerge, T:ux

#4511 docs: `tendermint node --help` dumps all supported flags
  docs/tendermint-core/using-tendermint.md
Labels: C:docs, S:automerge

#4510 rpc: remove BlockStoreRPC in favor of BlockStore
  state/services.go
Labels: S:automerge

#4512 cmd: show useful error when tm not initialised
  cmd/tendermint/commands/run_node.go
Labels: S:automerge, T:ux

#4516 docs: write about debug kill and dump
  docs/tendermint-core/running-in-production.md
  docs/tools/README.md
  docs/tools/debugging.md
Labels: C:docs, S:automerge

#4486 lite: add helper functions for initiating the light client
  cmd/tendermint/commands/lite.go
  lite2/client.go
  lite2/example_test.go
  lite2/setup.go
Labels: C:light, S:automerge

#4517 cmd: fix debug kill and change debug dump archive filename format
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/debug/dump.go
  cmd/tendermint/commands/debug/kill.go
Labels: S:automerge

#4429 adr-047: evidence handling
  docs/architecture/README.md
  docs/architecture/adr-047-handling-evidence-from-light-client.md
Labels: C:docs, C:light

#4506 fix: proto-breakage
  .circleci/config.yml
  Makefile
  abci/types/types.pb.go
  buf.yaml
  libs/kv/types.pb.go
  scripts/protocgen.sh
  tools.mk
Labels: S:automerge, T:code-hygiene

#4526 p2p/pex: fix addrbook tests
  p2p/pex/addrbook_test.go
Labels: S:automerge, T:code-hygiene, T:test

#4531 docs: fix links
  docs/DOCS_README.md
  docs/README.md
  docs/app-dev/abci-cli.md
  docs/app-dev/app-development.md
  docs/app-dev/indexing-transactions.md
  docs/app-dev/subscribing-to-events-via-websocket.md
  docs/architecture/README.md
  docs/architecture/adr-002-event-subscription.md
  docs/architecture/adr-011-monitoring.md
  docs/architecture/adr-018-ABCI-Validators.md
  docs/architecture/adr-043-blockchain-riri-org.md
  docs/tendermint-core/how-to-read-logs.md
  docs/tendermint-core/running-in-production.md
  docs/tendermint-core/using-tendermint.md
Labels: C:docs, S:automerge

#4533 readme: add discord to readme
  README.md
Labels: C:docs, S:automerge

#4535 lite2: remove auto update
  cmd/tendermint/commands/lite.go
  docs/architecture/adr-046-light-client-implementation.md
  lite2/client.go
  lite2/client_test.go
  lite2/doc.go
  lite2/example_test.go
  lite2/rpc/client.go
Labels: C:light

#4536 lite2: indicate success/failure of Update
  docs/architecture/adr-042-state-sync.md
  docs/architecture/adr-046-light-client-implementation.md
  lite2/client.go
  lite2/client_test.go
  lite2/example_test.go
Labels: C:light

#4521 rpc: create buffered subscriptions on /subscribe
  CHANGELOG_PENDING.md
  rpc/core/README.md
  rpc/core/events.go
Labels: C:rpc, T:bug

#4523 lite2: replace primary when providing invalid header
  go.sum
  lite2/client.go
  lite2/errors.go
  lite2/verifier.go
  lite2/verifier_test.go
Labels: C:light

#4481 adr: crypto encoding for proto
  docs/architecture/README.md
  docs/architecture/adr-054-crypto-encoding-2.md
  docs/architecture/adr-template.md
  go.sum
Labels: C:crypto, S:automerge, T:breaking

#4543 CONTRIBUTING: include instructions for installing protobuf
  CONTRIBUTING.md
Labels: S:automerge

#4332 more linting and some types to proto
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  abci/types/types.proto
  buf.yaml
  consensus/byzantine_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/state.go
  crypto/merkle/merkle.pb.go
  libs/kv/types.pb.go
  mempool/clist_mempool.go
  rpc/grpc/types.pb.go
  scripts/protocgen.sh
  state/tx_filter_test.go
  store/store.go
  third_party/proto/gogoproto/gogo.proto
  tools.mk
  types/block.go
  types/block.pb.go
  types/block.proto
  types/block_meta.go
  types/block_test.go
  types/canonical.go
  types/evidence.go
  types/evidence_test.go
  types/part_set.go
  types/part_set_test.go
  types/proposal_test.go
  types/proto3/block.pb.go
  types/proto3/block.proto
  types/proto3_test.go
  types/result.go
  types/signed_msg_type.go
  types/types.pb.go
  types/types.proto
  types/vote.go
  types/vote_set_test.go
  types/vote_test.go
Labels: T:breaking, T:encoding

#4555 deps: bump deps that bot cant
  go.mod
  go.sum
Labels: T:dependencies

#4558 tools/build: delete stale tools
  tools/build/Makefile
  tools/build/tendermint.list
Labels: T:code-hygiene

#4514 lite: benchmarking tests
  lite2/client_benchmark_test.go
  lite2/test_helpers.go
  lite2/verifier.go
Labels: C:light, T:test

#4534 privval: return error on getpubkey
  CHANGELOG_PENDING.md
  blockchain/v1/reactor_test.go
  cmd/tendermint/commands/init.go
  cmd/tendermint/commands/show_validator.go
  cmd/tendermint/commands/testnet.go
  consensus/common_test.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set_test.go
  node/node.go
  privval/file.go
  privval/file_deprecated_test.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_requestHandler.go
  scripts/privValUpgrade_test.go
  state/state_test.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness.go
  types/block_test.go
  types/evidence_test.go
  types/priv_validator.go
  types/proposal_test.go
  types/protobuf_test.go
  types/test_util.go
  types/validator.go
  types/vote_set_test.go
  types/vote_test.go
Labels: T:enhancement, T:validator

#4548 p2p: ban bad peers
  p2p/pex/addrbook.go
  p2p/pex/addrbook_test.go
  p2p/pex/errors.go
  p2p/pex/known_address.go
  p2p/pex/pex_reactor.go
Labels: C:p2p

#4561 Use docs-staging branch for docs preview website
  .circleci/config.yml
Labels: C:docs, S:automerge

#4565 removal: remove build folder
  tools/build/.gitignore
  tools/build/RPM-GPG-KEY-Tendermint
  tools/build/Release
  tools/build/Release_amd64
  tools/build/_gpg
  tools/build/basecoind/DEBIAN/changelog
  tools/build/basecoind/DEBIAN/compat
  tools/build/basecoind/DEBIAN/control
  tools/build/basecoind/DEBIAN/copyright
  tools/build/basecoind/DEBIAN/postinst
  tools/build/basecoind/DEBIAN/postrm
  tools/build/basecoind/DEBIAN/preinst
  tools/build/basecoind/DEBIAN/prerm
  tools/build/basecoind/etc/systemd/system-preset/50-basecoind.preset
  tools/build/basecoind/etc/systemd/system/basecoind.service
  tools/build/basecoind/usr/share/basecoind/key.json
  tools/build/basecoind/usr/share/basecoind/key2.json
  tools/build/ethermint/DEBIAN/changelog
  tools/build/ethermint/DEBIAN/compat
  tools/build/ethermint/DEBIAN/control
  tools/build/ethermint/DEBIAN/copyright
  tools/build/ethermint/DEBIAN/postinst
  tools/build/ethermint/DEBIAN/postrm
  tools/build/ethermint/DEBIAN/preinst
  tools/build/ethermint/DEBIAN/prerm
  tools/build/ethermint/etc/systemd/system-preset/50-ethermint.preset
  tools/build/ethermint/etc/systemd/system/ethermint.service
  tools/build/gaia/DEBIAN/changelog
  tools/build/gaia/DEBIAN/compat
  tools/build/gaia/DEBIAN/control
  tools/build/gaia/DEBIAN/copyright
  tools/build/gaia/DEBIAN/postinst
  tools/build/gaia/DEBIAN/postrm
  tools/build/gaia/DEBIAN/preinst
  tools/build/gaia/DEBIAN/prerm
  tools/build/gaia/etc/systemd/system-preset/50-gaia.preset
  tools/build/gaia/etc/systemd/system/gaia.service
  tools/build/gaia/usr/share/gaia/key.json
  tools/build/gaia/usr/share/gaia/key2.json
  tools/build/generate-spec
  tools/build/sign
  tools/build/spectemplates/app-template.spec
  tools/build/spectemplates/basecoind.data
  tools/build/spectemplates/ethermint.data
  tools/build/spectemplates/ethermint.spec
  tools/build/spectemplates/gaia.data
  tools/build/spectemplates/tendermint.spec
  tools/build/tendermint.repo
  tools/build/tendermint/DEBIAN/changelog
  tools/build/tendermint/DEBIAN/compat
  tools/build/tendermint/DEBIAN/control
  tools/build/tendermint/DEBIAN/copyright
Labels: S:automerge, T:code-hygiene

#4564 Update docs website
  docs/.vuepress/styles/index.styl
  docs/package-lock.json
  docs/package.json
Labels: C:docs, S:automerge

#4566 fix: spelling of comment
  types/evidence.go
Labels: S:automerge, T:code-hygiene

#4577 DOCKER: update with defaults
  CHANGELOG_PENDING.md
  DOCKER/Dockerfile
Labels: S:automerge

#4587 deps: run go mod tidy
  go.sum
Labels: S:automerge, T:code-hygiene

#4589 Docker image port fix
  DOCKER/Dockerfile
Labels: S:automerge

#4598 docs: link fixing
  CHANGELOG.md
  README.md
  docs/tools/README.md
Labels: C:docs

#4597 blockchain: enable v2 to be set
  config/toml.go
  node/node.go
Labels: S:automerge

#4601 docs: link scheduler cron job
  .github/workflows/action.yml
Labels: C:docs, S:automerge

#4562 lite2: cache headers in bisection
  CHANGELOG_PENDING.md
  docs/imgs/light_client_bisection_alg.png
  lite2/client.go
  lite2/doc.go
Labels: C:light, T:perf

#4605 tools: remove need to install buf
  .circleci/config.yml
  .github/workflows/linkchecker.yml
  .github/workflows/proto.yml
  CONTRIBUTING.md
  Makefile
  tools.mk
Labels: T:ux

#4576 Update style guide and add it to contributors section
  CONTRIBUTING.md
  README.md
  STYLE_GUIDE.md
Labels: C:docs

#4604 docs: validator setup
  docs/tendermint-core/local_config.png
  docs/tendermint-core/sentry_layout.png
  docs/tendermint-core/validators.md
Labels: C:docs, S:automerge

#4582 stricter ints for round and valIndex
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set.go
  consensus/types/height_vote_set_test.go
  consensus/types/peer_round_state.go
  consensus/types/round_state.go
  libs/math/safemath.go
  privval/file.go
  privval/file_deprecated.go
  privval/file_deprecated_test.go
  privval/file_test.go
  rpc/client/rpc_test.go
  scripts/privValUpgrade_test.go
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state_test.go
  state/store.go
  state/tx_filter_test.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/block.go
  types/block_test.go
  types/events.go
  types/evidence.go
  types/evidence_test.go
  types/proposal.go
  types/test_util.go
  types/validator_set.go
  types/validator_set_test.go
  types/vote.go
  types/vote_set.go
  types/vote_set_test.go
  types/vote_test.go
Labels: T:code-hygiene

#4615 proto: use docker to generate stubs
  CHANGELOG_PENDING.md
  CONTRIBUTING.md
  Makefile
Labels: T:encoding, T:ux

#4575 lite2: use bisection for some of backward verification
  CHANGELOG_PENDING.md
  docs/architecture/adr-046-light-client-implementation.md
  lite2/client.go
  lite2/client_benchmark_test.go
  lite2/client_test.go
  lite2/errors.go
  lite2/store/db/db.go
  lite2/store/db/db_test.go
  lite2/store/store.go
Labels: C:light, T:enhancement

#4616 lite2: make maxClockDrift an option
  CHANGELOG_PENDING.md
  docs/architecture/adr-046-light-client-implementation.md
  lite2/client.go
  lite2/verifier.go
  lite2/verifier_test.go
Labels: C:light
