Repository tendermint/tendermint, pull requests merged in 2020-06, with the labels that each got.

#4923 rpc: add BlockByHash to supported methods
  CHANGELOG_PENDING.md
  lite/proxy/proxy.go
  lite/proxy/wrapper.go
  lite2/proxy/routes.go
  lite2/rpc/client.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
Labels: C:rpc, R:minor

#4931 lite2: correctly return the results of the "latest" block
  cmd/tendermint/commands/lite.go
  lite2/rpc/client.go
Labels: R:minor

#4870 evidence: retrieve header at height of evidence for validation
  consensus/reactor_test.go
  consensus/replay_stubs.go
  evidence/pool.go
  state/mocks/evidence_pool.go
  state/services.go
  state/validation.go
Labels: C:evidence

#4940 proto: move mempool to proto
  CHANGELOG_PENDING.md
  docs/app-dev/getting-started.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/codec.go
  mempool/mempool.go
  mempool/reactor.go
  state/tx_filter.go
  types/block.go
  types/tx.go
  types/tx_test.go
Labels: S:automerge, T:breaking

#4941 crypto: remove key suffixes
  CHANGELOG_PENDING.md
  abci/example/kvstore/persistent_kvstore.go
  crypto/README.md
  crypto/ed25519/ed25519.go
  crypto/encoding/amino/amino.go
  crypto/encoding/amino/encode_test.go
  crypto/encoding/codec.go
  crypto/multisig/codec.go
  crypto/multisig/threshold_pubkey.go
  crypto/multisig/threshold_pubkey_test.go
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_cgo.go
  crypto/secp256k1/secp256k1_cgo_test.go
  crypto/secp256k1/secp256k1_nocgo.go
  crypto/secp256k1/secp256k1_test.go
  crypto/sr25519/codec.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
  privval/file_test.go
  privval/socket_listeners.go
  privval/socket_listeners_test.go
  rpc/client/evidence_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/main.go
  types/protobuf.go
  types/validator_set_test.go
Labels: C:crypto, S:automerge, T:breaking

#4930 lite2: allow bigger requests to LC proxy
  cmd/tendermint/commands/lite.go
Labels: R:minor

#4929 lite2: check header w/ witnesses only when doing bisection
  CHANGELOG_PENDING.md
  lite2/client.go
Labels: R:minor

#4935 lite2: compare header with witnesses in parallel
  CHANGELOG_PENDING.md
  lite2/client.go
  lite2/errors.go
Labels: R:minor

#4943 statesync: use Protobuf instead of Amino for p2p traffic
  CHANGELOG_PENDING.md
  statesync/messages.go
  statesync/messages_test.go
  statesync/reactor.go
  statesync/reactor_test.go
  statesync/syncer.go
  statesync/syncer_test.go
Labels: C:sync, S:automerge

#4945 docs: document open file limit in production guide
  docs/tendermint-core/running-in-production.md
Labels: C:docs, S:automerge

#4829 p2p/conn: add a test for MakeSecretConnection
  libs/async/async.go
  libs/async/async_test.go
  p2p/conn/evil_secret_connection_test.go
  p2p/conn/secret_connection_test.go
Labels: R:minor

#4947 rpc/core: return an error if `page=0`
  CHANGELOG_PENDING.md
  light/provider/http/http.go
  light/proxy/routes.go
  light/rpc/client.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
  rpc/core/consensus.go
  rpc/core/env.go
  rpc/core/env_test.go
  rpc/core/mempool.go
  rpc/core/tx.go
  rpc/swagger/swagger.yaml
Labels: R:major

#4948 fix swagger page
  rpc/swagger/index.html
Labels: S:automerge

#4952 swagger: define version
  rpc/swagger/index.html
  rpc/swagger/swagger.yaml
Labels: C:docs, S:automerge

#4916 light: implement validate basic
  CHANGELOG_PENDING.md
  light/client.go
  light/client_test.go
Labels: C:light

#4950 keys: change to []bytes for keys (#4634)
  CHANGELOG_PENDING.md
  abci/example/kvstore/persistent_kvstore.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/encoding.go
  crypto/encoding/amino/encode_test.go
  crypto/encoding/codec.go
  crypto/secp256k1/encoding.go
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_test.go
  crypto/sr25519/encoding.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  privval/file_test.go
  rpc/client/evidence_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/main.go
  types/block.go
  types/proto3_test.go
  types/protobuf.go
  types/protobuf_test.go
  types/validator_set_test.go
Labels: C:crypto

#4939 ints: stricter numbers
  CHANGELOG_PENDING.md
  CONTRIBUTING.md
  blockchain/v1/reactor_test.go
  config/config.go
  config/toml.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set.go
  consensus/types/height_vote_set_test.go
  consensus/types/peer_round_state.go
  consensus/types/round_state.go
  evidence/pool.go
  libs/math/safemath.go
  light/helpers_test.go
  privval/file.go
  privval/file_test.go
  privval/signer_client_test.go
  proto/types/types.pb.go
  proto/types/types.proto
  rpc/client/evidence_test.go
  scripts/json2wal/main.go
  scripts/protocgen.sh
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state_test.go
  state/store.go
  state/tx_filter_test.go
  state/validation_test.go
  store/store.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/block.go
  types/block_test.go
  types/canonical.go
  types/events.go
  types/evidence.go
  types/evidence_test.go
  types/params.go
  types/part_set.go
  types/part_set_test.go
  types/proposal.go
  types/proposal_test.go
  types/signed_msg_type.go
  types/test_util.go
  types/validator_set.go
  types/validator_set_test.go
  types/vote.go
  types/vote_set.go
  types/vote_set_test.go
  types/vote_test.go
Labels: T:code-hygiene

#4959 evidence: json tags for DuplicateVoteEvidence
  CHANGELOG_PENDING.md
  types/evidence.go
Labels: C:evidence, S:automerge, T:breaking, T:ux

#4956 proto: add more to/from
  crypto/merkle/simple_proof.go
  crypto/merkle/simple_tree.go
  crypto/merkle/simple_tree_test.go
  types/block.go
  types/block_meta.go
  types/block_test.go
  types/part_set.go
  types/part_set_test.go
  types/tx_test.go
Labels: S:automerge, T:encoding

#4951 state: proto migration
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/kvstore_test.go
  abci/types/messages_test.go
  abci/types/types.pb.go
  abci/types/types.proto
  consensus/replay.go
  consensus/replay_test.go
  go.mod
  go.sum
  node/node_test.go
  p2p/node_info.go
  proto/crypto/merkle/types.pb.go
  proto/crypto/merkle/types.proto
  proto/libs/bits/types.pb.go
  proto/libs/bits/types.proto
  proto/types/types.pb.go
  proto/types/types.proto
  proto/version/version.pb.go
  proto/version/version.proto
  proxy/version.go
  rpc/core/tx.go
  rpc/grpc/types.pb.go
  rpc/grpc/types.proto
  state/execution.go
  state/state.go
  state/txindex/indexer.go
  state/txindex/indexer_service_test.go
  state/txindex/kv/codec.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
  state/txindex/null/null.go
  state/validation.go
  statesync/syncer.go
  statesync/syncer_test.go
  types/block.go
  types/block_test.go
  types/event_bus.go
  types/event_bus_test.go
  types/events.go
  types/protobuf.go
  types/protobuf_test.go
  types/tx.go
  version/version.go
Labels: T:breaking, T:encoding

#4961 types: remove VerifyFutureCommit
  types/validator_set.go
Labels: R:major, S:automerge

#4954 consensus: change logging and handling of height mismatch
  consensus/state.go
Labels: C:consensus, S:wip

#4962 types: migrate params to protobuf
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  abci/types/types.proto
  consensus/replay.go
  consensus/replay_test.go
  evidence/pool_test.go
  light/rpc/client.go
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  proto/types/params.pb.go
  proto/types/params.proto
  proto/types/validator.pb.go
  proto/types/validator.proto
  rpc/core/types/responses.go
  state/execution.go
  state/execution_test.go
  state/export_test.go
  state/helpers_test.go
  state/state.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/validation.go
  types/genesis.go
  types/params.go
  types/params_test.go
  types/protobuf.go
  types/protobuf_test.go
Labels: R:major, T:breaking, T:encoding

#4971 blockchain/v2: correctly set block store base in status responses
  CHANGELOG_PENDING.md
  blockchain/v2/io.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
Labels: C:p2p, C:sync, R:minor, S:automerge, T:bug

#4974 store: proto migration
  CHANGELOG_PENDING.md
  consensus/replay_test.go
  consensus/state.go
  evidence/pool_test.go
  evidence/reactor_test.go
  store/codec.go
  store/store.go
  store/store_test.go
  types/block.go
  types/block_test.go
  types/evidence.go
Labels: R:major, S:automerge, T:breaking, T:encoding

#4964 light: migrate to proto
  CHANGELOG_PENDING.md
  light/store/db/db.go
  light/store/db/db_test.go
  types/evidence.go
Labels: C:light, T:breaking, T:encoding

#4980 readme: add source graph badge
  README.md
Labels: S:automerge

#4973 p2p/pex: migrate to Protobuf
  CHANGELOG_PENDING.md
  p2p/netaddress.go
  p2p/pex/codec.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
Labels: C:p2p, R:major, S:automerge, T:breaking, T:encoding

#4981 p2p: expose SaveAs on NodeKey
  CHANGELOG_PENDING.md
  p2p/key.go
  p2p/key_test.go
Labels: R:minor, S:automerge

#4982 proto: remove amino proto tests
  types/proto3/block.pb.go
  types/proto3/block.proto
  types/proto3/result.go
  types/proto3_test.go
Labels: S:automerge, T:code-hygiene

#4972 state: proto migration
  consensus/replay.go
  consensus/replay_stubs.go
  consensus/replay_test.go
  evidence/pool_test.go
  rpc/core/blocks_test.go
  state/execution.go
  state/export_test.go
  state/helpers_test.go
  state/state.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/validation.go
  statesync/stateprovider.go
  statesync/syncer_test.go
Labels: R:major, S:automerge, T:breaking, T:encoding

#4955 json: add Amino-compatible encoder/decoder
  libs/json/decoder.go
  libs/json/decoder_test.go
  libs/json/doc.go
  libs/json/encoder.go
  libs/json/encoder_test.go
  libs/json/helpers_test.go
  libs/json/structs.go
  libs/json/types.go
Labels: S:automerge, T:encoding

#4968 rpc: replace Amino with new JSON encoder
  cmd/tendermint/commands/lite.go
  crypto/ed25519/ed25519.go
  light/proxy/proxy.go
  light/rpc/client.go
  node/node.go
  rpc/client/codec.go
  rpc/client/http/http.go
  rpc/core/events.go
  rpc/core/routes.go
  rpc/core/types/codec.go
  rpc/jsonrpc/client/args_test.go
  rpc/jsonrpc/client/decode.go
  rpc/jsonrpc/client/encode.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/http_uri_client.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_json_handler_test.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/parse_test.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/jsonrpc/server/ws_handler.go
  rpc/jsonrpc/server/ws_handler_test.go
  rpc/jsonrpc/test/main.go
  rpc/jsonrpc/types/types.go
  rpc/jsonrpc/types/types_test.go
  rpc/swagger/swagger.yaml
  rpc/test/helpers.go
  types/events.go
  types/evidence.go
Labels: C:rpc, R:major, S:automerge, T:encoding

#4975 migrate all JSON to new JSON encoder
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/codec.go
  cmd/tendermint/commands/gen_validator.go
  cmd/tendermint/commands/probe_upnp.go
  cmd/tendermint/commands/show_validator.go
  consensus/reactor.go
  consensus/state.go
  consensus/types/height_vote_set.go
  consensus/wal.go
  crypto/encoding/amino/encode_test.go
  crypto/secp256k1/encoding.go
  crypto/sr25519/encoding.go
  node/node.go
  p2p/key.go
  privval/file.go
  privval/file_test.go
  scripts/json2wal/main.go
  scripts/wal2json/main.go
  test/app/grpc_client.go
  types/genesis.go
  types/genesis_test.go
  types/part_set.go
  types/vote_set.go
Labels: S:automerge, T:encoding

#4969 blockchain: proto migration
  CHANGELOG_PENDING.md
  blockchain/msgs.go
  blockchain/msgs_test.go
  blockchain/v0/codec.go
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  blockchain/v1/codec.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_test.go
  blockchain/v2/codec.go
  blockchain/v2/io.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  config/toml.go
  consensus/reactor.go
  docs/tendermint-core/configuration.md
  go.mod
  go.sum
  proto/blockchain/msgs.pb.go
  proto/blockchain/msgs.proto
  types/block.go
  types/block_test.go
Labels: C:sync, R:major, S:automerge, T:breaking, T:encoding

#4979 rpc: support EXISTS operator in /tx_search query
  CHANGELOG_PENDING.md
  rpc/swagger/swagger.yaml
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
Labels: R:minor, S:automerge

#4949 evidence: migrate reactor to proto
  CHANGELOG_PENDING.md
  evidence/codec.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/reactor_test.go
  node/node_test.go
  proto/evidence/msgs.pb.go
  proto/evidence/msgs.proto
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  types/evidence.go
  types/evidence_test.go
Labels: C:evidence, R:major, S:automerge, T:breaking, T:encoding

#4988 crypto: removal of multisig
  CHANGELOG_PENDING.md
  UPGRADING.md
  crypto/encoding/amino/amino.go
  crypto/encoding/amino/encode_test.go
  crypto/multisig/bitarray/compact_bit_array.go
  crypto/multisig/bitarray/compact_bit_array_test.go
  crypto/multisig/codec.go
  crypto/multisig/multisignature.go
  crypto/multisig/threshold_pubkey.go
  crypto/multisig/threshold_pubkey_test.go
Labels: C:crypto, S:automerge, T:code-hygiene

#4991 types: Remove duplicated validation in VerifyCommit
  types/validator_set.go
Labels: S:automerge, T:code-hygiene

#4990 p2p/conn: migrate to Protobuf
  libs/protoio/io.go
  libs/protoio/io_test.go
  libs/protoio/reader.go
  libs/protoio/writer.go
  p2p/conn/codec.go
  p2p/conn/connection.go
  p2p/conn/connection_test.go
  p2p/conn/evil_secret_connection_test.go
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
  proto/p2p/conn_msgs.pb.go
  proto/p2p/conn_msgs.proto
Labels: C:p2p, S:automerge, T:encoding

#4970 consensus: stricter on LastCommitRound check
  CHANGELOG_PENDING.md
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/state.go
  consensus/types/round_state.go
Labels: R:minor

#4821 evidence: adr56 form amnesia evidence
  consensus/common_test.go
  consensus/state_test.go
  evidence/pool.go
  evidence/pool_test.go
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  proto/types/params.pb.go
  proto/types/params.proto
  state/store_test.go
  state/validation.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/evidence.go
  types/evidence_test.go
  types/params.go
  types/params_test.go
  types/priv_validator.go
  types/validator_set.go
  types/vote_set_test.go
Labels: C:evidence

#4983 proto: move keys to oneof
  abci/example/kvstore/kvstore_test.go
  abci/example/kvstore/persistent_kvstore.go
  abci/types/pubkey.go
  abci/types/types.pb.go
  abci/types/types.proto
  abci/types/util.go
  consensus/reactor_test.go
  consensus/replay_test.go
  crypto/crypto.go
  crypto/ed25519/ed25519.go
  crypto/encoding/amino/encode_test.go
  crypto/secp256k1/secp256k1.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  p2p/conn/secret_connection_test.go
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  proto/crypto/merkle/types.pb.go
  rpc/client/evidence_test.go
  rpc/client/helpers.go
  rpc/client/http/http.go
  rpc/client/rpc_test.go
  state/execution.go
  state/execution_test.go
  state/state_test.go
  types/protobuf.go
  types/protobuf_test.go
Labels: C:crypto, R:major, T:breaking, T:encoding

#4985 privval: migrate to protobuf
  CHANGELOG_PENDING.md
  blockchain/v1/reactor_test.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set_test.go
  crypto/ed25519/ed25519.go
  evidence/pool_test.go
  libs/math/safemath.go
  light/helpers_test.go
  privval/codec.go
  privval/errors.go
  privval/file.go
  privval/file_test.go
  privval/messages.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_endpoint.go
  privval/signer_listener_endpoint.go
  privval/signer_requestHandler.go
  privval/signer_server.go
  proto/privval/msgs.pb.go
  proto/privval/msgs.proto
  proto/privval/types.pb.go
  proto/privval/types.proto
  proto/types/canonical.pb.go
  proto/types/canonical.proto
  proto/types/types.pb.go
  proto/types/types.proto
  rpc/client/evidence_test.go
  state/tx_filter_test.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/internal/test_harness_test.go
  types/block.go
  types/block_test.go
  types/canonical.go
  types/evidence.go
  types/evidence_test.go
  types/priv_validator.go
  types/proposal.go
  types/proposal_test.go
  types/test_util.go
  types/validator_set_test.go
  types/vote.go
  types/vote_test.go
Labels: R:major, T:breaking, T:encoding, T:validator

#4995 p2p: proto leftover
  p2p/codec.go
  p2p/node_info.go
  p2p/transport.go
  p2p/transport_test.go
  proto/p2p/types.pb.go
  proto/p2p/types.proto
  state/codec.go
Labels: C:p2p, S:automerge, T:encoding

#4997 bring back binary:fixed64
  proto/types/canonical.pb.go
  proto/types/canonical.proto
Labels: S:automerge, T:validator

#4845 [block#LastResultsHash] add Events + GasWanted/Used
  CHANGELOG_PENDING.md
  proto/types/validator.pb.go
  scripts/protocgen.sh
  state/execution.go
  state/helpers_test.go
  state/state_test.go
  state/store.go
  state/store_test.go
  types/results.go
  types/results_test.go
Labels: R:major, T:breaking

#5007 tools: update gogoproto get cmd
  CONTRIBUTING.md
  tools.mk
Labels: C:docs, S:automerge

#4986 proto: leftover amino
  config/toml.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/encoding.go
  crypto/encoding/amino/amino.go
  crypto/encoding/amino/encode_test.go
  crypto/merkle/codec.go
  crypto/merkle/compile.sh
  crypto/merkle/proof.go
  crypto/merkle/proof_test.go
  crypto/merkle/proof_value.go
  crypto/merkle/types.go
  crypto/secp256k1/encoding.go
  crypto/secp256k1/secp256k1.go
  crypto/sr25519/encoding.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  node/node_test.go
  proto/crypto/merkle/types.pb.go
  proto/crypto/merkle/types.proto
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  proto/types/types.pb.go
  proto/types/types.proto
  proto/types/validator.pb.go
  proto/types/validator.proto
  state/main_test.go
  types/block.go
  types/block_meta.go
  types/block_test.go
  types/codec.go
  types/encoding_helper.go
  types/events.go
  types/evidence.go
  types/evidence_test.go
  types/params.go
  types/protobuf.go
  types/protobuf_test.go
  types/tx.go
  types/tx_test.go
  types/validator.go
  types/validator_set_test.go
Labels: R:major, T:breaking, T:encoding

#4996 encoding: remove codecs
  consensus/types/round_state_test.go
  crypto/encoding/amino/amino.go
  crypto/encoding/amino/encode_test.go
  crypto/merkle/proof_test.go
  go.mod
  go.sum
  node/codec.go
  state/main_test.go
Labels: R:major, S:automerge, T:breaking, T:encoding

#5015 ci: fix spacing of if statement
  .github/workflows/tests.yml
Labels: S:automerge

#5012 proto: move all proto dirs to /proto
  abci/types/types.pb.go
  proto/abci/types.proto
  proto/blockchain/msgs.pb.go
  proto/blockchain/msgs.proto
  proto/consensus/msgs.pb.go
  proto/consensus/msgs.proto
  proto/consensus/walmsgs.pb.go
  proto/consensus/walmsgs.proto
  proto/crypto/keys/types.pb.go
  proto/crypto/keys/types.proto
  proto/crypto/merkle/types.pb.go
  proto/crypto/merkle/types.proto
  proto/evidence/msgs.pb.go
  proto/evidence/msgs.proto
  proto/libs/bits/types.pb.go
  proto/libs/bits/types.proto
  proto/p2p/conn_msgs.pb.go
  proto/p2p/conn_msgs.proto
  proto/p2p/pex_msgs.pb.go
  proto/p2p/pex_msgs.proto
  proto/p2p/types.pb.go
  proto/p2p/types.proto
  proto/privval/msgs.pb.go
  proto/privval/msgs.proto
  proto/privval/types.pb.go
  proto/privval/types.proto
  proto/rpc/types.proto
  proto/state/types.pb.go
  proto/state/types.proto
  proto/statesync/types.pb.go
  proto/statesync/types.proto
  proto/store/types.pb.go
  proto/store/types.proto
  proto/types/block.pb.go
  proto/types/block.proto
  proto/types/canonical.pb.go
  proto/types/canonical.proto
  proto/types/events.pb.go
  proto/types/events.proto
  proto/types/evidence.pb.go
  proto/types/evidence.proto
  proto/types/params.pb.go
  proto/types/params.proto
  proto/types/types.pb.go
  proto/types/types.proto
  proto/types/validator.pb.go
  proto/types/validator.proto
  proto/version/version.pb.go
  proto/version/version.proto
  rpc/grpc/types.pb.go
  scripts/protocgen.sh
Labels: S:automerge, T:breaking, T:encoding

#5013 types: add tests for blockmeta
  types/block_meta_test.go
Labels: S:automerge, T:test

#5016 types: remove pubkey options
  types/params_test.go
  types/protobuf.go
Labels: S:automerge, T:code-hygiene, T:ux

#5017 rpc: add /check_tx endpoint
  CHANGELOG_PENDING.md
  light/rpc/client.go
  mempool/clist_mempool.go
  node/node.go
  proxy/app_conn.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
  rpc/core/env.go
  rpc/core/mempool.go
  rpc/core/routes.go
  rpc/core/types/responses.go
  rpc/swagger/swagger.yaml
Labels: R:minor

#5018 types: more test cases for TestValidatorSet_VerifyCommit
  types/block.go
  types/canonical.go
  types/proposal.go
  types/validator_set_test.go
  types/vote.go
  types/vote_set_test.go
Labels: S:automerge

#5033 cov: ignore autogen file
  codecov.yml
  proto/blockchain/msgs.proto
Labels: S:automerge

#5029 types: rename partsheader to partsetheader
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_test.go
  blockchain/v2/processor.go
  blockchain/v2/reactor_test.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/msgs.go
  consensus/msgs_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set_test.go
  consensus/types/peer_round_state.go
  consensus/types/round_state.go
  evidence/pool_test.go
  light/helpers_test.go
  privval/file_test.go
  privval/signer_client_test.go
  proto/abci/types.proto
  proto/consensus/msgs.pb.go
  proto/consensus/msgs.proto
  proto/types/canonical.pb.go
  proto/types/canonical.proto
  proto/types/types.pb.go
  proto/types/types.proto
  rpc/client/evidence_test.go
  state/execution_test.go
  state/helpers_test.go
  state/state_test.go
  state/validation_test.go
  store/store.go
  store/store_test.go
  tools/tm-signer-harness/internal/test_harness.go
  types/block.go
  types/block_meta_test.go
  types/block_test.go
  types/canonical.go
  types/canonical_test.go
  types/evidence_test.go
  types/part_set.go
  types/proposal_test.go
  types/protobuf.go
  types/vote_set_test.go
  types/vote_test.go
Labels: S:automerge, T:breaking, T:code-hygiene

#5038 Update UPGRADING.md and bump p2p/block protocol versions
  CHANGELOG.md
  CONTRIBUTING.md
  UPGRADING.md
  version/version.go
Labels: R:major, S:automerge

#5039 abci: proto files follow same path
  abci/types/types.pb.go
  proto/tendermint/abci/types/types.proto
  proto/tendermint/rpc/grpc/types.proto
  proto/tendermint/state/types.pb.go
  proto/tendermint/state/types.proto
  rpc/grpc/types.pb.go
  scripts/protocgen.sh
Labels: C:abci, S:automerge

#5032 types: fix evidence timestamp calculation
  types/evidence.go
  types/evidence_test.go
Labels: S:automerge

#5031 types: add AppVersion to ConsensusParams
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  consensus/replay.go
  proto/tendermint/abci/types/types.proto
  proto/tendermint/consensus/walmsgs.pb.go
  proto/tendermint/crypto/keys/types.pb.go
  proto/tendermint/types/params.pb.go
  proto/tendermint/types/params.proto
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state_test.go
  state/validation_test.go
  types/params.go
  types/params_test.go
Labels: R:minor

#5041 types: reject blocks w/ ConflictingHeadersEvidence
  types/block.go
  types/block_test.go
Labels: R:minor

#5003 evidence: improve amnesia evidence handling
  consensus/reactor_test.go
  consensus/replay_stubs.go
  consensus/state.go
  consensus/state_test.go
  evidence/doc.go
  evidence/pool.go
  evidence/pool_test.go
  light/client.go
  light/client_test.go
  rpc/client/evidence_test.go
  state/validation.go
  state/validation_test.go
  types/block.go
  types/evidence.go
  types/evidence_test.go
Labels: C:evidence

#5006 indexer: remove index filtering
  CHANGELOG_PENDING.md
  UPGRADING.md
  abci/example/kvstore/kvstore.go
  config/config.go
  config/toml.go
  docs/app-dev/indexing-transactions.md
  go.sum
  node/node.go
  rpc/client/rpc_test.go
  rpc/test/helpers.go
  state/txindex/indexer_service_test.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
Labels: S:automerge, T:ux

#5036 evidence: replace mock evidence with mocked duplicate vote evidence
  consensus/reactor_test.go
  evidence/pool_test.go
  evidence/reactor_test.go
  node/node_test.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/evidence.proto
  state/execution_test.go
  state/validation_test.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
  types/protobuf.go
Labels: C:evidence, T:bug

#5044 rpc: move docs from doc.go to swagger.yaml
  rpc/core/doc.go
  rpc/swagger/swagger.yaml
Labels: S:automerge

#5048 p2p: Remove data race bug in netaddr stringer
  p2p/netaddress.go
  p2p/netaddress_test.go
Labels: C:p2p, S:automerge

#5049 upgrading.md additions
  CHANGELOG_PENDING.md
  UPGRADING.md
  rpc/swagger/swagger.yaml
Labels: S:automerge, T:ux

#5054 mempool: make it clear overwriting of pre/postCheck filters is intent…
  mempool/clist_mempool.go
Labels: C:docs, S:automerge

#5055 behaviour: add simple doc.go
  behaviour/doc.go
Labels: C:docs, S:automerge

#5056 abci/example/kvstore: decrease val power by 1 upon equivocation
  abci/example/kvstore/persistent_kvstore.go
  networks/remote/integration.sh
Labels: S:automerge

#5062 tests: use github.sha in binary cache key
  .github/workflows/tests.yml
Labels: T:test

#5061 types: simplify safeMul
  types/validator_set.go
  types/validator_set_test.go
Labels: S:automerge

#5063 mempool: use oneof
  mempool/reactor.go
  proto/tendermint/consensus/walmsgs.pb.go
  proto/tendermint/crypto/keys/types.pb.go
  proto/tendermint/mempool/msgs.pb.go
  proto/tendermint/mempool/msgs.proto
Labels: C:mempool, S:automerge
