Repository tendermint/tendermint, pull requests merged in 2020-12, with the labels that each got.

#5729 readme: remover circleci badge
  README.md
Labels: S:automerge

#5720 libs/bits: validate BitArray in FromProto
  CHANGELOG_PENDING.md
  consensus/msgs.go
  libs/bits/bit_array.go
  libs/bits/bit_array_test.go
  test/maverick/consensus/msgs.go
Labels: S:automerge

#5716 light: minor fixes / standardising errors
  light/client.go
  light/detector.go
  light/errors.go
  light/provider/http/http.go
  light/provider/mock/deadmock.go
  light/provider/mock/mock.go
  light/provider/provider.go
  light/store/db/db.go
  light/verifier.go
Labels: C:light, S:automerge

#5711 blockchain/v1: fix deadlock
  CHANGELOG_PENDING.md
  blockchain/v1/reactor.go
  blockchain/v1/reactor_test.go
Labels: S:automerge

#5728 blockchain/v1: remove in favor of v2
  CHANGELOG_PENDING.md
  UPGRADING.md
  blockchain/v1/peer.go
  blockchain/v1/peer_test.go
  blockchain/v1/pool.go
  blockchain/v1/pool_test.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_fsm.go
  blockchain/v1/reactor_fsm_test.go
  blockchain/v1/reactor_test.go
  config/config.go
  config/config_test.go
  config/toml.go
  docs/nodes/configuration.md
  docs/tendermint-core/fast-sync.md
  node/node.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/maverick/node/node.go
Labels: T:breaking

#5738 changelog: add entry back
  CHANGELOG_PENDING.md
  UPGRADING.md
Labels: S:automerge

#5740 UX: version configuration
  Makefile
  docs/tendermint-core/running-in-production.md
Labels: S:automerge, T:ux

#5743 reactors: omit incoming message bytes from reactor logs
  blockchain/v0/reactor.go
  blockchain/v2/reactor.go
  consensus/reactor.go
  mempool/reactor.go
  p2p/pex/pex_reactor.go
  statesync/reactor.go
  test/maverick/consensus/reactor.go
Labels: S:automerge, S:backport

#5760 dep: bump ed25519consensus version
  go.mod
  go.sum
Labels: C:crypto, S:automerge

#5736 docs: add version dropdown and v0.34 docs
  docs/.vuepress/config.js
  docs/versions
Labels: C:docs

#5748 node: improve test coverage on proposal block
  node/node_test.go
Labels: S:automerge

#5671 p2p refactor: state sync reactor
  node/node.go
  p2p/channel.go
  p2p/peer.go
  p2p/peer_test.go
  p2p/shim.go
  p2p/shim_test.go
  proto/tendermint/statesync/message.go
  proto/tendermint/statesync/message_test.go
  statesync/chunks.go
  statesync/chunks_test.go
  statesync/messages.go
  statesync/messages_test.go
  statesync/reactor.go
  statesync/reactor_test.go
  statesync/snapshots.go
  statesync/snapshots_test.go
  statesync/syncer.go
  statesync/syncer_test.go
  test/maverick/node/node.go
Labels: C:p2p

#5778 Makefile: use git 2.20-compatible branch detection
  Makefile
Labels: S:automerge

#5777 cmd: hyphen case cli and config
  CHANGELOG_PENDING.md
  DOCKER/Dockerfile
  DOCKER/docker-entrypoint.sh
  UPGRADING.md
  cmd/tendermint/commands/gen_node_key.go
  cmd/tendermint/commands/gen_validator.go
  cmd/tendermint/commands/light.go
  cmd/tendermint/commands/probe_upnp.go
  cmd/tendermint/commands/replay.go
  cmd/tendermint/commands/reset_priv_validator.go
  cmd/tendermint/commands/root.go
  cmd/tendermint/commands/root_test.go
  cmd/tendermint/commands/run_node.go
  cmd/tendermint/commands/show_node_id.go
  cmd/tendermint/commands/show_validator.go
  cmd/tendermint/commands/testnet.go
  config/config.go
  config/toml.go
  test/app/test.sh
  test/e2e/docker/Dockerfile
  test/e2e/runner/setup.go
  test/maverick/main.go
Labels: T:breaking, T:ux

#5791 p2p: implement new Transport interface
  consensus/byzantine_test.go
  libs/log/testing_logger.go
  node/node.go
  p2p/conn/connection.go
  p2p/netaddress.go
  p2p/node_info.go
  p2p/peer.go
  p2p/peer_test.go
  p2p/pex/pex_reactor_test.go
  p2p/switch.go
  p2p/switch_test.go
  p2p/test_util.go
  p2p/transport.go
  p2p/transport_mconn.go
  p2p/transport_test.go
  test/maverick/node/node.go
Labels: C:p2p, S:automerge

#5799 p2p: remove `NodeInfo` interface and rename `DefaultNodeInfo` struct
  CHANGELOG_PENDING.md
  blockchain/v2/reactor_test.go
  node/node.go
  node/node_test.go
  p2p/mock/peer.go
  p2p/node_info.go
  p2p/node_info_test.go
  p2p/peer_set_test.go
  p2p/peer_test.go
  p2p/test_util.go
  p2p/transport.go
  p2p/transport_mconn.go
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/p2p/types.proto
  rpc/core/net.go
  rpc/core/status.go
  rpc/core/types/responses.go
  rpc/core/types/responses_test.go
  test/maverick/node/node.go
Labels: C:p2p, S:automerge, T:breaking

#5810 p2p: fix data race in MakeSwitch test helper
  p2p/test_util.go
  p2p/transport_mconn.go
Labels: S:automerge

#5819 mempool: introduce KeepInvalidTxsInCache config option (#5813)
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  docs/tendermint-core/configuration.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
Labels: S:backport

#5820 mempool: disable MaxBatchBytes (#5800)
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  docs/tendermint-core/configuration.md
  mempool/reactor.go
  mempool/reactor_test.go
Labels: S:backport

#5818 abci: use protoio for length delimitation
  CHANGELOG_PENDING.md
  UPGRADING.md
  abci/types/messages.go
Labels: C:abci, T:breaking

#5822 docs: specify master for tutorials
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: C:abci, C:docs, S:automerge

#5823 docs/tutorials: specify 0.34
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: C:abci, C:docs, S:backport

#5824 ci: run `goreleaser build`
  .github/workflows/release.yml
  .goreleaser.yml
Labels: S:automerge

#5827 p2p: add MemoryTransport, an in-memory transport for testing
  p2p/transport_memory.go
  p2p/transport_memory_test.go
Labels: C:p2p

#5826 modify Reactor priorities
  blockchain/v0/reactor.go
  blockchain/v2/reactor.go
  consensus/reactor.go
  evidence/reactor.go
  statesync/reactor.go
  test/maverick/consensus/reactor.go
Labels: S:automerge

#5828 proxy: improve ABCI app connection handling (#5078)
  CHANGELOG_PENDING.md
  abci/client/mocks/client.go
  consensus/state.go
  proxy/client.go
  proxy/mocks/client_creator.go
  proxy/multi_app_conn.go
  proxy/multi_app_conn_test.go
Labels: S:backport

#5830 modify Reactor priorities (#5826)
  blockchain/v0/reactor.go
  blockchain/v2/reactor.go
  consensus/reactor.go
  evidence/reactor.go
  statesync/reactor.go
  test/maverick/consensus/reactor.go
Labels: S:automerge, S:backport
