Repository tendermint/tendermint, pull requests merged in 2021-08, with the labels that each got.

#6772 mempool/v1: test reactor does not panic on broadcast
  internal/mempool/v1/reactor.go
  internal/mempool/v1/reactor_test.go
Labels: S:automerge

#6791 clist: add simple property tests
  go.mod
  go.sum
  internal/libs/clist/clist_property_test.go
Labels: S:automerge

#6794 docs: upgrade documentation for custom mempools
  UPGRADING.md
Labels: S:automerge

#6798 node: minimize hardcoded service initialization
  node/node.go
  node/node_test.go
  node/setup.go
  rpc/client/local/local.go
Labels: S:automerge

#6823 doc: fix typos in /tx_search and /tx.
  rpc/openapi/openapi.yaml
Labels: C:docs, S:automerge

#6825 rpc: log update
  CHANGELOG_PENDING.md
  rpc/core/abci.go
Labels: S:automerge, S:backport-to-v0.34.x

#6836 changelog: linkify the 0.34.11 release notes
  CHANGELOG.md
Labels: S:automerge

#6835 e2e: avoid starting nodes from the future
  test/e2e/runner/start.go
Labels: S:backport-to-v0.34.x

#6839 docs: add package godoc for indexer
  state/indexer/doc.go
Labels: C:docs, S:automerge, C:indexer

#6842 e2e: cleanup node start function
  test/e2e/runner/start.go
Labels: S:automerge, S:backport-to-v0.34.x

#6853 time: make median time library type private
  libs/time/time.go
  state/state.go
  state/time.go
  state/time_test.go
Labels: S:automerge

#6854 cmd: remove deprecated snakes
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/gen_node_key.go
  cmd/tendermint/commands/gen_validator.go
  cmd/tendermint/commands/probe_upnp.go
  cmd/tendermint/commands/replay.go
  cmd/tendermint/commands/reset_priv_validator.go
  cmd/tendermint/commands/root.go
  cmd/tendermint/commands/show_node_id.go
  cmd/tendermint/commands/show_validator.go
Labels: S:automerge

#6785 inspect: add inspect mode for debugging crashed tendermint node
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/inspect.go
  cmd/tendermint/main.go
  docs/tools/debugging/README.md
  docs/tools/debugging/pro.md
  go.mod
  go.sum
  inspect/doc.go
  inspect/inspect.go
  inspect/inspect_test.go
  inspect/rpc/rpc.go
  light/proxy/proxy.go
  node/node.go
  node/setup.go
  rpc/core/env.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/test/main.go
  state/indexer/indexer_service.go
  state/indexer/sink/sink.go
Labels: S:automerge

#6857 e2e: more consistent node selection during tests
  test/e2e/pkg/testnet.go
  test/e2e/runner/evidence.go
  test/e2e/runner/load.go
Labels: S:automerge

#6861 lint: change deprecated linter
  .golangci.yml
Labels: S:automerge

#6875 types: move mempool error for consistency
  internal/mempool/v0/clist_mempool.go
  internal/mempool/v0/clist_mempool_test.go
  internal/mempool/v1/mempool.go
  types/mempool.go
Labels: S:automerge

#6880 e2e: more reliable method for selecting node to inject evidence
  test/e2e/runner/evidence.go
Labels: S:automerge
