Repository tendermint/tendermint, pull requests merged in 2021-09, with the labels that each got.

#6884 e2e: weight protocol dimensions
  test/e2e/generator/generate.go
Labels: S:automerge

#6909 doc: fix a typo in the indexing section
  docs/app-dev/indexing-transactions.md
Labels: S:automerge

#6910 cleanup: fix order of linters in the golangci-lint config
  .golangci.yml
Labels: S:automerge

#6893 update changelog ahead of v0.35 release
  CHANGELOG.md
  CHANGELOG_PENDING.md
Labels: S:automerge

#6896 rename configuration parameters to use the new blocksync nomenclature
  UPGRADING.md
  cmd/tendermint/commands/run_node.go
  config/config.go
  config/toml.go
  config/toml_test.go
  docs/nodes/configuration.md
  docs/tendermint-core/block-sync.md
  go.mod
  node/node.go
  test/e2e/runner/setup.go
Labels: S:automerge

#6920 ci: tweak code coverage settings
  .github/codecov.yml
  .github/workflows/coverage.yml
Labels: S:automerge

#6926 e2e: compile tests
  .github/workflows/e2e-nightly-master.yml
  .github/workflows/e2e.yml
  test/e2e/Makefile
  test/e2e/run-multiple.sh
  test/e2e/runner/main.go
  test/e2e/runner/test.go
  test/e2e/tests/e2e_test.go
Labels: S:automerge

#6929 e2e: improve p2p mode selection
  test/e2e/generator/generate.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
Labels: S:automerge

#6935 Update CHANGELOG.md for release v0.34.13.
  CHANGELOG.md
Labels: S:automerge

#6936 e2e: slow load processes with longer evidence timeouts
  test/e2e/runner/evidence.go
  test/e2e/runner/load.go
Labels: S:automerge

#6948 docs: fix openapi yaml lint
  rpc/openapi/openapi.yaml
Labels: S:automerge

#6949 e2e: skip broadcastTxCommit check
  test/e2e/tests/app_test.go
Labels: S:automerge

#6921 rfc: add performance taxonomy rfc
  docs/rfc/README.md
  docs/rfc/rfc-003-performance-questions.md
  internal/consensus/state.go
Labels: S:automerge

#6952 e2e: allow load generator to succed for short tests
  test/e2e/runner/load.go
Labels: S:automerge

#6950 e2e: cleanup on all errors if preserve not specified
  test/e2e/runner/main.go
Labels: S:automerge

#6879 config/docs: update and deprecated
  config/toml.go
  docs/networks/README.md
  docs/nodes/configuration.md
  docs/tutorials/go-built-in.md
Labels: S:automerge

#6965 readme: update discord links
  README.md
  docs/.vuepress/config.js
  docs/tools/debugging/pro.md
Labels: S:automerge

#6969 consensus: remove panics from test helper functions
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay_test.go
  internal/consensus/state_test.go
Labels: S:automerge

#6885 ABCI Vote Extension 2
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/mocks/client.go
  abci/example/kvstore/persistent_kvstore.go
  abci/types/application.go
  abci/types/messages.go
  abci/types/result.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/state.go
  privval/msgs_test.go
  proxy/app_conn.go
  rpc/client/helpers.go
  rpc/client/rpc_test.go
  state/execution.go
  state/execution_test.go
  test/e2e/app/app.go
  types/block.go
  types/vote.go
  types/vote_set.go
Labels: C:abci

#6973 Fix script paths in go:generate directives.
  internal/proxy/app_conn.go
  internal/state/indexer/eventsink.go
  internal/state/mocks/evidence_pool.go
  internal/state/mocks/store.go
  internal/state/services.go
  internal/state/store.go
Labels: S:automerge

#6977 proto: regenerate code
  proto/tendermint/state/types.pb.go
  proto/tendermint/statesync/types.pb.go
  rpc/grpc/types.pb.go
Labels: S:automerge

#6991 e2e: skip validation of status apphash
  test/e2e/tests/app_test.go
Labels: S:automerge

#6992 e2e: do not inject evidence through light proxy
  test/e2e/runner/evidence.go
Labels: S:automerge

#6993 ci: use smart merges
  .github/mergify.yml
Labels: S:automerge

#6995 statesync: clean up reactor/syncer lifecylce
  internal/statesync/reactor.go
  internal/statesync/reactor_test.go
  internal/statesync/stateprovider.go
  internal/statesync/syncer.go
Labels: S:automerge

#6998 e2e: add limit and sort to generator
  test/e2e/generator/generate.go
  test/e2e/generator/main.go
  test/e2e/pkg/manifest.go
Labels: S:automerge

#7001 e2e: improve chances of statesyncing success
  test/e2e/generator/generate.go
Labels: S:automerge

#7004 e2e: reduce log noise while waiting
  test/e2e/runner/rpc.go
Labels: S:automerge

#7006 e2e: avoid seed nodes when statesyncing
  test/e2e/generator/generate.go
Labels: S:automerge

#7008 e2e: add generator tests
  .github/workflows/coverage.yml
  test/e2e/generator/generate.go
  test/e2e/generator/generate_test.go
  test/e2e/pkg/manifest.go
Labels: S:automerge

#7007 statesync: add logging while waiting for peers
  internal/statesync/reactor.go
Labels: S:automerge

#7010 e2e: reduce number of stateless nodes in test networks
  test/e2e/generator/generate.go
Labels: S:automerge

#7016 e2e: use smaller transactions
  test/e2e/generator/generate.go
Labels: S:automerge

#7019 e2e: use network size in load generator
  test/e2e/runner/evidence.go
  test/e2e/runner/load.go
  test/e2e/runner/main.go
Labels: S:automerge

#7021 e2e: generator ensure p2p modes
  test/e2e/generator/generate.go
  test/e2e/generator/generate_test.go
  test/e2e/generator/main.go
  test/e2e/tests/app_test.go
Labels: S:automerge

#7025 consensus: avoid unbuffered channel in state test
  internal/consensus/state.go
  internal/consensus/state_test.go
Labels: S:automerge

#7026 statesync: ensure test network properly configured
  internal/statesync/dispatcher.go
  internal/statesync/reactor.go
  internal/statesync/reactor_test.go
Labels: S:automerge

#7030 blocksync: fix shutdown deadlock issue
  internal/blocksync/v0/reactor.go
Labels: S:automerge

#7037 Align atomic struct field for compatibility in 32-bit ABIs.
  internal/p2p/conn/connection.go
Labels: T:bug, C:p2p

#7029 statesync: remove deadlock on init fail
  internal/statesync/reactor.go
  internal/statesync/syncer.go
  internal/statesync/syncer_test.go
Labels: S:automerge
