Repository tendermint/tendermint, pull requests merged in 2021-12, with the labels that each got.

#7362 tools/tm-signer-harness: switch to not use hardcoded bytes for configs in test
  tools/tm-signer-harness/internal/test_harness_test.go
Labels: S:automerge

#7315 cmd: add integration test for rollback functionality
  cmd/tendermint/commands/rollback.go
  cmd/tendermint/commands/rollback_test.go
  internal/evidence/pool.go
  internal/evidence/reactor.go
  internal/state/mocks/store.go
  internal/state/rollback.go
  internal/state/rollback_test.go
  internal/state/store.go
  internal/store/store.go
  node/node.go
  node/setup.go
  test/e2e/app/app.go
  test/e2e/app/state.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7374 ci: move test execution to makefile (#7372)
  .github/workflows/coverage.yml
  Makefile
Labels: S:automerge

#7375 Revert CI test timeout.
  Makefile
Labels: S:automerge

#7385 Update mergify configuration.
  .github/mergify.yml
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7388 Update Mergify configuration.
  .github/mergify.yml
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7393 ci: cleanup build/test targets
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/docker.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/tests.yml
Labels: S:backport-to-v0.35.x

#7397 ci: skip docker image builds during PRs
  .github/workflows/docker.yml
Labels: S:backport-to-v0.35.x

#7404 Revert "ci: tweak e2e configuration (#7400)"
  test/e2e/networks/ci.toml
Labels: S:automerge

#7377 cmd: cosmetic changes for errors and print statements
  cmd/tendermint/commands/reindex_event.go
  cmd/tendermint/commands/reindex_event_test.go
  cmd/tendermint/commands/rollback.go
Labels: S:automerge, S:backport-to-v0.35.x

#7403 p2p: migrate to use new interface for channel errors
  internal/blocksync/reactor.go
  internal/consensus/reactor.go
  internal/evidence/reactor.go
  internal/mempool/reactor.go
  internal/p2p/channel.go
  internal/p2p/channel_test.go
  internal/p2p/p2ptest/require.go
  internal/p2p/pex/reactor.go
  internal/p2p/router_test.go
  internal/statesync/reactor.go
Labels: S:automerge

#7409 mempool: avoid arbitrary background contexts
  internal/consensus/replay_stubs.go
  internal/mempool/mempool.go
  internal/mempool/mempool_test.go
  internal/mempool/mock/mempool.go
  internal/mempool/reactor_test.go
  internal/mempool/types.go
  internal/state/execution.go
  rpc/client/mocks/client.go
Labels: S:automerge

#7410 state: pass connected context
  internal/state/execution.go
Labels: S:automerge

#7416 Fix links to Terraform/Ansible documentation.
  README.md
  networks/remote/README.md
Labels: S:backport-to-v0.35.x

#7439 Fix broken documentation link.
  README.md
  docs/tools/docker-compose.md
Labels: S:automerge, S:backport-to-v0.35.x
