Repository tendermint/tendermint, pull requests merged in 2021-07, with the labels that each got.

#6634 Refactor Event Subscription
  CHANGELOG_PENDING.md
  internal/consensus/reactor.go
  internal/consensus/state.go
  libs/events/events.go
  libs/pubsub/example_test.go
  libs/pubsub/pubsub.go
  libs/pubsub/pubsub_test.go
  libs/pubsub/query/empty.go
  libs/pubsub/query/empty_test.go
  libs/pubsub/query/query.go
  libs/pubsub/query/query_test.go
  libs/pubsub/subscription.go
  rpc/client/event_test.go
  rpc/client/helpers.go
  rpc/core/types/responses.go
  types/event_bus.go
  types/event_bus_test.go
  types/events.go
  types/events_test.go
Labels: C:events

#6627 pkg: expose p2p functions
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/gen_node_key.go
  cmd/tendermint/commands/init.go
  cmd/tendermint/commands/show_node_id.go
  cmd/tendermint/commands/testnet.go
  config/config.go
  internal/p2p/mock/peer.go
  internal/p2p/peer_set_test.go
  internal/p2p/switch.go
  internal/p2p/test_util.go
  node/node.go
  node/node_test.go
  node/public.go
  node/setup.go
  test/e2e/runner/setup.go
  types/node_key.go
  types/node_key_test.go
Labels: C:p2p, S:automerge

#6654 Revert "consensus: skip all messages during sync (#6577)"
  internal/consensus/reactor.go
Labels: C:consensus

#6658 docs: update events
  docs/app-dev/indexing-transactions.md
  node/setup.go
  state/indexer/sink/psql/schema.sql
Labels: C:docs, S:automerge

#6655 docs: add sentence about windows support
  docs/nodes/running-in-production.md
Labels: C:docs, S:automerge

#6664 state/indexer: close row after query
  state/indexer/sink/psql/psql.go
Labels: S:automerge

#6666 deps: remove pkg errors
  go.mod
  scripts/keymigrate/migrate.go
Labels: S:automerge, T:dependencies

#6668 abci: Fix gitignore abci-cli
  .gitignore
  CHANGELOG_PENDING.md
Labels: S:automerge

#6637 internal/blockchain/v0: prevent all possible race for blockchainCh.Out
  internal/blockchain/v0/reactor.go
Labels: C:sync, S:automerge

#6670 e2e: remove colorized output from docker-compose
  test/e2e/runner/exec.go
  test/e2e/runner/main.go
Labels: S:automerge

#6677 deps: run go mod tidy
  go.mod
  go.sum
Labels: S:automerge

#6688 p2p: remove annoying error log
  internal/p2p/router.go
Labels: S:automerge

#6689 tools: move tools.go to subdir
  tools/tools.go
Labels: S:automerge

#6692 statesync: keep peer despite lightblock query fail
  internal/statesync/reactor.go
Labels: S:automerge

#6684 abci: remove counter app
  .github/workflows/tests.yml
  CHANGELOG_PENDING.md
  abci/cmd/abci-cli/abci-cli.go
  abci/example/counter/counter.go
  abci/tests/test_app/app.go
  abci/tests/test_app/main.go
  abci/tests/test_app/test.sh
  abci/tests/test_cli/test.sh
  cmd/tendermint/commands/run_node.go
  docs/app-dev/abci-cli.md
  docs/app-dev/getting-started.md
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/invalid_test.go
  internal/consensus/reactor_test.go
  internal/consensus/state_test.go
  internal/mempool/v0/clist_mempool_test.go
  proxy/client.go
  test/README.md
  test/app/test.sh
Labels: C:abci

#6701 light: add case to catch cancelled contexts within the detector
  light/client_test.go
  light/detector.go
  light/provider/mock/mock.go
Labels: S:backport-to-v0.34.x

#6713 statesync: dispatcher test uses internal channel for timing
  internal/statesync/dispatcher_test.go
Labels: S:automerge

#6719 docs: fix broken links
  docs/architecture/README.md
  docs/architecture/adr-042-state-sync.md
  docs/architecture/adr-044-lite-client-with-weak-subjectivity.md
  docs/architecture/adr-045-abci-evidence.md
  docs/architecture/adr-047-handling-evidence-from-light-client.md
  docs/nodes/logging.md
  docs/nodes/running-in-production.md
  docs/tendermint-core/subscription.md
  docs/tendermint-core/using-tendermint.md
Labels: C:docs, S:automerge

#6723 e2e: tweak sleep for pertubations
  test/e2e/runner/perturb.go
Labels: S:automerge

#6725 RPC: mark grpc as deprecated
  CHANGELOG_PENDING.md
  UPGRADING.md
  config/config.go
  config/toml.go
  rpc/grpc/api.go
  rpc/grpc/client_server.go
Labels: C:rpc, S:automerge

#6730 blockchain: error on v2 selection
  CHANGELOG_PENDING.md
  UPGRADING.md
  config/config.go
  config/config_test.go
  config/toml.go
  node/setup.go
Labels: S:automerge

#6732 add and run make target for generating existing mocks
  Makefile
  abci/client/mocks/client.go
  internal/p2p/mocks/connection.go
  internal/p2p/mocks/peer.go
  internal/p2p/mocks/transport.go
  light/provider/provider.go
  rpc/client/mocks/client.go
  state/mocks/store.go
Labels: S:automerge

#6727 clist: add a few basic clist tests
  internal/libs/clist/clist_test.go
Labels: S:automerge

#6715 feature: add TTL configuration to mempool
  config/config.go
  config/toml.go
  docs/nodes/configuration.md
  internal/mempool/v1/mempool.go
  internal/mempool/v1/mempool_test.go
  internal/mempool/v1/tx.go
  internal/mempool/v1/tx_test.go
Labels: C:mempool

#6619 fastsync/event: emit fastsync status event when switching consensus/fastsync
  CHANGELOG_PENDING.md
  docs/tendermint-core/fast-sync.md
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  node/node.go
  types/event_bus.go
  types/event_bus_test.go
  types/events.go
Labels: S:automerge

#6734 e2e: remove cartesian testing of ipv6
  test/e2e/generator/generate.go
Labels: S:automerge

#6746 fix makefile test target to rely on test makefile
  Makefile
Labels: S:automerge

#6743 e2e: prevent adding light clients as persistent peers
  test/e2e/pkg/testnet.go
Labels: S:automerge

#6728 e2e: longer test harness timeouts
  .github/workflows/e2e-nightly-master.yml
  test/e2e/runner/evidence.go
  test/e2e/runner/main.go
  test/e2e/runner/perturb.go
  test/e2e/runner/start.go
  test/e2e/runner/wait.go
Labels: S:automerge

#6740 mempool: return mempool errors to the abci client
  abci/types/types.pb.go
  internal/mempool/v1/mempool.go
  internal/mempool/v1/mempool_test.go
  proto/tendermint/abci/types.proto
  proto/tendermint/p2p/types.pb.go
  rpc/core/mempool.go
  rpc/core/types/responses.go
Labels: S:automerge

#6749 internal: update blockchain reactor godoc
  internal/blockchain/doc.go
Labels: C:docs, C:sync, S:automerge

#6754 p2p: add coverage for mConnConnection.TrySendMessage
  internal/p2p/conn/connection.go
  internal/p2p/transport_mconn_test.go
  internal/p2p/transport_test.go
Labels: S:automerge

#6757 test/fuzz: add test to reproduce found fuzz errors
  test/fuzz/rpc/jsonrpc/server/fuzz_test.go
  test/fuzz/rpc/jsonrpc/server/handler.go
  test/fuzz/rpc/jsonrpc/server/testdata/1184f5b8d4b6dd08709cf1513f26744167065e0d
  test/fuzz/rpc/jsonrpc/server/testdata/clusterfuzz-testcase-minimized-fuzz_rpc_jsonrpc_server-4738572803506176
Labels: S:automerge

#6760 p2p: add test for pqueue dequeue full error
  internal/p2p/pqueue_test.go
Labels: S:automerge

#6767 ci: avoid issues already labeled
  .github/workflows/stale.yml
Labels: S:automerge

#6544 abci: PrepareProposal
  abci/client/client.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/mocks/client.go
  abci/client/socket_client.go
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/persistent_kvstore.go
  abci/server/socket_server.go
  abci/types/application.go
  abci/types/messages.go
  abci/types/types.pb.go
  internal/consensus/mempool_test.go
  internal/evidence/mocks/block_store.go
  internal/statesync/mocks/state_provider.go
  libs/pubsub/query/query.peg.go
  light/rpc/mocks/light_client.go
  proto/tendermint/abci/types.proto
  proxy/app_conn.go
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  state/execution.go
  state/mocks/evidence_pool.go
  state/mocks/store.go
  test/e2e/app/app.go
  types/tx.go
Labels: C:abci

#6770 abci: add changelog entry for mempool_error field
  CHANGELOG_PENDING.md
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
Labels: S:automerge

#6735 light: replace homegrown mock with mockery
  light/client_benchmark_test.go
  light/client_test.go
  light/detector_test.go
  light/helpers_test.go
  light/provider/mock/deadmock.go
  light/provider/mock/mock.go
  light/provider/mocks/provider.go
Labels: S:automerge

#6748 state/privval: vote timestamp fix
  internal/consensus/common_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
Labels: S:backport-to-v0.34.x

#6787 tools: add mockery to tools.go and remove mockery version strings
  Makefile
  abci/client/client.go
  abci/client/mocks/client.go
  go.mod
  go.sum
  internal/consensus/mocks/cons_sync_reactor.go
  internal/consensus/reactor.go
  internal/evidence/mocks/block_store.go
  internal/evidence/services.go
  internal/p2p/mocks/connection.go
  internal/p2p/mocks/peer.go
  internal/p2p/mocks/transport.go
  internal/p2p/peer.go
  internal/p2p/transport.go
  internal/statesync/mocks/state_provider.go
  internal/statesync/stateprovider.go
  light/provider/mocks/provider.go
  light/provider/provider.go
  light/rpc/client.go
  light/rpc/mocks/light_client.go
  proxy/app_conn.go
  proxy/client.go
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  proxy/mocks/client_creator.go
  rpc/client/interface.go
  rpc/client/mocks/client.go
  scripts/mockery_generate.sh
  state/indexer/eventsink.go
  state/indexer/mocks/event_sink.go
  state/mocks/block_store.go
  state/mocks/evidence_pool.go
  state/mocks/store.go
  state/services.go
  state/store.go
  tools/tools.go
Labels: S:automerge
