Repository tendermint/tendermint, pull requests merged in 2021-04, with the labels that each got.

#6309 Adds missing line break
  docs/introduction/what-is-tendermint.md
Labels: S:automerge

#6314 state: fix block event indexing reserved key check
  state/indexer/block/kv/kv.go
Labels: S:automerge, S:backport-to-v0.34.x

#6334 changelog: update to reflect 0.34.9
  CHANGELOG.md
  CHANGELOG_PENDING.md
Labels: S:automerge

#6344 docs: bump vuepress-theme-cosmos
  docs/package-lock.json
  docs/package.json
Labels: C:docs, S:automerge

#6346 light: handle too high errors correctly
  CHANGELOG_PENDING.md
  light/client.go
Labels: C:light, S:backport-to-v0.34.x

#6345 docs: remove RFC section and s/RFC001/ADR066
  CONTRIBUTING.md
  docs/architecture/README.md
  docs/architecture/adr-066-e2e-testing.md
  docs/rfc/README.md
Labels: S:automerge

#6347 e2e: tx load to use broadcast sync instead of commit
  test/e2e/runner/load.go
  test/e2e/tests/app_test.go
Labels: S:backport-to-v0.34.x

#6307 ADR 065: Custom Event Indexing
  docs/architecture/README.md
  docs/architecture/adr-065-custom-event-indexing.md
  docs/architecture/adr-template.md
Labels: C:docs

#6353 p2p: minor cleanup + update router options
  config/config.go
  config/toml.go
  docs/nodes/configuration.md
  node/node.go
  p2p/router.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: C:p2p

#6378 statesync: improve e2e test outcomes
  CHANGELOG_PENDING.md
  config/config.go
  statesync/reactor.go
  statesync/snapshots.go
  statesync/syncer.go
  statesync/syncer_test.go
  test/e2e/app/snapshots.go
Labels: S:automerge, S:backport-to-v0.34.x

#6375 evidence: fix bug with hashes
  CHANGELOG_PENDING.md
  evidence/pool.go
  evidence/pool_test.go
  evidence/verify.go
  evidence/verify_test.go
  p2p/shim.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/testnet.go
  test/e2e/runner/evidence.go
  test/e2e/tests/block_test.go
  types/evidence.go
  types/evidence_test.go
  types/light.go
  types/light_test.go
  types/validator_set.go
Labels: S:backport-to-v0.34.x

#6383 .github: make core team codeowners
  .github/CODEOWNERS
Labels: S:automerge

#6376 crypto: add sr25519 as a validator key
  CHANGELOG_PENDING.md
  abci/types/pubkey.go
  crypto/encoding/codec.go
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
  proto/tendermint/crypto/keys.pb.go
  proto/tendermint/crypto/keys.proto
  types/params.go
  types/params_test.go
Labels: C:crypto, S:automerge

#6390 statesync: fix unreliable test
  statesync/snapshots_test.go
Labels: S:automerge

#6408 types: Refactor EventAttribute
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/types/messages_test.go
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/tx/kv/kv.go
  state/indexer/tx/kv/kv_bench_test.go
  state/indexer/tx/kv/kv_test.go
  state/state_test.go
  test/e2e/app/app.go
  types/event_bus.go
  types/event_bus_test.go
Labels: C:abci, C:events, S:automerge
