Repository tendermint/tendermint, pull requests merged in 2021-03, with the labels that each got.

#6185 privval: return errors on loadFilePV
  CHANGELOG_PENDING.md
  cmd/priv_val_server/main.go
  cmd/tendermint/commands/init.go
  cmd/tendermint/commands/reset_priv_validator.go
  cmd/tendermint/commands/show_validator.go
  cmd/tendermint/commands/testnet.go
  consensus/replay_test.go
  privval/file.go
  privval/file_test.go
  test/e2e/app/main.go
  tools/tm-signer-harness/internal/test_harness.go
  tools/tm-signer-harness/main.go
Labels: S:automerge, T:ux, T:validator

#6188 test/fuzz: fix PEX reactor test
  .github/workflows/fuzz-nightly.yml
  p2p/pex/pex_reactor_test.go
  p2p/shim_test.go
  p2p/switch_test.go
  p2p/test_util.go
  rpc/core/net_test.go
  test/fuzz/p2p/pex/reactor_receive.go
Labels: S:automerge

#6183 changelog: update for 0.34.8
  CHANGELOG.md
  CHANGELOG_PENDING.md
Labels: S:automerge

#6191 rpc/jsonrpc: Unmarshal RPCRequest correctly
  CHANGELOG_PENDING.md
  rpc/jsonrpc/types/types.go
Labels: S:automerge, S:backport-to-v0.34.x

#6194 indexer: remove info log
  state/execution.go
  state/txindex/indexer_service.go
Labels: S:automerge, S:backport-to-v0.34.x

#6201 mempool & rpc log grooming
  mempool/reactor.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_server.go
  test/e2e/runner/rpc.go
Labels: S:backport-to-v0.34.x

#6198 logs: cleanup
  consensus/state.go
  mempool/clist_mempool.go
  p2p/shim.go
  rpc/jsonrpc/server/http_json_handler.go
Labels: S:backport-to-v0.34.x

#6210 e2e: add benchmarking functionality
  test/e2e/README.md
  test/e2e/runner/benchmark.go
  test/e2e/runner/main.go
  test/e2e/runner/wait.go
Labels: S:backport-to-v0.34.x

#6209 localnet: fix localnet by excluding self from persistent peers list
  cmd/tendermint/commands/testnet.go
Labels: S:automerge

#6196 e2e: integrate light clients
  cmd/tendermint/commands/light.go
  light/client.go
  light/proxy/proxy.go
  light/rpc/client.go
  test/e2e/app/config.go
  test/e2e/app/main.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/networks/simple.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  test/e2e/runner/start.go
  test/e2e/tests/app_test.go
Labels: S:backport-to-v0.34.x

#6214 update outdated comment in state.go
  state/state.go
Labels: S:automerge

#6213 build with go1.16
  .github/workflows/coverage.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e-nightly-master.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: S:automerge, S:backport-to-v0.34.x

#6212 blockstore: save only the last seen commit
  store/store.go
  store/store_test.go
Labels: S:backport-to-v0.34.x

#6220 note: add nondeterministic note to events
  proto/tendermint/abci/types.proto
  types/block.go
Labels: S:automerge, S:backport-to-v0.34.x

#6204 rpc/jsonrpc/server: return an error in WriteRPCResponseHTTP(Error)
  CHANGELOG_PENDING.md
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/http_uri_handler.go
Labels: S:backport-to-v0.34.x

#6237 consensus: use errors.Is in checking vote error
  consensus/state.go
Labels: S:backport-to-v0.34.x

#6120 crypto: ed25519 & sr25519 batch verification
  CHANGELOG_PENDING.md
  crypto/batch/batch.go
  crypto/crypto.go
  crypto/ed25519/bench_test.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/ed25519_test.go
  crypto/sr25519/batch.go
  crypto/sr25519/bench_test.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  crypto/sr25519/sr25519_test.go
  go.mod
  go.sum
  types/validator_set.go
  types/validator_set_test.go
Labels: C:crypto

#6240 privval: add ctx to privval interface
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/init.go
  cmd/tendermint/commands/root.go
  cmd/tendermint/commands/show_validator.go
  cmd/tendermint/commands/testnet.go
  config/config.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/invalid_test.go
  consensus/msgs_test.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state.go
  consensus/state_test.go
  consensus/types/height_vote_set_test.go
  evidence/pool_test.go
  evidence/verify_test.go
  node/node.go
  privval/file.go
  privval/file_test.go
  privval/grpc/client.go
  privval/grpc/client_test.go
  privval/grpc/server.go
  privval/grpc/server_test.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_requestHandler.go
  privval/signer_server.go
  state/state_test.go
  state/validation_test.go
  tools/tm-signer-harness/internal/test_harness.go
  types/block_test.go
  types/evidence.go
  types/evidence_test.go
  types/priv_validator.go
  types/proposal_test.go
  types/test_util.go
  types/validator.go
  types/validator_set_test.go
  types/validator_test.go
  types/vote_set_test.go
  types/vote_test.go
Labels: S:automerge, T:breaking

#6226 rpc: index block events to support block event queries
  CHANGELOG_PENDING.md
  docs/app-dev/indexing-transactions.md
  light/proxy/routes.go
  light/rpc/client.go
  node/node.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mocks/client.go
  rpc/core/blocks.go
  rpc/core/env.go
  rpc/core/routes.go
  rpc/core/tx.go
  rpc/core/types/responses.go
  rpc/openapi/openapi.yaml
  state/indexer/block.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/indexer/block/null/null.go
  state/indexer/query_range.go
  state/txindex/indexer.go
  state/txindex/indexer_service.go
  state/txindex/indexer_service_test.go
  state/txindex/kv/kv.go
  test/e2e/app/app.go
  types/events.go
Labels: C:rpc, S:backport-to-v0.34.x

#6263 state: cleanup block indexing logs and null
  state/indexer/block/null/null.go
  state/txindex/indexer_service.go
Labels: C:state, S:automerge

#6273 github: add @tychoish to code owners
  .github/CODEOWNERS
Labels: S:automerge

#6272 e2e: fix perturbation of seed nodes
  test/e2e/networks/ci.toml
  test/e2e/runner/perturb.go
Labels: T:test

#6270 logging: shorten precommit log message
  consensus/state.go
  types/block.go
  types/vote_set.go
Labels: S:automerge, S:backport-to-v0.34.x

#6275 p2p test infra: make memory network test buffers configurable
  blockchain/v0/reactor_test.go
  consensus/reactor_test.go
  evidence/reactor_test.go
  mempool/reactor_test.go
  p2p/p2ptest/network.go
  p2p/router_test.go
  p2p/transport_memory.go
  p2p/transport_memory_test.go
Labels: C:p2p, T:test

#6126 p2p: revised router message scheduling
  blockchain/v0/reactor.go
  consensus/reactor.go
  evidence/reactor.go
  mempool/reactor.go
  mempool/reactor_test.go
  node/node.go
  p2p/conn/connection.go
  p2p/metrics.go
  p2p/p2ptest/network.go
  p2p/pex/pex_reactor.go
  p2p/pqueue.go
  p2p/queue.go
  p2p/router.go
  p2p/router_init_test.go
  p2p/router_test.go
  p2p/wdrr_queue.go
  p2p/wdrr_queue_test.go
  statesync/reactor.go
  test/e2e/docker/Dockerfile
  test/e2e/runner/load.go
  test/e2e/runner/main.go
  test/e2e/runner/setup.go
Labels: C:p2p

#6278 p2p: metrics
  p2p/metrics.go
  p2p/pqueue.go
  p2p/router.go
  p2p/wdrr_queue.go
Labels: C:p2p, S:automerge

#6264 fix: jsonrpc url parsing and dial function
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/http_json_client_test.go
Labels: C:rpc, S:automerge, S:backport-to-v0.34.x

#6292 ci: add janitor
  .github/workflows/janitor.yml
  .github/workflows/tests.yml
Labels: S:automerge, S:backport-to-v0.34.x

#6286 p2p: rate-limit incoming connections by IP
  p2p/conn_tracker.go
  p2p/conn_tracker_test.go
  p2p/router.go
  p2p/router_test.go
Labels: C:p2p

#6300 p2p: filter peers by IP address and ID
  node/node.go
  p2p/router.go
  p2p/router_filter_test.go
Labels: C:p2p
