Repository tendermint/tendermint, pull requests merged in 2021-11, with the labels that each got.

#7198 pex: allow disabled pex reactor
  node/node.go
Labels: S:automerge, S:backport-to-v0.35.x

#7204 ci: update dependabot configuration
  .github/dependabot.yml
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7226 ci: backport lint changes to v0.35
  .github/workflows/lint.yml
  .github/workflows/linter.yml
  .golangci.yml
Labels: S:automerge

#7190 Fix spurious crasher in mempool fuzz test.
  test/fuzz/mempool/checktx.go
Labels: S:backport-to-v0.35.x

#7227 doc: Set up Dependabot on new backport branches.
  RELEASES.md
Labels: S:automerge

#7225 ci: backport recent changes to lint configuration to 0.34
  .github/workflows/lint.yml
  .github/workflows/linter.yml
  .golangci.yml
Labels: S:automerge

#7229 codeowners: backport master code owners to 0.34.x
  .github/CODEOWNERS
Labels: S:automerge

#7239 pex: avoid starting reactor twice
  node/node.go
Labels: S:automerge

#7237 lint: cleanup pending lint errors
  .golangci.yml
  abci/types/result.go
  consensus/reactor.go
  consensus/wal_fuzz.go
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_nocgo.go
  crypto/secp256k1/secp256k1_test.go
  crypto/xchacha20poly1305/xchachapoly_test.go
  libs/bytes/bytes.go
  libs/events/event_cache_test.go
  libs/json/helpers_test.go
  libs/protoio/io_test.go
  libs/pubsub/subscription.go
  libs/sync/deadlock.go
  libs/sync/sync.go
  light/store/db/db.go
  node/node_test.go
  p2p/conn/conn_go110.go
  p2p/conn/conn_notgo110.go
  p2p/conn/secret_connection_test.go
  p2p/netaddress.go
  privval/socket_listeners.go
  rpc/client/helpers.go
  rpc/jsonrpc/client/integration_test.go
  rpc/jsonrpc/types/types.go
  state/state.go
  state/state_test.go
  state/store.go
  state/txindex/indexer_service.go
  state/validation_test.go
  test/e2e/app/state.go
  types/event_bus.go
  types/genesis_test.go
  types/signable.go
  types/validator_set_test.go
Labels: S:automerge

#7241 docs: add upgrading info about node service
  UPGRADING.md
Labels: S:automerge, S:backport-to-v0.35.x

#7243 Update master changelog after v0.35.0 tag.
  CHANGELOG.md
Labels: S:automerge

#7245 Remove unused libs/cmap.
  libs/cmap/cmap.go
  libs/cmap/cmap_test.go
Labels: S:automerge

#7248 Fix ToC entry for RFC 006.
  docs/rfc/README.md
Labels: S:automerge

#7253 consensus: add some more checks to vote counting
  internal/consensus/peer_state.go
  types/vote_set.go
Labels: S:backport-to-v0.35.x

#7263 Set a cap on the length of subscription queries.
  internal/rpc/core/events.go
  internal/rpc/core/tx.go
Labels: S:backport-to-v0.35.x

#7170 state: add an 'IsTimely' method to implement the 'timely' check for proposer-based timestamps
  libs/time/mocks/source.go
  libs/time/time.go
  types/params.go
  types/proposal.go
  types/proposal_test.go
Labels: S:automerge

#7266 evidence: remove source of non-determinism from test
  internal/evidence/reactor_test.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7265 p2p: reduce peer score for dial failures
  CHANGELOG_PENDING.md
  internal/p2p/peermanager.go
Labels: S:automerge, S:backport-to-v0.35.x

#7283 node+consensus: handshaker initialization
  cmd/tendermint/commands/replay.go
  internal/consensus/replay.go
  internal/consensus/replay_file.go
  internal/consensus/replay_test.go
  node/node.go
  node/setup.go
Labels: S:automerge

#7284 libs/os: remove arbitrary os.Exit
  internal/consensus/replay_file.go
  internal/state/store.go
  libs/os/os.go
  rpc/jsonrpc/test/main.go
Labels: S:automerge

#7269 proto: update the mechanism for generating protos from spec repo
  .github/workflows/proto-docker.yml
  Makefile
  buf.gen.yaml
  buf.yaml
  scripts/protocgen.sh
  scripts/protopackage.sh
  tools/proto/Dockerfile
Labels: S:automerge

#6915 PrepareProposal-VoteExtension integration
  abci/types/types.pb.go
  internal/consensus/byzantine_test.go
  internal/consensus/state.go
  node/node_test.go
  proto/tendermint/abci/types.proto
  state/execution.go
  types/block.go
  types/vote.go
  types/vote_set.go
Labels: C:abci

#7289 docs: clarify where doc site config settings must land
  RELEASES.md
  docs/DOCS_README.md
Labels: S:automerge

#7291 proto: rebuild the proto files from the spec repository
  .github/workflows/proto.yml
  Makefile
  abci/types/types.pb.go
  proto/tendermint/blocksync/types.pb.go
  proto/tendermint/consensus/types.pb.go
  proto/tendermint/consensus/wal.pb.go
  proto/tendermint/crypto/keys.pb.go
  proto/tendermint/crypto/keys.proto
  proto/tendermint/crypto/proof.pb.go
  proto/tendermint/crypto/proof.proto
  proto/tendermint/libs/bits/types.pb.go
  proto/tendermint/libs/bits/types.proto
  proto/tendermint/mempool/types.pb.go
  proto/tendermint/p2p/conn.pb.go
  proto/tendermint/p2p/pex.pb.go
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/privval/service.proto
  proto/tendermint/privval/types.pb.go
  proto/tendermint/state/types.pb.go
  proto/tendermint/statesync/types.pb.go
  proto/tendermint/types/block.pb.go
  proto/tendermint/types/canonical.pb.go
  proto/tendermint/types/events.pb.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/params.pb.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/validator.pb.go
  proto/tendermint/version/types.pb.go
  proto/tendermint/version/types.proto
Labels: S:automerge

#7296 build: update location of proto builder image
  Makefile
Labels: S:automerge, S:backport-to-v0.35.x

#7311 docs: add abci timing metrics to the metrics docs
  docs/nodes/metrics.md
Labels: S:automerge

#7309 pubsub: Report a non-nil error when shutting down.
  CHANGELOG_PENDING.md
  libs/pubsub/pubsub.go
Labels: S:automerge

#7310 pubsub: Report a non-nil error when shutting down.
  CHANGELOG_PENDING.md
  libs/pubsub/pubsub.go
Labels: S:automerge

#7318 Update example code in OpenAPI docs.
  rpc/openapi/openapi.yaml
Labels: S:backport-to-v0.35.x

#7330 docs: go tutorial fixed for 0.35.0 version (#7329)
  docs/tutorials/go.md
Labels: S:backport-to-v0.35.x

#7339 Add pending change log entry for #7319.
  CHANGELOG_PENDING.md
Labels: S:automerge

#7337 eventbus: plumb contexts
  internal/blocksync/reactor.go
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_file.go
  internal/consensus/replay_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
  internal/consensus/wal_generator.go
  internal/eventbus/event_bus.go
  internal/eventbus/event_bus_test.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  internal/state/indexer/indexer_service_test.go
  internal/state/validation_test.go
  node/node.go
  node/setup.go
  types/events.go
Labels: S:automerge

#7345 e2e: control access to state in Info calls
  test/e2e/app/app.go
Labels: S:automerge

#7347 e2e: more clear height test
  test/e2e/tests/app_test.go
Labels: S:automerge

#7343 pex: improve goroutine lifecycle
  internal/p2p/pex/reactor.go
Labels: S:automerge

#7340 e2e: stabilize validator update form
  test/e2e/app/app.go
Labels: S:automerge, S:backport-to-v0.35.x

#7348 e2e: clarify apphash reporting
  test/e2e/tests/app_test.go
Labels: S:automerge, S:backport-to-v0.35.x

#7344 e2e: generate keys for more stable load
  test/e2e/runner/load.go
Labels: S:automerge, S:backport-to-v0.35.x

#7356 Remove now-unused nolint:lll directives.
  config/config_test.go
  internal/consensus/msgs_test.go
  internal/evidence/reactor_test.go
  internal/inspect/inspect.go
  internal/inspect/rpc/rpc.go
  internal/p2p/conn/connection_test.go
  internal/p2p/metrics.go
  internal/rpc/core/mempool.go
  internal/state/indexer/sink/sink.go
  libs/pubsub/query/query_test.go
  light/proxy/routes.go
  light/rpc/client.go
  privval/msgs_test.go
  proto/tendermint/blocksync/message_test.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  types/proposal_test.go
  types/vote_test.go
Labels: S:automerge, S:backport-to-v0.35.x
