Repository tendermint/tendermint, pull requests merged in 2021-05, with the labels that each got.

#6428 libs/os: avoid CopyFile truncating destination before checking if regular file
  libs/os/os.go
  libs/os/os_test.go
Labels: S:backport-to-v0.34.x

#6465 adr 067: updates
  docs/architecture/README.md
  docs/architecture/adr-067-mempool-refactor.md
Labels: C:docs, S:automerge

#6469 consensus: add test vector for hasvote
  proto/tendermint/consensus/message_test.go
Labels: S:automerge

#6445 rpc: add chunked rpc interface
  light/proxy/routes.go
  light/rpc/client.go
  node/node.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mocks/client.go
  rpc/client/rpc_test.go
  rpc/core/env.go
  rpc/core/net.go
  rpc/core/routes.go
  rpc/core/types/responses.go
Labels: C:rpc

#6453 libs/clist: fix flaky tests
  libs/clist/clist_test.go
Labels: S:automerge, T:test

#6493 Readme Introduction Reframed for better clarity
  README.md
Labels: S:automerge

#6490 config: Add private peer id /net_info expose information in default config
  config/toml.go
Labels: C:docs, S:automerge

#6478 events: Add block_id to NewBlockEvent
  CHANGELOG_PENDING.md
  state/execution.go
  types/event_bus_test.go
  types/events.go
Labels: S:automerge

#6494 version: revert version through ldflag only
  CHANGELOG_PENDING.md
  CONTRIBUTING.md
  Makefile
  cmd/tendermint/commands/version.go
  node/setup.go
  proxy/version.go
  state/state.go
  statesync/syncer_test.go
  tools/tm-signer-harness/main.go
  version/version.go
Labels: S:automerge, S:backport-to-v0.34.x

#6503 libs/log: use fmt.Fprintf directly with *bytes.Buffer to avoid unnecessary allocations
  libs/log/tmfmt_logger.go
Labels: S:automerge

#6462 config: seperate priv validator config into seperate section
  CHANGELOG_PENDING.md
  UPGRADING.md
  cmd/tendermint/commands/run_node.go
  cmd/tendermint/commands/show_validator.go
  cmd/tendermint/commands/testnet.go
  config/config.go
  config/toml.go
  config/toml_test.go
  node/node.go
  node/node_test.go
  privval/grpc/util.go
  test/e2e/runner/setup.go
Labels: S:automerge
