Repository tendermint/tendermint, pull requests merged in 2021-01, with the labels that each got.

#5850 tools/tm-signer-harness: fix listener leak in newTestHarnessListener()
  tools/tm-signer-harness/internal/test_harness.go
Labels: S:automerge

#5849 abci/grpc: fix invalid mutex handling in StopForError()
  abci/client/grpc_client.go
Labels: S:automerge

#5852 libs/os: EnsureDir now returns IO errors and checks file type
  CHANGELOG_PENDING.md
  libs/os/os.go
  libs/os/os_test.go
Labels: S:automerge

#5853 p2p: fix IPv6 address handling in new transport API
  p2p/transport.go
  p2p/transport_mconn.go
Labels: S:automerge

#5854 test/e2e: disable abci/grpc and blockchain/v2 due to flake
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
Labels: S:automerge

#5857 test/e2e: add conceptual overview
  test/e2e/README.md
Labels: S:automerge

#5861 test/consensus: improve WaitGroup handling in Byzantine tests
  consensus/byzantine_test.go
Labels: S:automerge

#5862 blockchain/v2: fix missing mutex unlock
  blockchain/v2/reactor.go
Labels: S:automerge

#5860 blockchain/v0: stop tickers on poolRoutine exit
  blockchain/v0/reactor.go
Labels: S:automerge

#5771 store: order-preserving varint key encoding
  CHANGELOG_PENDING.md
  evidence/pool.go
  go.mod
  go.sum
  light/store/db/db.go
  light/store/db/db_test.go
  state/store.go
  store/store.go
  store/store_test.go
Labels: T:breaking, T:perf

#5870 p2p: fix MConnection inbound traffic statistics and rate limiting
  CHANGELOG_PENDING.md
  libs/protoio/io.go
  libs/protoio/io_test.go
  libs/protoio/reader.go
  p2p/conn/connection.go
  p2p/conn/connection_test.go
  p2p/conn/secret_connection.go
  p2p/transport.go
  p2p/transport_test.go
  privval/signer_endpoint.go
Labels: S:backport

#5871 os: simplify EnsureDir()
  libs/os/os.go
Labels: S:automerge

#5747 evidence: p2p refactor
  consensus/byzantine_test.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/reactor_test.go
  evidence/verify.go
  evidence/verify_test.go
  node/node.go
  node/node_test.go
  p2p/key.go
  p2p/key_test.go
  p2p/netaddress.go
  p2p/peer.go
  p2p/shim.go
  p2p/shim_test.go
  statesync/reactor.go
  statesync/reactor_test.go
  test/maverick/node/node.go
Labels: C:evidence

#5725 privval: add grpc
  CHANGELOG_PENDING.md
  Makefile
  cmd/priv_val_server/main.go
  config/config.go
  config/toml.go
  docs/nodes/remote_signer.md
  go.mod
  go.sum
  libs/net/net_test.go
  node/node.go
  node/utils.go
  privval/grpc/client.go
  privval/grpc/client_test.go
  privval/grpc/server.go
  privval/grpc/server_test.go
  privval/grpc/util.go
  proto/tendermint/privval/service.pb.go
  proto/tendermint/privval/service.proto
  test/e2e/app/main.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  types/priv_validator.go
Labels: T:validator

#5878 test/e2e: tolerate up to 2/3 missed signatures for a validator
  test/e2e/tests/validator_test.go
Labels: S:automerge

#5831 p2p: add Router prototype
  p2p/channel.go
  p2p/peer.go
  p2p/queue.go
  p2p/router.go
  p2p/router_test.go
  p2p/transport.go
Labels: C:p2p, S:automerge

#5876 privval: Query validator key
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/show_validator.go
  node/node.go
  privval/grpc/util.go
Labels: S:automerge, T:validator

#5913 .github/codeowners: add alexanderbez
  .github/CODEOWNERS
Labels: S:automerge

#5886 proto: bump gogoproto (1.3.2)
  abci/types/types.pb.go
  go.mod
  go.sum
  proto/tendermint/blockchain/types.pb.go
  proto/tendermint/consensus/types.pb.go
  proto/tendermint/consensus/wal.pb.go
  proto/tendermint/crypto/keys.pb.go
  proto/tendermint/crypto/proof.pb.go
  proto/tendermint/libs/bits/types.pb.go
  proto/tendermint/mempool/types.pb.go
  proto/tendermint/p2p/conn.pb.go
  proto/tendermint/p2p/pex.pb.go
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/privval/types.pb.go
  proto/tendermint/state/types.pb.go
  proto/tendermint/statesync/types.pb.go
  proto/tendermint/types/block.pb.go
  proto/tendermint/types/canonical.pb.go
  proto/tendermint/types/events.pb.go
  proto/tendermint/types/evidence.pb.go
  proto/tendermint/types/params.pb.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/validator.pb.go
  proto/tendermint/version/types.pb.go
  rpc/grpc/types.pb.go
Labels: S:automerge

#5914 config: fix mispellings
  config/config.go
  config/toml.go
  docs/nodes/configuration.md
Labels: S:automerge

#5916 readme: add security mailing list
  README.md
Labels: S:automerge

#5882 p2p: add prototype peer lifecycle manager
  p2p/peer.go
  p2p/router.go
  p2p/router_test.go
Labels: S:automerge

#5858 blockchain v0: p2p refactor
  blockchain/msgs.go
  blockchain/v0/pool.go
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  blockchain/v0/test_util.go
  blockchain/v2/io.go
  blockchain/v2/reactor.go
  blockchain/v2/reactor_test.go
  node/node.go
  proto/tendermint/blockchain/message.go
  proto/tendermint/blockchain/message_test.go
  proto/tendermint/statesync/message.go
  statesync/reactor.go
  test/maverick/node/node.go
Labels: C:p2p, C:sync

#5927 changelog: update changelog for v0.34.3
  CHANGELOG.md
Labels: S:automerge

#5906 e2e: releases nightly
  .github/workflows/e2e-nightly.yml
Labels: S:automerge, T:test

#5940 p2p: revise shim log levels
  p2p/shim.go
Labels: C:p2p, S:automerge

#5936 p2p: improve PeerManager prototype
  p2p/peer.go
  p2p/router.go
  p2p/router_test.go
Labels: C:p2p, S:automerge

#5919 mempool: p2p refactor
  blockchain/v0/reactor.go
  evidence/reactor.go
  libs/sync/deadlock.go
  libs/sync/sync.go
  mempool/ids.go
  mempool/reactor.go
  mempool/reactor_test.go
  node/node.go
  proto/tendermint/blockchain/message.go
  proto/tendermint/mempool/message.go
  statesync/reactor.go
  test/maverick/node/node.go
Labels: C:mempool, C:p2p

#5948 docs: package-lock.json fix
  docs/.vuepress/config.js
  docs/package-lock.json
Labels: C:docs

#5946 docs: bump vuepress theme
  docs/.vuepress/config.js
  docs/.vuepress/styles/index.styl
  docs/architecture/adr-056-proving-amnesia-attacks.md
  docs/package-lock.json
  docs/package.json
Labels: C:docs, S:automerge

#5949 docs: vuepress version update
  docs/.vuepress/config.js
  docs/package-lock.json
  docs/package.json
Labels: C:docs

#5950 docs: change v0.33 version
  docs/versions
Labels: C:docs, S:automerge

#5953 Makefile: always pull image in proto-gen-docker.
  Makefile
Labels: S:automerge

#5955 test: fix TestPEXReactorRunning data race
  p2p/pex/pex_reactor_test.go
Labels: S:automerge, T:test

#5947 p2p: make PeerManager.DialNext() and EvictNext() block
  p2p/peer.go
  p2p/router.go
  p2p/router_test.go
  p2p/transport_mconn.go
Labels: C:p2p, S:automerge

#5945 docs: log level docs
  docs/nodes/README.md
  docs/nodes/configuration.md
  docs/nodes/logging.md
  docs/tendermint-core/how-to-read-logs.md
  docs/tendermint-core/running-in-production.md
Labels: C:docs, S:automerge, T:code-hygiene

#5965 .github: fix fuzz-nightly job
  .github/workflows/fuzz-nightly.yml
Labels: S:automerge

#5967 mempool: fix reactor tests
  mempool/reactor_test.go
Labels: C:mempool, C:p2p, S:automerge

#5954 p2p: improve peerStore prototype
  mempool/reactor.go
  node/node.go
  p2p/peer.go
  p2p/router.go
  p2p/router_test.go
  p2p/transport.go
  p2p/transport_memory.go
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/p2p/types.proto
  test/maverick/node/node.go
Labels: C:p2p, S:automerge

#5962 p2p: simplify PeerManager upgrade logic
  p2p/peer.go
Labels: C:p2p, S:automerge

#5957 p2p: add PeerManager.Advertise()
  p2p/peer.go
  p2p/router.go
Labels: C:p2p, S:automerge

#5970 blockchain v0: fix waitgroup data race
  blockchain/v0/reactor.go
Labels: C:sync, S:automerge, T:test

#5966 tests: fix `make test`
  go.mod
  go.sum
Labels: S:automerge, T:test

#5973 terminate go-fuzz gracefully (w/ SIGINT)
  .github/workflows/fuzz-nightly.yml
Labels: S:automerge

#5971 p2p: add prototype PEX reactor for new stack
  p2p/peer.go
  p2p/pex/reactor.go
  proto/tendermint/p2p/pex.go
Labels: C:p2p, S:automerge

#5974 proto/p2p: rename PEX messages and fields
  p2p/netaddress.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
  p2p/pex/reactor.go
  proto/tendermint/p2p/pex.go
  proto/tendermint/p2p/pex.pb.go
  proto/tendermint/p2p/pex.proto
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/p2p/types.proto
  test/fuzz/p2p/pex/init-corpus/main.go
Labels: C:p2p

#5980 p2p: resolve PEX addresses in PEX reactor
  p2p/netaddress.go
  p2p/peer.go
  p2p/pex/reactor.go
Labels: C:p2p, S:automerge

#5982 test/p2p: close transports to avoid goroutine leak failures
  p2p/router_test.go
Labels: S:automerge, T:test

#5984 mempool: fix TestReactorNoBroadcastToSender
  mempool/reactor.go
  mempool/reactor_test.go
Labels: C:mempool, S:automerge, T:test

#5988 mempool: really fix mempool tests timeout
  mempool/reactor.go
  mempool/reactor_test.go
Labels: C:mempool, S:automerge, T:test

#5983 p2p: use stopCtx for Router.dialPeer()
  p2p/router.go
Labels: C:p2p, S:automerge

#5979 CONTRIBUTING.md: update testing section
  CONTRIBUTING.md
  test/Makefile
Labels: C:docs, S:automerge

#5997 test: don't use foo-bar.net in TestHTTPClientMakeHTTPDialer
  rpc/jsonrpc/client/http_json_client_test.go
Labels: S:automerge

#6000 test: fix TestSwitchAcceptRoutine flake by ignoring error type
  p2p/switch_test.go
Labels: S:automerge, T:test

#5996 test: disable TestPEXReactorSeedModeFlushStop due to flake
  p2p/pex/pex_reactor_test.go
Labels: S:automerge

#5994 proto: seperate native and proto types
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/init.go
  cmd/tendermint/commands/testnet.go
  consensus/replay.go
  consensus/replay_test.go
  evidence/pool_test.go
  evidence/verify_test.go
  light/helpers_test.go
  light/rpc/client.go
  light/store/db/db_test.go
  rpc/core/consensus.go
  rpc/core/types/responses.go
  state/execution.go
  state/execution_test.go
  state/export_test.go
  state/helpers_test.go
  state/state.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/validation.go
  statesync/stateprovider.go
  statesync/syncer_test.go
  store/store_test.go
  test/maverick/consensus/replay.go
  test/maverick/main.go
  types/block.go
  types/block_test.go
  types/evidence_test.go
  types/genesis.go
  types/light_test.go
  types/params.go
  types/params_test.go
  types/protobuf.go
  types/protobuf_test.go
  version/version.go
Labels: C:state, S:automerge, T:code-hygiene

#5917 consensus: Groom Logs
  cmd/tendermint/commands/root.go
  config/config.go
  consensus/state.go
  test/e2e/app/main.go
  test/e2e/runner/setup.go
  test/maverick/consensus/misbehavior.go
  test/maverick/consensus/state.go
  test/maverick/main.go
Labels: S:automerge, T:code-hygiene, T:observability

#5995 test: fix test data race in p2p.MemoryTransport with logger
  p2p/transport_memory.go
Labels: S:automerge

#6001 test: fix TestSwitchAcceptRoutine by ignoring spurious error
  p2p/switch_test.go
Labels: S:automerge

#6002 test: fix TestRouter to take into account PeerManager reconnects
  p2p/router_test.go
Labels: S:automerge, T:test

#6006 test: fix flaky router broadcast test
  p2p/router.go
  p2p/router_test.go
Labels: C:p2p, S:automerge

#5987 params: remove blockTimeIota
  CHANGELOG_PENDING.md
  abci/client/mocks/client.go
  abci/types/types.pb.go
  consensus/replay.go
  evidence/mocks/block_store.go
  p2p/conn/secret_connection.go
  p2p/mocks/peer.go
  privval/secret_connection.go
  proto/tendermint/abci/types.proto
  proto/tendermint/types/params.pb.go
  proto/tendermint/types/params.proto
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  rpc/core/consensus.go
  rpc/core/types/responses.go
  state/helpers_test.go
  state/mocks/evidence_pool.go
  state/mocks/store.go
  state/state_test.go
  state/store.go
  state/store_test.go
  statesync/mocks/state_provider.go
  test/maverick/consensus/replay.go
  test/maverick/consensus/state.go
  types/params.go
  types/params_test.go
  types/protobuf.go
  types/protobuf_test.go
Labels: S:automerge, T:breaking, T:code-hygiene

#6003 test/e2e: enable pprof server to help debugging failures
  test/e2e/README.md
  test/e2e/docker/Dockerfile
  test/e2e/runner/setup.go
Labels: S:automerge

#6014 blockchain v0: skip TestReactor_BadBlockStopsPeer
  blockchain/v0/reactor_test.go
Labels: C:sync, S:automerge

#6015 sync: move closer to separate file
  libs/sync/closer.go
  libs/sync/closer_test.go
  libs/sync/deadlock.go
  libs/sync/sync.go
Labels: S:automerge

#6017 p2p: clean up new Transport infrastructure
  node/node.go
  p2p/netaddress.go
  p2p/peer.go
  p2p/peer_test.go
  p2p/pex/reactor.go
  p2p/router.go
  p2p/router_test.go
  p2p/switch.go
  p2p/switch_test.go
  p2p/test_util.go
  p2p/transport.go
  p2p/transport_mconn.go
  p2p/transport_memory.go
  p2p/transport_memory_test.go
  test/maverick/node/node.go
Labels: C:p2p, S:automerge
