Repository tendermint/tendermint, pull requests merged in 2021-02, with the labels that each got.

#6020 p2p: tighten up and test Transport API
  mempool/reactor_test.go
  p2p/key.go
  p2p/peer.go
  p2p/router.go
  p2p/router_test.go
  p2p/switch.go
  p2p/switch_test.go
  p2p/transport.go
  p2p/transport_mconn.go
  p2p/transport_mconn_test.go
  p2p/transport_memory.go
  p2p/transport_memory_test.go
  p2p/transport_test.go
Labels: C:p2p, S:automerge

#6021 p2p: add tests and fix bugs for `NodeAddress` and `NodeID`
  p2p/address.go
  p2p/address_test.go
  p2p/key.go
  p2p/key_test.go
  p2p/peer.go
  p2p/pex/reactor.go
  p2p/router.go
  p2p/router_test.go
  p2p/transport.go
  p2p/transport_mconn.go
  p2p/transport_test.go
Labels: C:p2p, S:automerge, T:test

#6022 light/provider/http: fix Validators
  CHANGELOG_PENDING.md
  light/provider/http/http.go
  rpc/client/http/http.go
  rpc/client/rpc_test.go
  types/validator_set.go
Labels: S:automerge

#6023 types: cleanup protobuf.go
  CHANGELOG_PENDING.md
  state/helpers_test.go
  state/state_test.go
  types/params.go
  types/protobuf.go
  types/protobuf_test.go
Labels: S:automerge, T:code-hygiene

#6029 goreleaser: downcase archive and binary names
  .goreleaser.yml
Labels: S:automerge

#6033 test/e2e: increase sign/propose tolerances
  test/e2e/tests/validator_test.go
Labels: S:automerge, T:test

#6037 test/e2e: increase validator tolerances
  test/e2e/tests/validator_test.go
Labels: S:automerge, T:test

#6035 docs: external address
  docs/nodes/configuration.md
Labels: C:docs, S:automerge

#6039 docs: reword configuration
  docs/nodes/configuration.md
Labels: C:docs, S:automerge

#6034 p2p: tighten up and test PeerManager
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  evidence/reactor.go
  evidence/reactor_test.go
  libs/sync/waker.go
  libs/sync/waker_test.go
  mempool/reactor.go
  mempool/reactor_test.go
  p2p/address.go
  p2p/address_test.go
  p2p/channel.go
  p2p/peer.go
  p2p/peermanager.go
  p2p/peermanager_test.go
  p2p/pex/reactor.go
  p2p/router.go
  p2p/router_test.go
  p2p/shim.go
  p2p/shim_test.go
  statesync/reactor.go
  statesync/reactor_test.go
Labels: C:p2p, S:automerge, T:test

#6044 p2p: tighten up Router and add tests
  blockchain/v0/reactor.go
  evidence/reactor.go
  mempool/reactor.go
  node/node.go
  p2p/channel.go
  p2p/mocks/connection.go
  p2p/mocks/transport.go
  p2p/p2p_test.go
  p2p/p2ptest/network.go
  p2p/p2ptest/require.go
  p2p/p2ptest/util.go
  p2p/peermanager.go
  p2p/peermanager_test.go
  p2p/pex/reactor.go
  p2p/router.go
  p2p/router_test.go
  p2p/shim.go
  p2p/shim_test.go
  p2p/transport.go
  p2p/transport_test.go
  statesync/reactor.go
  test/maverick/node/node.go
Labels: C:p2p, S:automerge, T:test

#6047 tests: backport TestHTTPClientMakeHTTPDialer fix
  rpc/jsonrpc/client/http_json_client_test.go
Labels: S:backport

#6024 light/provider/http: fix Validators
  CHANGELOG_PENDING.md
  light/provider/http/http.go
  types/validator_set.go
Labels: S:automerge, S:backport

#6050 .github: clean up PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S:automerge

#6040 light: fix `/commit` and `/validators` rpc calls
  CHANGELOG_PENDING.md
  light/provider/http/http.go
  light/rpc/client.go
  light/rpc/mocks/light_client.go
Labels: S:backport

#6051 ADR-062: update with new P2P core implementation
  docs/architecture/adr-062-p2p-architecture.md
  docs/architecture/img/adr-062-architecture.svg
Labels: C:docs, C:p2p

#6052 maverick: reduce some duplication
  test/maverick/consensus/metrics.go
  test/maverick/consensus/misbehavior.go
  test/maverick/consensus/msgs.go
  test/maverick/consensus/reactor.go
  test/maverick/consensus/replay.go
  test/maverick/consensus/replay_file.go
  test/maverick/consensus/state.go
  test/maverick/consensus/wal.go
  test/maverick/consensus/wal_fuzz.go
  test/maverick/consensus/wal_generator.go
  test/maverick/node/node.go
Labels: C:consensus, S:automerge

#6060 .github: use job ID (not step ID) inside if condition
  .github/workflows/fuzz-nightly.yml
Labels: S:automerge

#6065 light: remove witnesses in order of decreasing index (#6058)
  light/client.go
  light/detector.go
Labels: S:backport

#6074 test: don't use foo-bar.net in TestHTTPClientMakeHTTPDialer (#5997)
  rpc/jsonrpc/client/http_json_client_test.go
Labels: S:backport

#6102 tooling: remove tools/Makefile
  CONTRIBUTING.md
  Makefile
  docs/app-dev/abci-cli.md
  docs/app-dev/getting-started.md
  docs/introduction/install.md
  tools/Makefile
Labels: S:needs-backport

#6108 changelog: update 0.34.3 changelog with details on security vuln
  CHANGELOG.md
Labels: S:backport-to-v0.34.x

#6069 evidence: terminate broadcastEvidenceRoutine when peer is stopped
  CHANGELOG_PENDING.md
  evidence/reactor.go
Labels: S:automerge, S:backport

#6112 docs/tutorials: fix proto file names
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
  docs/tutorials/java.md
  docs/tutorials/kotlin.md
Labels: C:docs, S:automerge

#6008 adr: batch verification
  docs/architecture/adr-064-batch-verification.md
Labels: C:docs

#6101 lint: update and appease the linter
  .github/workflows/lint.yaml
  .golangci.yml
  abci/example/kvstore/persistent_kvstore.go
  abci/tests/test_app/main.go
  abci/types/util.go
  blockchain/v0/pool.go
  blockchain/v0/pool_test.go
  blockchain/v0/reactor.go
  blockchain/v0/reactor_test.go
  blockchain/v1/reactor.go
  blockchain/v1/reactor_fsm.go
  blockchain/v1/reactor_test.go
  blockchain/v2/scheduler.go
  consensus/reactor.go
  consensus/state.go
  crypto/encoding/amino/encode_test.go
  libs/bech32/bech32.go
  libs/bytes/bytes.go
  libs/clist/clist_test.go
  libs/cmap/cmap_test.go
  libs/fail/fail.go
  libs/log/tracing_logger_test.go
  libs/pubsub/pubsub_test.go
  lite/proxy/proxy.go
  lite2/errors.go
  lite2/provider/http/http_test.go
  mempool/clist_mempool.go
  node/node.go
  p2p/conn/secret_connection_test.go
  p2p/node_info_test.go
  p2p/pex/pex_reactor.go
  p2p/upnp/upnp.go
  privval/signer_listener_endpoint_test.go
  proxy/app_conn_test.go
  rpc/client/examples_test.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/jsonrpc/server/ws_handler.go
  rpc/test/helpers.go
  scripts/wal2json/main.go
  state/state_test.go
  state/txindex/kv/kv.go
  store/store.go
  store/store_test.go
  types/events.go
  types/priv_validator.go
  types/validator_set.go
  types/validator_set_test.go
  types/vote.go
Labels: S:backport

#5969 consensus: p2p refactor
  consensus/README.md
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/invalid_test.go
  consensus/mempool_test.go
  consensus/msgs.go
  consensus/msgs_test.go
  consensus/peer_state.go
  consensus/reactor.go
  consensus/reactor_test.go
  consensus/replay_test.go
  consensus/state_test.go
  node/node.go
  p2p/p2ptest/network.go
  p2p/queue.go
  p2p/router.go
  p2p/router_test.go
  proto/tendermint/consensus/message.go
  proto/tendermint/statesync/message.go
  statesync/reactor.go
Labels: C:consensus, C:p2p

#6056 Feature Flag for Legacy P2P Support
  node/node.go
  p2p/switch.go
  test/e2e/docker/Dockerfile
  test/e2e/runner/rpc.go
Labels: C:p2p

#6121 consensus: Groom Logs (#5917)
  cmd/tendermint/commands/root.go
  config/config.go
  consensus/state.go
  test/e2e/app/main.go
  test/maverick/consensus/misbehavior.go
  test/maverick/consensus/state.go
  test/maverick/main.go
Labels: S:backport

#6124 ABCI: Fix ReCheckTx for Socket Client
  CHANGELOG_PENDING.md
  abci/client/client.go
  abci/client/socket_client.go
Labels: C:abci, S:automerge, S:backport-to-v0.34.x

#6132 tests: Fix TestByzantinePrevoteEquivocation
  consensus/byzantine_test.go
  consensus/reactor_test.go
Labels: S:automerge, T:test

#6019 rpc: standardize error codes
  CHANGELOG_PENDING.md
  light/provider/http/http.go
  light/provider/http/http_test.go
  light/rpc/client.go
  rpc/core/blocks.go
  rpc/core/env.go
  rpc/core/evidence.go
  rpc/core/net.go
  rpc/core/tx.go
  rpc/core/types/responses.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/jsonrpc/server/ws_handler.go
  rpc/jsonrpc/types/types.go
  rpc/jsonrpc/types/types_test.go
Labels: C:rpc

#6140 consensus: more log grooming
  consensus/state.go
Labels: S:automerge, S:backport-to-v0.34.x, T:code-hygiene

#6144 consensus: log private validator address and not struct
  consensus/state.go
Labels: S:automerge, T:code-hygiene

#6145 light: improve timeout functionality
  cmd/tendermint/commands/light.go
  light/provider/http/http.go
  light/rpc/client.go
  rpc/jsonrpc/client/http_json_client.go
Labels: C:light

#6151 docs: how to add tm version to RPC
  docs/tendermint-core/rpc.md
Labels: S:automerge

#6150 changelog: update with changes from 0.34.7 (and failed 0.34.5, 0.34.6)
  CHANGELOG.md
Labels: S:automerge

#6160 cmd: ignore missing wal in debug kill command
  cmd/tendermint/commands/debug/kill.go
Labels: S:automerge

#6168 rpc: change default sorting to desc for `/tx_search` results
  CHANGELOG_PENDING.md
  rpc/core/tx.go
  rpc/openapi/openapi.yaml
Labels: S:automerge

#6152 state executor: groom logs
  consensus/state.go
  state/execution.go
Labels: S:automerge, S:backport-to-v0.34.x

#6167 docs/security: add preallocated list of security vulnerability names
  docs/security/vulnerability-names.md
Labels: S:automerge

#6163 rpc/client/http: Do not drop events even if the `out` channel is full
  CHANGELOG_PENDING.md
  rpc/client/http/http.go
Labels: S:automerge

#6177 logging: print string instead of callback
  libs/service/service.go
Labels: S:automerge, S:backport-to-v0.34.x

#6176 rpc/client/http: drop endpoint arg from New and add WSOptions
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/debug/dump.go
  cmd/tendermint/commands/debug/kill.go
  cmd/tendermint/commands/light.go
  light/provider/http/http.go
  light/provider/http/http_test.go
  rpc/client/examples_test.go
  rpc/client/http/http.go
  rpc/client/http/ws.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/ws_client.go
  rpc/openapi/openapi.yaml
  statesync/stateprovider.go
  test/e2e/pkg/testnet.go
Labels: S:automerge

#6174 libs/log: [JSON format] include timestamp
  CHANGELOG_PENDING.md
  libs/cli/flags/log_level_test.go
  libs/log/filter_test.go
  libs/log/tm_json_logger.go
  libs/log/tracing_logger_test.go
Labels: S:automerge, S:backport-to-v0.34.x

#6186 docs/tutorials: fix sample code
  docs/tutorials/go-built-in.md
Labels: S:backport-to-v0.34.x
