Repository tendermint/tendermint, pull requests merged in 2022-03, with the labels that each got.

#8032 statesync: avoid compounding retry logic for fetching consensus parameters
  internal/statesync/reactor_test.go
  internal/statesync/stateprovider.go
Labels: S:automerge, S:backport-to-v0.35.x

#8035 consensus: validator set changes test cleanup
  internal/consensus/reactor_test.go
Labels: S:automerge

#8047 p2p: update shim to transfer information about peers
  internal/p2p/shim.go
  internal/p2p/shim_test.go
Labels: S:automerge

#8054 Forward-port changelog updates for v0.35.2 to master.
  CHANGELOG.md
Labels: S:automerge

#8083 Fix govet errors for %w use in test errors.
  internal/consensus/mempool_test.go
  internal/libs/queue/queue_test.go
  internal/p2p/conn/secret_connection_test.go
  internal/pubsub/query/syntax/syntax_test.go
  types/vote_set_test.go
Labels: S:automerge

#8080 evidence: manage and initialize state objects more clearly in the pool
  internal/consensus/byzantine_test.go
  internal/evidence/pool.go
  internal/evidence/pool_test.go
  internal/evidence/reactor_test.go
  internal/evidence/verify_test.go
  node/node.go
  node/node_test.go
  node/setup.go
Labels: S:automerge

#8085 statesync: avoid leaking a thread during tests
  internal/statesync/reactor_test.go
Labels: S:automerge

#8084 node: pass eventbus at construction time
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_file.go
  internal/consensus/replay_test.go
  internal/consensus/state.go
  internal/consensus/wal_generator.go
  internal/eventbus/event_bus.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/validation_test.go
  node/node.go
  node/node_test.go
  node/setup.go
Labels: S:automerge

#8092 Update changelog for #8081 backport.
  CHANGELOG_PENDING.md
Labels: S:automerge

#8082 consensus: start the timeout ticker before replay (Backport #7844)
  internal/consensus/state.go
Labels: S:automerge

#7828 p2p+flowrate: rate control refactor
  internal/blocksync/pool.go
  internal/libs/flowrate/flowrate.go
  internal/p2p/conn/connection.go
Labels: S:automerge

#8105 Fix data race.
  internal/consensus/common_test.go
Labels: S:automerge

#8112 consensus: avert a data race in round state access
  internal/consensus/common_test.go
Labels: S:automerge

#8117 readme: add vocdoni
  README.md
Labels: S:automerge

#8119 node: cleanup evidence db
  node/node.go
  node/setup.go
Labels: S:automerge

#8120 libs/log: remove Must constructor
  internal/state/execution.go
  libs/log/default.go
  test/e2e/app/app.go
  test/e2e/generator/main.go
  test/e2e/node/main.go
Labels: S:automerge

#8122 autofile: reduce minor panic and docs changes
  internal/libs/autofile/autofile.go
  internal/libs/autofile/cmd/logjack.go
  internal/libs/autofile/group.go
Labels: S:automerge

#8125 state: avoid panics for marshaling errors
  internal/rpc/core/blocks.go
  internal/rpc/core/consensus.go
  internal/state/state.go
  internal/state/state_test.go
  internal/state/store.go
Labels: S:automerge

#8134 libs/clist: remove unused surface area
  internal/libs/clist/bench_test.go
  internal/libs/clist/clist.go
  internal/libs/clist/clist_test.go
Labels: S:automerge

#8135 libs/events: remove unneccessary unsubscription code
  internal/consensus/reactor.go
  libs/events/events.go
  libs/events/events_test.go
Labels: S:automerge

#8143 mempool: test harness should expose application
  internal/mempool/mempool_bench_test.go
  internal/mempool/mempool_test.go
  internal/mempool/reactor_test.go
Labels: S:automerge

#8142 types: update synchrony params to match checked in proto
  proto/tendermint/statesync/message_test.go
  proto/tendermint/types/params.pb.go
  types/params.go
  types/params_test.go
Labels: S:automerge

#8129 docs: PBTS synchrony issues runbook
  docs/tools/debugging/proposer-based-timestamps-runbook.md
  internal/consensus/metrics.go
  internal/consensus/state.go
Labels: S:automerge

#8144 consensus: avoid extra close channel
  internal/consensus/state.go
Labels: S:automerge

#8140 blocksync: remove intermediate channel
  internal/blocksync/reactor.go
Labels: S:automerge

#8146 events: remove service aspects of event switch
  internal/consensus/state.go
  libs/events/events.go
  libs/events/events_test.go
Labels: S:automerge

#8154 types: minor cleanup of un or minimally used types
  internal/consensus/types/height_vote_set.go
  types/keys.go
  types/signable.go
  types/vote_set.go
Labels: S:automerge

#8138 consensus: change lock handling in reactor and handleMsg for RoundState (forward-port #7994 #7992)
  internal/consensus/reactor.go
  internal/consensus/state.go
Labels: S:automerge

#8145 state: panic on ResponsePrepareProposal validation error
  internal/state/execution.go
  internal/state/execution_test.go
Labels: S:automerge

#8152 mempool: reduce size of test
  internal/mempool/reactor_test.go
Labels: S:automerge

#8153 testing: logger cleanup
  internal/blocksync/pool_test.go
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/pbts_test.go
  internal/consensus/peer_state_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay_test.go
  internal/consensus/wal_generator.go
  internal/consensus/wal_test.go
  internal/eventbus/event_bus_test.go
  internal/evidence/reactor_test.go
  internal/evidence/verify_test.go
  internal/inspect/inspect_test.go
  internal/libs/autofile/group_test.go
  internal/mempool/mempool_test.go
  internal/p2p/conn/connection_test.go
  internal/p2p/p2ptest/network.go
  internal/p2p/pex/reactor_test.go
  internal/p2p/router_filter_test.go
  internal/p2p/router_test.go
  internal/p2p/transport_mconn_test.go
  internal/p2p/transport_memory_test.go
  internal/proxy/client_test.go
  internal/pubsub/example_test.go
  internal/pubsub/pubsub_test.go
  internal/state/execution_test.go
  internal/state/indexer/indexer_service_test.go
  internal/state/validation_test.go
  libs/log/testing.go
  light/client_test.go
  light/detector_test.go
  light/light_test.go
Labels: S:automerge

#8155 consensus: skip channel close during shutdown
  internal/consensus/state.go
Labels: S:automerge

#8139 consensus: change lock handling in reactor and handleMsg for RoundState (forward-port #7994 #7992)
  internal/consensus/reactor.go
  internal/consensus/state.go
Labels: S:automerge

#8172 consensus: reduce size of test fixtures and logging rate
  internal/consensus/invalid_test.go
  internal/consensus/reactor_test.go
  internal/consensus/state_test.go
Labels: S:automerge

#8158 ABCI++: Update new protos to use enum instead of bool
  abci/example/kvstore/kvstore.go
  abci/types/application.go
  abci/types/mocks/base.go
  abci/types/types.go
  abci/types/types.pb.go
  internal/consensus/mempool_test.go
  internal/consensus/state_test.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  proto/tendermint/abci/types.proto
  proto/tendermint/abci/types.proto.intermediate
  scripts/abci-gen.sh
  spec/abci++/abci++_methods_002_draft.md
  test/e2e/app/app.go
Labels: S:automerge

#8185 consensus: add leaktest check to replay tests
  internal/consensus/replay_test.go
Labels: S:automerge

#8205 migration: remove stale seen commits
  cmd/tendermint/commands/key_migrate.go
  go.mod
  scripts/scmigrate/migrate.go
  scripts/scmigrate/migrate_test.go
Labels: S:automerge, S:backport-to-v0.35.x

#8217 Document steps for updating the timeout parameters.
  UPGRADING.md
  cmd/tendermint/commands/root.go
  config/config.go
  config/toml.go
  docs/nodes/configuration.md
  proto/tendermint/types/params.proto
  spec/core/genesis.md
Labels: S:automerge

#8224 state: avoid premature genericism
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_file.go
  internal/consensus/replay_test.go
  internal/consensus/wal_generator.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/validation_test.go
  node/node.go
  node/node_test.go
Labels: S:automerge

#8228 light: remove untracked close channel
  light/rpc/client.go
Labels: S:automerge

#8229 e2e: Fix hashing for app + Fix logic of TestApp_Hash
  test/e2e/app/snapshots.go
  test/e2e/app/state.go
  test/e2e/tests/app_test.go
Labels: S:backport-to-v0.35.x
