Repository tendermint/tendermint, pull requests merged in 2022-07, with the labels that each got.

#8922 p2p: fix typo
  internal/p2p/peermanager.go
Labels: S:automerge, S:backport-to-v0.36.x

#8796 Restore `Commit` to the ABCI++ spec, and other late modifications
  UPGRADING.md
  abci/example/kvstore/kvstore.go
  abci/types/types.pb.go
  docs/rfc/rfc-013-abci++.md
  docs/tools/debugging/proposer-based-timestamps-runbook.md
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  proto/tendermint/abci/types.proto
  spec/abci++/README.md
  spec/abci++/abci++_app_requirements.md
  spec/abci++/abci++_basic_concepts.md
  spec/abci++/abci++_basic_concepts_002_draft.md
  spec/abci++/abci++_client_server.md
  spec/abci++/abci++_methods.md
  spec/abci++/abci++_tmint_expected_behavior.md
  spec/abci++/v0.md
  spec/abci++/v1.md
  spec/abci++/v2.md
  spec/abci++/v3.md
  spec/abci++/v4.md
Labels: S:backport-to-v0.36.x

#8945 Work around indexing problem for duplicate transactions (forward port: #8625)
  CHANGELOG_PENDING.md
  internal/state/indexer/indexer_service.go
  internal/state/indexer/indexer_service_test.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8942 mempool: return error when mempool is full and inbound tx is rejected
  internal/mempool/mempool.go
Labels: S:automerge, S:backport-to-v0.36.x

#8929 p2p: simpler priority queue
  internal/p2p/channel.go
  internal/p2p/pqueue.go
  internal/p2p/router.go
  internal/p2p/rqueue.go
  internal/p2p/rqueue_test.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8949 p2p: make peer gossiping coinflip safer
  internal/p2p/peermanager.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8965 Update pending changelog.
  CHANGELOG_PENDING.md
Labels: S:automerge

#8976 p2p: switch default queue implementation
  config/config.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/testnet.go
Labels: S:automerge, S:backport-to-v0.36.x

#8984 mempool: release lock during app connection flush
  internal/mempool/v1/mempool.go
Labels: S:backport-to-v0.34.x

#8987 config: remove obsolete mempool v1 warning
  config/toml.go
Labels: S:automerge

#9007 config: update config to reflect simple-priority queue
  config/config.go
  config/toml.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#9001 Typo in basic concepts section
  spec/abci++/abci++_basic_concepts.md
Labels: S:backport-to-v0.36.x

#9021 config: fix the comments on p2p.queue-type
  config/toml.go
Labels: S:automerge

#9005 migration: scope key migration to stores
  cmd/tendermint/commands/key_migrate.go
  config/db.go
  scripts/keymigrate/migrate.go
  scripts/keymigrate/migrate_test.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#9059 Forward-port changelog for v0.35.9 to master.
  CHANGELOG.md
Labels: S:automerge

#9048 Documentation: update go tutorials
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#9103 Fix unsafe-reset-all for working with default home
  cmd/tendermint/commands/reset.go
  cmd/tendermint/commands/root.go
Labels: S:backport-to-v0.34.x

#9093 abci/tests: stop abci server started in addr test
  abci/tests/client_server_test.go
Labels: S:backport-to-v0.34.x

#8786 RELEASES: add a set of pre-release steps for Tendermint versions
  RELEASES.md
Labels: S:automerge

#8898 logging: implement lazy sprinting
  abci/client/grpc_client.go
  abci/client/socket_client.go
  internal/blocksync/reactor.go
  internal/consensus/reactor.go
  internal/consensus/state.go
  internal/libs/strings/string.go
  internal/mempool/mempool.go
  internal/mempool/reactor.go
  internal/p2p/conn/connection.go
  internal/p2p/pex/reactor.go
  internal/p2p/pqueue.go
  internal/p2p/router.go
  internal/statesync/reactor.go
  internal/statesync/syncer.go
  libs/log/default.go
  light/client.go
  light/detector.go
  rpc/jsonrpc/server/http_server.go
  test/e2e/app/app.go
  test/e2e/runner/cleanup.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#9099 libs/pubsub/query: specify peg version in go.mod
  go.mod
  go.sum
  libs/pubsub/query/.gitignore
  libs/pubsub/query/Makefile
  libs/pubsub/query/peg.go
  libs/pubsub/query/query.go
  libs/pubsub/query/query.peg.go
  tools/tools.go
Labels: S:automerge

#9075 Improve handling of -short flag in tests
  cmd/tendermint/commands/rollback_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay_test.go
  internal/mempool/mempool_test.go
  internal/p2p/conn/connection_test.go
  internal/p2p/peermanager_test.go
  internal/p2p/router_test.go
  internal/p2p/transport_mconn_test.go
  internal/statesync/block_queue_test.go
  internal/statesync/reactor_test.go
  internal/statesync/syncer_test.go
  light/detector_test.go
  light/example_test.go
  light/light_test.go
  light/provider/http/http_test.go
  node/node_test.go
  rpc/client/examples_test.go
  rpc/client/helpers_test.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/ws_client_test.go
  rpc/jsonrpc/jsonrpc_test.go
  types/part_set_test.go
  types/validator_set_test.go
Labels: S:automerge, S:backport-to-v0.36.x
