Repository tendermint/tendermint, pull requests merged in 2022-09, with the labels that each got.

#9276 Update rpc client header
  CHANGELOG_PENDING.md
  consensus/replay_test.go
  light/proxy/routes.go
  light/rpc/client.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mocks/client.go
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/routes.go
  rpc/core/types/responses.go
  rpc/openapi/openapi.yaml
  state/mocks/block_store.go
  state/services.go
  store/store.go
  store/store_test.go
Labels: S:backport-to-v0.37.x

#9351 test: add the loadtime report tool
  go.mod
  go.sum
  test/loadtime/Makefile
  test/loadtime/README.md
  test/loadtime/basic.sh
  test/loadtime/cmd/load/main.go
  test/loadtime/cmd/report/main.go
  test/loadtime/payload/payload.go
  test/loadtime/payload/payload_test.go
  test/loadtime/payload/size.go
  test/loadtime/payload/size_test.go
  test/loadtime/report/report.go
  test/loadtime/report/report_test.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9366 ci: Pre-release workflows
  .github/workflows/docker.yml
  .github/workflows/pre-release.yml
  .goreleaser.yml
  RELEASES.md
Labels: S:automerge, S:backport-to-v0.37.x

#9371 ci: Remove "(WARNING: BETA SOFTWARE)" tagline from all upcoming releases
  .goreleaser.yml
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9367 add separated runs by UUID
  go.mod
  go.sum
  test/loadtime/README.md
  test/loadtime/cmd/load/main.go
  test/loadtime/cmd/report/main.go
  test/loadtime/payload/payload.pb.go
  test/loadtime/payload/payload.proto
  test/loadtime/payload/payload_test.go
  test/loadtime/report/report.go
  test/loadtime/report/report_test.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9376 Add missing changes changelog files
  CHANGELOG.md
  CHANGELOG_PENDING.md
  spec/p2p/messages/state-sync.md
  tools/tm-signer-harness/README.md
Labels: S:backport-to-v0.37.x

#9329 print all versions of tendermint and its sub protocols
  cmd/tendermint/commands/version.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9385 Add redirect link for tutorial
  docs/.vuepress/redirects
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9383 test: generate uuid on startup for load tool
  test/loadtime/cmd/load/main.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9384 Update to markdown links
  CHANGELOG.md
  DOCKER/README.md
  README.md
  RELEASES.md
  UPGRADING.md
  abci/README.md
  consensus/README.md
  docs/app-dev/abci-cli.md
  docs/app-dev/indexing-transactions.md
  docs/architecture/adr-056-light-client-amnesia-attacks.md
  docs/architecture/adr-076-combine-spec-repo.md
  docs/introduction/what-is-tendermint.md
  docs/rfc/rfc-002-ipc-ecosystem.md
  docs/rfc/rfc-003-performance-questions.md
  docs/rfc/rfc-006-event-subscription.md
  docs/rfc/rfc-012-custom-indexing.md
  docs/rfc/rfc-019-config-version.md
  docs/tendermint-core/block-structure.md
  docs/tendermint-core/how-to-read-logs.md
  docs/tendermint-core/running-in-production.md
  docs/tendermint-core/subscription.md
  docs/tendermint-core/using-tendermint.md
  docs/tendermint-core/validators.md
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
  libs/events/README.md
  proto/README.md
  spec/consensus/light-client/accountability.md
  spec/consensus/light-client/detection.md
  spec/consensus/light-client/verification.md
  spec/consensus/proposer-based-timestamp/pbts-sysmodel_001_draft.md
  spec/consensus/readme.md
  spec/core/data_structures.md
  spec/light-client/README.md
  spec/light-client/accountability/README.md
  spec/light-client/attacks/isolate-attackers_001_draft.md
  spec/light-client/attacks/isolate-attackers_002_reviewed.md
  spec/light-client/detection/README.md
  spec/light-client/detection/detection_001_reviewed.md
  spec/light-client/detection/detection_003_reviewed.md
  spec/light-client/detection/draft-functions.md
  spec/light-client/detection/req-ibc-detection.md
  spec/light-client/supervisor/supervisor_001_draft.md
  spec/light-client/verification/README.md
  spec/light-client/verification/verification_001_published.md
  spec/light-client/verification/verification_002_draft.md
  spec/p2p/messages/consensus.md
  spec/p2p/messages/pex.md
  spec/p2p/messages/state-sync.md
  tools/tm-signer-harness/README.md
Labels: S:wip

#9250 update btcec to v2 and use the latest btcutil
  CHANGELOG_PENDING.md
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_internal_test.go
  crypto/secp256k1/secp256k1_test.go
  go.mod
  go.sum
Labels: S:wip

#9299 test/fuzz: bring changes from v0.34.x into main
  test/fuzz/Makefile
  test/fuzz/README.md
  test/fuzz/oss-fuzz-build.sh
  test/fuzz/p2p/addrbook/fuzz.go
  test/fuzz/p2p/addrbook/init-corpus/main.go
  test/fuzz/p2p/pex/init-corpus/main.go
  test/fuzz/p2p/pex/reactor_receive.go
  test/fuzz/p2p/pex/testdata/addrbook1
  test/fuzz/p2p/secret_connection/init-corpus/main.go
  test/fuzz/rpc/jsonrpc/server/handler.go
  test/fuzz/tests/mempool_test.go
  test/fuzz/tests/p2p_secretconnection_test.go
  test/fuzz/tests/rpc_jsonrpc_server_test.go
  test/fuzz/tests/testdata/fuzz/FuzzMempool/1daffc1033a0bfc7f0c2bccb7440674e67a9e2cc0a4531863076254ada059863
  test/fuzz/tests/testdata/fuzz/FuzzMempool/582528ddfad69eb57775199a43e0f9fd5c94bba343ce7bb6724d4ebafe311ed4
  test/fuzz/tests/testdata/fuzz/FuzzMempool/d40a98862ed393eb712e47a91bcef18e6f24cf368bb4bd248c7a7101ef8e178d
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/0f1a3d10e4d642e42a3ccd9bad652d355431f5824327271aca6f648e8cd4e786
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/172c521d1c5e7a5cce55e39b235928fc1c8c4adbb4635913c204c4724cf47d20
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/a9481542b8154bfe8fe868c8907cb66557347cb9b45709b17da861997d7cabea
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/ba3758980fe724f83bdf1cb97caa73657b4a78d48e5fd6fc3b1590d24799e803
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/c22ff3cdf5145a03ecc6a2c18a7ec4eb3c9e1384af92cfa14cf50951535b6c85
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/d40a98862ed393eb712e47a91bcef18e6f24cf368bb4bd248c7a7101ef8e178d
  test/fuzz/tests/testdata/fuzz/FuzzP2PSecretConnection/dc7304b2cddeadd08647d30b1d027f749960376c338e14a81e0396ffc6e6d6bd
  test/fuzz/tests/testdata/fuzz/FuzzRPCJSONRPCServer/058ae08103537df220789dea46edb8b7cf7368e90da0cb35888a1452f4d114a2
  test/fuzz/tests/testdata/fuzz/FuzzRPCJSONRPCServer/2ab633cb322fca9e76fc965b430076844ebd0b3c4f30f5263b94a3d50f00bce6
  test/fuzz/tests/testdata/fuzz/FuzzRPCJSONRPCServer/aadb440fa55da05c1185e3e64b33c804d994cce06781e8c39481411793a8a73f
  test/fuzz/tests/testdata/fuzz/FuzzRPCJSONRPCServer/d40a98862ed393eb712e47a91bcef18e6f24cf368bb4bd248c7a7101ef8e178d
Labels: stale

#9399 docs: Update ADRs for v0.37
  docs/architecture/README.md
  docs/architecture/adr-060-go-api-stability.md
  docs/architecture/adr-061-p2p-refactor-scope.md
  docs/architecture/adr-062-p2p-architecture.md
  docs/architecture/adr-063-privval-grpc.md
  docs/architecture/adr-065-custom-event-indexing.md
  docs/architecture/adr-068-reverse-sync.md
  docs/architecture/adr-076-combine-spec-repo.md
  docs/architecture/adr-077-block-retention.md
  docs/architecture/adr-078-nonzero-genesis.md
  docs/architecture/adr-079-ed25519-verification.md
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9416 feat: support HTTPS inside websocket
  rpc/jsonrpc/client/ws_client.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9435 state: restore previous error message
  state/store.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9294 rfc: simplify mempool to support more broad tendermint uses
  docs/rfc/README.md
  docs/rfc/rfc-025-support-app-side-mempool.md
Labels: S:automerge

#9255 crypto: Upstream v0.35.x improvements
  CHANGELOG_PENDING.md
  crypto/batch/batch.go
  crypto/crypto.go
  crypto/ed25519/bench_test.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/ed25519_test.go
  crypto/sr25519/batch.go
  crypto/sr25519/bench_test.go
  crypto/sr25519/encoding.go
  crypto/sr25519/privkey.go
  crypto/sr25519/pubkey.go
  crypto/sr25519/sr25519_test.go
  go.mod
  go.sum
  p2p/conn/evil_secret_connection_test.go
  p2p/conn/secret_connection.go
  types/validation.go
  types/validation_test.go
  types/validator_set.go
  types/validator_set_test.go
Labels: S:wip

#9261 cli: add --hard flag to rollback command to remove block as well
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/rollback.go
  consensus/replay_test.go
  rpc/client/mocks/client.go
  state/mocks/block_store.go
  state/rollback.go
  state/rollback_test.go
  state/services.go
  store/store.go
  store/store_test.go
Labels: S:backport-to-v0.37.x

#9447 crypto/merkle: pre-allocate data slice in innherHash (#6443)
  CHANGELOG_PENDING.md
  crypto/merkle/hash.go
Labels: S:automerge

#9445 p2p/pex: reuse hash.Hasher per addrbook for speed (#6509)
  CHANGELOG_PENDING.md
  p2p/pex/addrbook.go
  p2p/pex/bench_test.go
Labels: S:automerge

#9467 Fix ABCI specification (TXs added in `PrepareProposal` are not added to the mempool)
  spec/abci/abci++_methods.md
Labels: S:backport-to-v0.37.x

#9462 Ensure Dockerfile stages use consistent Go version
  CHANGELOG_PENDING.md
  DOCKER/Dockerfile
Labels: S:automerge, S:backport-to-v0.37.x

#9455 metrics: fix panic because of absent prometheus label
  consensus/metrics.gen.go
  consensus/metrics.go
  p2p/metrics.gen.go
  p2p/metrics.go
Labels: S:automerge, S:backport-to-v0.37.x

#9475 docs: Use release badge in README instead of latest tag
  README.md
Labels: S:automerge

#9483 config: Add missing storage section when generating config
  config/toml.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9444 tools: use os home dir to instead of the hardcoded PATH
  CHANGELOG_PENDING.md
  tools/tm-signer-harness/Makefile
  tools/tm-signer-harness/main.go
Labels: S:automerge

#9464 .github/workflows: add cosmos/gosec vulnerability scanner for each Push/PR
  .github/workflows/gosec.yml
Labels: S:automerge

#9461 small typo fix: "later" to "latter"
  spec/abci/apps.md
Labels: S:automerge
