Repository tendermint/tendermint, pull requests merged in 2022-01, with the labels that each got.

#7514 e2e: use more simple strings for generated transactions (#7513)
  libs/rand/random.go
  test/e2e/generator/generate.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/load.go
Labels: S:automerge

#7516 e2e: constrain test parallelism and reporting
  test/e2e/runner/test.go
  test/e2e/tests/app_test.go
  test/e2e/tests/e2e_test.go
Labels: S:backport-to-v0.35.x

#7523 e2e: make tx test more stable
  test/e2e/tests/app_test.go
Labels: S:backport-to-v0.35.x

#7568 rpc: remove cache control settings from the HTTP server
  internal/inspect/rpc/rpc.go
  internal/rpc/core/routes.go
  light/proxy/routes.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_json_handler_test.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/parse_test.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/jsonrpc/test/main.go
  test/fuzz/rpc/jsonrpc/server/handler.go
Labels: S:automerge

#7571 rpc: fix mock test cases
  rpc/client/mock/abci_test.go
Labels: S:automerge

#7595 rpc: update fuzz criteria to match the implementation
  test/fuzz/rpc/jsonrpc/server/handler.go
Labels: S:automerge

#7598 Add changelog entries from release v0.34.15.
  CHANGELOG.md
Labels: S:automerge

#7524 RFC-009: Consensus Parameter Upgrades
  docs/rfc/rfc-009-consensus-parameter-upgrades.md
Labels: S:automerge

#7503 ADR-74: Migrate Timeout Parameters to Consensus Parameters
  docs/architecture/README.md
  docs/architecture/adr-074-timeout-params.md
Labels: S:automerge

#7606 protoio: fix incorrect test assertion
  internal/libs/protoio/io_test.go
Labels: S:automerge

#7551 consensus: calculate prevote message delay metric
  internal/consensus/metrics.go
  internal/consensus/state.go
  types/vote_set.go
Labels: S:automerge

#7625 consensus: check proposal non-nil in prevote message delay metric
  internal/consensus/state.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7608 build: Make sure to test packages with external tests
  Makefile
  internal/p2p/pex/reactor_test.go
Labels: S:backport-to-v0.35.x

#7621 privval: do not use old proposal timestamp
  privval/file.go
  privval/file_test.go
Labels: S:automerge

#7648 consensus: fix height advances in test state
  internal/consensus/common_test.go
  internal/consensus/state_test.go
Labels: S:automerge

#7683 rpc: check error code for broadcast_tx_commit
  internal/rpc/core/mempool.go
Labels: S:backport-to-v0.35.x

#7605 Proposer-Based Timestamps Merge
  CHANGELOG_PENDING.md
  config/toml.go
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/invalid_test.go
  internal/consensus/mempool_test.go
  internal/consensus/pbts_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/consensus/replay_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
  internal/consensus/types/height_vote_set_test.go
  internal/consensus/types/round_state.go
  internal/eventbus/event_bus.go
  internal/eventbus/event_bus_test.go
  internal/evidence/pool_test.go
  internal/evidence/verify_test.go
  internal/state/helpers_test.go
  internal/state/rollback_test.go
  internal/state/state.go
  internal/state/store_test.go
  internal/state/validation.go
  internal/state/validation_test.go
  internal/statesync/block_queue_test.go
  internal/statesync/reactor_test.go
  internal/test/factory/block.go
  internal/test/factory/genesis.go
  internal/test/factory/validator.go
  libs/time/mocks/source.go
  libs/time/time.go
  light/client_test.go
  light/store/db/db_test.go
  node/node_test.go
  proto/tendermint/statesync/message_test.go
  proto/tendermint/types/params.pb.go
  test/e2e/runner/evidence.go
  third_party/proto/gogoproto/gogo.proto
  types/block.go
  types/canonical.go
  types/events.go
  types/genesis_test.go
  types/params.go
  types/params_test.go
  types/proposal.go
  types/proposal_test.go
  types/vote.go
  types/vote_set_test.go
Labels: S:automerge

#7668 consensus: use buffered channel in TestStateFullRound1
  internal/consensus/common_test.go
  internal/consensus/state_test.go
Labels: S:automerge

#7704 params: increase default synchrony params
  types/params.go
Labels: S:automerge

#7705 Forward-port v0.35.1 changelogs.
  CHANGELOG.md
Labels: S:automerge

#7709 metrics: add metric for proposal timestamp difference
  internal/consensus/metrics.go
  internal/consensus/state.go
Labels: S:automerge

#7711 Use proposer timestamp instead of genesis time for height 1 block time
  CHANGELOG_PENDING.md
  internal/consensus/pbts_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
  internal/state/state.go
  internal/state/validation.go
  rpc/client/evidence_test.go
  rpc/client/rpc_test.go
  types/proposal.go
  types/proposal_test.go
Labels: S:automerge

#7639 light: Fix absence proof verification by light client
  CHANGELOG_PENDING.md
  light/rpc/client.go
Labels: S:backport-to-v0.35.x

#7714 mempool: return duplicate tx errors more consistently
  internal/mempool/mempool.go
Labels: S:backport-to-v0.35.x

#7726 docs: fix some typos in ADR 075.
  docs/architecture/adr-075-rpc-subscription.md
Labels: S:automerge

#7733 conensus: put timeouts on reactor tests
  internal/consensus/reactor_test.go
Labels: S:automerge

#7734 consensus: remove unused closer construct
  internal/consensus/peer_state.go
  internal/consensus/reactor.go
Labels: S:automerge

#7744 rpc: fix layout of endpoint list (#7742)
  rpc/jsonrpc/server/http_json_handler.go
Labels: S:automerge
