Repository tendermint/tendermint, pull requests merged in 2022-06, with the labels that each got.

#8652 consensus: gossip catchup sleeping protocol
  internal/consensus/reactor.go
Labels: S:automerge

#8614 migrate: provide function for database production
  cmd/tendermint/commands/key_migrate.go
Labels: S:automerge, S:backport-to-v0.35.x

#8564 cmd: add tool for compaction of goleveldb
  cmd/tendermint/commands/compact.go
  cmd/tendermint/main.go
  go.mod
  go.sum
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#8678 p2p: shed peers from store from other networks
  internal/p2p/router.go
Labels: S:backport-to-v0.35.x

#8673 Remove the abci responses type - prune legacy responses
  abci/cmd/abci-cli/abci-cli.go
  cmd/tendermint/commands/reindex_event.go
  cmd/tendermint/commands/reindex_event_test.go
  internal/consensus/replay.go
  internal/consensus/replay_stubs.go
  internal/consensus/state_test.go
  internal/evidence/pool.go
  internal/inspect/inspect_test.go
  internal/rpc/core/blocks.go
  internal/rpc/core/blocks_test.go
  internal/state/errors.go
  internal/state/execution.go
  internal/state/helpers_test.go
  internal/state/mocks/store.go
  internal/state/state_test.go
  internal/state/store.go
  internal/state/store_test.go
  internal/store/store.go
  light/store/db/db.go
  proto/tendermint/state/types.pb.go
  proto/tendermint/state/types.proto
Labels: S:automerge

#8684 p2p: pass maxConns for MaxPeers during node setup
  node/setup.go
Labels: S:backport-to-v0.35.x

#8694 consensus: switch timeout message to be debug and clarify meaning
  internal/consensus/ticker.go
Labels: S:backport-to-v0.35.x

#8706 Fix a "broken" markdown link.
  docs/roadmap/roadmap.md
Labels: S:automerge

#8727 Update config migration test data for v0.36.x
  scripts/confix/testdata/diff-35-36.txt
  scripts/confix/testdata/v36-config.toml
Labels: S:automerge, S:backport-to-v0.36.x

#8730 e2e/generator: add additional testnets (0.35)
  test/e2e/generator/generate.go
Labels: S:automerge

#8753 p2p: self-add node should not error
  internal/p2p/peermanager.go
  internal/p2p/peermanager_test.go
  node/node.go
  node/seed.go
  node/setup.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8757 Revert "p2p: self-add node should not error (tendermint#8753)"
  internal/p2p/peermanager.go
  internal/p2p/peermanager_test.go
  node/node.go
  node/seed.go
  node/setup.go
Labels: S:automerge, S:backport-to-v0.36.x

#8759 p2p: accept should not abort on first error
  internal/p2p/router.go
  internal/p2p/router_test.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8762 p2p: fix mconn transport accept test
  internal/p2p/router_test.go
Labels: S:automerge, S:backport-to-v0.36.x

#8745 refactor: improve string representation for a vote against the proposal
  types/vote.go
  types/vote_set.go
  types/vote_test.go
Labels: S:backport-to-v0.36.x

#8635 e2e: reactivate network test
  test/e2e/runner/test.go
  test/e2e/tests/net_test.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8780 Fix typo in Using Tendermint section
  docs/tendermint-core/using-tendermint.md
Labels: S:automerge

#8737 p2p: peer store and dialing changes
  CHANGELOG_PENDING.md
  config/config.go
  config/toml.go
  internal/p2p/metrics.gen.go
  internal/p2p/metrics.go
  internal/p2p/p2ptest/network.go
  internal/p2p/peermanager.go
  internal/p2p/peermanager_scoring_test.go
  internal/p2p/peermanager_test.go
  internal/p2p/router.go
  node/node.go
  node/seed.go
  node/setup.go
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/p2p/types.proto
Labels: S:backport-to-v0.36.x

#8787 p2p: track peers stored on startup
  internal/p2p/peermanager.go
Labels: S:automerge, S:backport-to-v0.36.x

#8577 abci+test/e2e/app: add mutex for new methods
  test/e2e/app/app.go
Labels: S:automerge, S:backport-to-v0.36.x

#8790 p2p: peer score should not wrap around
  internal/p2p/peermanager.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8793 p2p: fix typo
  internal/p2p/router.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8803 p2p: wake dialing thread after sleep
  internal/p2p/peermanager.go
  internal/p2p/router.go
Labels: S:automerge, S:backport-to-v0.36.x

#8740 p2p: peer store and dialing changes (0.35.x backport)
  config/config.go
  config/toml.go
  internal/p2p/metrics.go
  internal/p2p/p2ptest/network.go
  internal/p2p/peermanager.go
  internal/p2p/peermanager_scoring_test.go
  internal/p2p/peermanager_test.go
  internal/p2p/router.go
  internal/p2p/switch.go
  node/node.go
  node/setup.go
  proto/tendermint/p2p/types.pb.go
  proto/tendermint/p2p/types.proto
Labels: S:automerge

#8819 p2p: add eviction metrics and cleanup dialing error handling
  internal/p2p/metrics.gen.go
  internal/p2p/metrics.go
  internal/p2p/peermanager.go
  internal/p2p/peermanager_test.go
  internal/p2p/router.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8824 p2p: revert wake-more change
  internal/p2p/router.go
Labels: S:automerge

#8827 p2p: more dial routines
  internal/p2p/router.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8843 e2e: report peer heights in error message
  test/e2e/runner/rpc.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8841 p2p: track peers by address
  internal/p2p/peermanager.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8849 e2e: add tolerance to peer discovery test
  test/e2e/tests/net_test.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8871 light: fix light client select statement
  light/client.go
Labels: S:backport-to-v0.36.x

#8862 e2e: disable another network test
  test/e2e/tests/net_test.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8839 p2p: remove dial sleep and provide disconnect cooldown
  internal/p2p/p2ptest/network.go
  internal/p2p/peermanager.go
  internal/p2p/router.go
  internal/p2p/router_test.go
  node/setup.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8890 libs/strings: move to internal
  internal/inspect/inspect.go
  internal/libs/strings/string.go
  internal/libs/strings/string_test.go
  internal/rpc/core/env.go
  node/setup.go
  types/node_info.go
  types/params.go
Labels: S:automerge, S:backport-to-v0.36.x

#8895 log: do not pre-process log results
  libs/log/default.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8869 p2p: set empty timeouts to configed values. (manual backport of #8847)
  abci/client/mocks/client.go
  internal/consensus/mocks/cons_sync_reactor.go
  internal/evidence/mocks/block_store.go
  internal/p2p/mocks/connection.go
  internal/p2p/mocks/peer.go
  internal/p2p/mocks/transport.go
  internal/p2p/peer_test.go
  internal/p2p/router.go
  internal/p2p/router_test.go
  internal/p2p/switch.go
  internal/p2p/switch_test.go
  internal/p2p/test_util.go
  internal/p2p/transport.go
  internal/p2p/transport_mconn.go
  internal/p2p/transport_memory.go
  internal/p2p/transport_test.go
  internal/proxy/mocks/app_conn_consensus.go
  internal/proxy/mocks/app_conn_mempool.go
  internal/proxy/mocks/app_conn_query.go
  internal/proxy/mocks/app_conn_snapshot.go
  internal/state/indexer/mocks/event_sink.go
  internal/state/mocks/block_store.go
  internal/state/mocks/evidence_pool.go
  internal/state/mocks/store.go
  internal/statesync/mocks/state_provider.go
  light/client.go
  light/provider/mocks/provider.go
  light/rpc/mocks/light_client.go
  node/node.go
  rpc/client/mocks/client.go
  scripts/mockery_generate.sh
Labels: S:automerge

#8902 node: always start blocksync and avoid misconfiguration
  node/node.go
  node/setup.go
Labels: S:automerge

#8906 p2p: stop mconn channel sends without timeout
  internal/p2p/conn/connection.go
Labels: S:backport-to-v0.36.x

#8913 p2p: set default outgoing connections to about 20% of total connections
  config/config.go
Labels: S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8917 p2p: fix flakey test due to disconnect cooldown
  internal/p2p/p2ptest/network.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x

#8916 p2p: use correct context error
  internal/p2p/transport_mconn.go
Labels: S:automerge, S:backport-to-v0.35.x, S:backport-to-v0.36.x
