Repository tendermint/tendermint, pull requests merged in 2022-11, with the labels that each got.

#9656 spec/abci: Removed reference to Finalize block
  spec/abci/abci++_methods.md
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9348 Documentation of p2p layer in Tendermint v0.34
  spec/p2p/readme.md
  spec/p2p/v0.34/README.md
  spec/p2p/v0.34/addressbook.md
  spec/p2p/v0.34/configuration.md
  spec/p2p/v0.34/img/p2p_state.png
  spec/p2p/v0.34/peer_manager.md
  spec/p2p/v0.34/pex-protocol.md
  spec/p2p/v0.34/pex.md
  spec/p2p/v0.34/switch.md
  spec/p2p/v0.34/transport.md
  spec/p2p/v0.34/types.md
Labels: S:wip

#9653 Removes space in hyperlink
  STYLE_GUIDE.md
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9654 Moves the PBTS ADR to Accepted list
  docs/architecture/README.md
Labels: S:automerge

#9650 rpc: Add caching support
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/debug/util.go
  light/proxy/routes.go
  rpc/core/routes.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_json_handler_test.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/openapi/openapi.yaml
  test/fuzz/tests/rpc_jsonrpc_server_test.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9660 abci: Add unsynchronized local client
  abci/client/local_client.go
  abci/client/unsync_local_client.go
  proxy/client.go
  test/e2e/app/app.go
  test/e2e/app/sync_app.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/node/config.go
  test/e2e/node/main.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: C:abci

#9676 docs: Add new per-message type P2P metrics
  docs/tendermint-core/metrics.md
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9690 rpc: fix check_tx cache problem
  rpc/core/routes.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9685 Forward-port v0.34.23 changelog entry
  CHANGELOG.md
Labels: S:automerge

#9682 metrics: add separate statesync and blocksync metrics
  CHANGELOG_PENDING.md
  blocksync/metrics.gen.go
  blocksync/metrics.go
  blocksync/reactor.go
  blocksync/reactor_test.go
  consensus/metrics.gen.go
  consensus/metrics.go
  consensus/reactor.go
  node/node.go
  node/setup.go
  statesync/metrics.gen.go
  statesync/metrics.go
  statesync/reactor.go
  statesync/reactor_test.go
Labels: C:metrics

#9698 Disambiguates wording in EndBlock
  spec/abci/abci++_basic_concepts.md
Labels: S:backport-to-v0.37.x

#9720 Remove useless whitespace in Websocket output
  CHANGELOG_PENDING.md
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  rpc/jsonrpc/server/ws_handler.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9375 Fix Examples for Proposer Selection Specs
  spec/consensus/proposer-selection.md
Labels: S:wip

#9716 Fix spec in `ProcessProposal` to align with implementation
  spec/abci/abci++_methods.md
Labels: S:backport-to-v0.37.x

#9591 statesync: convert apphash to hex string in log
  consensus/replay.go
  statesync/syncer.go
Labels: S:automerge

#9744 make format
  abci/types/messages.go
  consensus/msgs.go
  evidence/reactor.go
  libs/pubsub/query/query_test.go
  p2p/switch.go
  p2p/transport.go
  p2p/types.go
  proto/tendermint/blocksync/message.go
  proto/tendermint/consensus/message.go
  proto/tendermint/mempool/message.go
  proto/tendermint/statesync/message.go
  state/execution_test.go
  state/indexer/block/kv/util.go
  state/validation_test.go
  test/loadtime/cmd/load/main.go
  test/loadtime/cmd/report/main.go
  test/loadtime/payload/payload_test.go
  test/loadtime/report/report.go
  test/loadtime/report/report_test.go
Labels: S:automerge

#9745 Update oss-fuzz-build.sh
  test/fuzz/oss-fuzz-build.sh
Labels: S:automerge

#9760 consensus: correctly save reference to previous height precommits
  CHANGELOG_PENDING.md
  consensus/reactor.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9777 docs: Fix search configuration
  docs/.vuepress/config.js
Labels: C:docs, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9746 Add v0.34.24 changelog entry and upgrading guidelines
  CHANGELOG.md
  UPGRADING.md
Labels: S:automerge

#9771 patch: error message in light client
  light/rpc/client.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9787 [Backport to v0.34.x] update btcec to v2 and use the latest btcutil (#9250)
  CHANGELOG_PENDING.md
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_internal_test.go
  crypto/secp256k1/secp256k1_test.go
  go.mod
  go.sum
Labels: S:automerge

#9782 ci: Configure docs build workflow to use legacy OpenSSL provider
  .github/workflows/docs-deployment.yml
Labels: C:docs, S:automerge, S:backport-to-v0.37.x

#9674 rpc: update docs
  docs/pre.sh
  rpc/openapi/openapi.yaml
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9793 docs: Expand on genesis_chunked description
  rpc/openapi/openapi.yaml
Labels: C:docs

#9794 docs: Fix pre-build script
  docs/pre.sh
Labels: C:docs, S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9764 p2p: fix logspam (backport #9756)
  p2p/switch.go
Labels: S:automerge

#9779 e2e: test runner generates loadtime formatted transactions.
  test/e2e/networks/simple.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/load.go
  test/e2e/runner/main.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x
