Repository tendermint/tendermint, pull requests merged in 2022-02, with the labels that each got.

#7739 types: make timely predicate adaptive after 10 rounds
  internal/consensus/state.go
  types/proposal.go
  types/proposal_test.go
Labels: S:automerge

#7749 rpc: remove the placeholder RunState type.
  light/rpc/client.go
  rpc/client/helpers.go
  rpc/client/http/ws.go
  rpc/client/interface.go
  rpc/client/mocks/client.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/integration_test.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/client/ws_client_test.go
  rpc/jsonrpc/server/ws_handler.go
Labels: C:rpc

#7764 ADR: synchronize PBTS ADR with spec
  docs/architecture/adr-071-proposer-based-timestamps.md
Labels: S:automerge

#7787 types: add string format to 64-bit integer JSON fields
  rpc/coretypes/responses.go
  types/block_meta.go
  types/events.go
Labels: S:automerge

#7791 consensus: refactor operations in consensus queryMaj23Routine
  internal/consensus/reactor.go
Labels: S:backport-to-v0.35.x

#7777 RFC: add delete gas rfc
  docs/rfc/README.md
  docs/rfc/rfc-011-delete-gas.md
Labels: S:automerge

#7811 Silence a staticcheck warning.
  crypto/secp256k1/secp256k1.go
Labels: S:automerge

#7813 docs: fix ToC file extension for RFC 004.
  docs/rfc/README.md
Labels: S:automerge

#7834 Fix broken links in ADR 071.
  docs/architecture/adr-071-proposer-based-timestamps.md
Labels: S:automerge

#7841 docs: rename RFC 008
  docs/rfc/README.md
  docs/rfc/rfc-008-do-not-panic.md
Labels: S:automerge

#7842 abci/client: remove waitgroup for requests
  abci/client/client.go
  abci/client/grpc_client.go
  abci/client/socket_client.go
Labels: S:automerge

#7840 blocksync: shutdown cleanup
  internal/blocksync/reactor.go
  internal/blocksync/reactor_test.go
Labels: S:automerge

#7838 p2p: pass start time to flowrate and cleanup constructors
  internal/blocksync/pool.go
  internal/libs/flowrate/flowrate.go
  internal/libs/flowrate/util.go
  internal/p2p/conn/connection.go
  internal/p2p/conn/connection_test.go
  internal/p2p/transport_mconn.go
Labels: S:automerge

#7843 clist: remove unused waitgroup from clist implementation
  internal/libs/clist/clist.go
Labels: S:automerge

#7845 abci/client: remove client-level callback
  abci/client/client.go
  abci/client/creators.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/mocks/client.go
  abci/client/socket_client.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/mocks/cons_sync_reactor.go
  internal/consensus/reactor_test.go
  internal/evidence/mocks/block_store.go
  internal/mempool/mempool.go
  internal/proxy/app_conn.go
  internal/proxy/mocks/app_conn_consensus.go
  internal/proxy/mocks/app_conn_mempool.go
  internal/proxy/multi_app_conn.go
  internal/proxy/multi_app_conn_test.go
  internal/state/indexer/mocks/event_sink.go
  internal/state/mocks/evidence_pool.go
  internal/state/mocks/store.go
  internal/statesync/mocks/state_provider.go
Labels: S:automerge

#7863 docs: fix misspelled file name
  docs/architecture/adr-069-flexible-node-inititalization.md
Labels: S:automerge

#7869 Update unsafe-reset-all command to match release v35
  docs/app-dev/getting-started.md
Labels: S:backport-to-v0.35.x

#7857 abci/client: make flush operation sync
  abci/client/client.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/mocks/client.go
  abci/client/socket_client.go
  internal/mempool/mempool.go
  internal/proxy/app_conn.go
  internal/proxy/mocks/app_conn_mempool.go
Labels: S:automerge

#7849 consensus: additional timing metrics
  internal/consensus/metrics.go
  internal/consensus/state.go
Labels: S:automerge, S:backport-to-v0.35.x

#7877 abci: undo socket buffer limit
  abci/client/socket_client.go
Labels: S:automerge

#7837 fix app hash in state rollback
  CHANGELOG_PENDING.md
  internal/state/rollback.go
  internal/state/rollback_test.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7856 statesync: assert app version matches
  internal/statesync/syncer.go
  internal/statesync/syncer_test.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7788 types: add default values for the synchrony parameters
  types/genesis.go
  types/params.go
Labels: S:automerge

#7873 logging: allow logging level override
  cmd/tendermint/commands/root.go
  libs/log/default.go
  libs/log/nop.go
Labels: S:automerge

#7899 docs: remove spec section from v0.35 docs
  docs/post.sh
  docs/pre.sh
Labels: S:backport-to-v0.34.x

#7720 consensus: HasVoteMessage index boundary check
  internal/consensus/peer_state.go
  internal/consensus/peer_state_test.go
  internal/consensus/reactor.go
  libs/bits/bit_array.go
  libs/bits/bit_array_test.go
Labels: S:automerge

#7802 types/events+evidence: emit events + metrics on evidence validation
  CHANGELOG_PENDING.md
  docs/nodes/metrics.md
  internal/consensus/byzantine_test.go
  internal/consensus/reactor_test.go
  internal/consensus/state.go
  internal/eventbus/event_bus.go
  internal/eventbus/event_bus_test.go
  internal/evidence/metrics.go
  internal/evidence/pool.go
  internal/evidence/pool_test.go
  internal/evidence/reactor.go
  internal/evidence/reactor_test.go
  internal/evidence/verify.go
  internal/evidence/verify_test.go
  internal/rpc/core/evidence.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  internal/state/mocks/evidence_pool.go
  internal/state/services.go
  internal/state/validation_test.go
  node/node.go
  node/node_test.go
  node/setup.go
  types/events.go
Labels: C:evidence, C:events

#7874 Remove master from the docs site version config.
  docs/.vuepress/config.js
  docs/versions
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7909 docs: Pin the RPC docs to v0.35 instead of master
  docs/.vuepress/config.js
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7936 docs: redirect master links to the latest release version
  docs/.vuepress/config.js
  docs/.vuepress/redirects
  docs/package-lock.json
  docs/package.json
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7966 docs: fix cosmos theme version.
  docs/package-lock.json
  docs/package.json
Labels: S:automerge

#7969 Restore building docs for master on docs.tendermint.com.
  docs/versions
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.35.x

#7962 math: remove panics in safe math ops
  internal/consensus/state.go
  internal/consensus/types/height_vote_set.go
  internal/state/store.go
  libs/math/safemath.go
Labels: S:automerge

#7963 context: cleaning up context dead ends
  cmd/tendermint/commands/light.go
  internal/rpc/core/events.go
  rpc/client/event_test.go
  rpc/client/helpers.go
  rpc/client/http/ws.go
  rpc/client/main_test.go
  rpc/client/rpc_test.go
  test/e2e/node/main.go
  test/e2e/runner/benchmark.go
Labels: S:automerge

#7958 e2e(harness): plumb logging instance
  test/e2e/runner/benchmark.go
  test/e2e/runner/cleanup.go
  test/e2e/runner/evidence.go
  test/e2e/runner/load.go
  test/e2e/runner/main.go
  test/e2e/runner/perturb.go
  test/e2e/runner/rpc.go
  test/e2e/runner/setup.go
  test/e2e/runner/start.go
  test/e2e/runner/test.go
  test/e2e/runner/wait.go
Labels: S:automerge

#7973 p2p: make mconn transport test less flaky
  internal/p2p/transport_memory.go
  internal/p2p/transport_test.go
Labels: S:automerge

#7978 abci: make tendermint example+test clients manage a mutex
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/kvstore_test.go
  abci/example/kvstore/persistent_kvstore.go
  abci/types/application.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/invalid_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay_test.go
  rpc/client/main_test.go
  test/e2e/app/app.go
Labels: S:automerge

#7960 testing: reduce usage of the MustDefaultLogger constructor
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/test/main.go
  rpc/test/helpers.go
  test/fuzz/rpc/jsonrpc/server/handler.go
Labels: S:automerge

#7984 abci: remove lock protecting calls to the application interface
  CHANGELOG_PENDING.md
  UPGRADING.md
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/server/grpc_server.go
  abci/server/socket_server.go
Labels: S:automerge

#7991 abci/kvstore: test cleanup improvements
  abci/example/kvstore/kvstore_test.go
Labels: S:automerge

#7996 abci: use no-op loggers in the examples
  abci/example/example_test.go
Labels: S:automerge

#7995 p2p: mconn track last message for pongs
  internal/p2p/conn/connection.go
  internal/p2p/conn/connection_test.go
Labels: S:automerge

#8001 statesync: fix SyncAny test
  internal/statesync/syncer_test.go
Labels: S:automerge

#8005 Add manual e2e workflow to v0.34.x.
  .github/workflows/e2e-manual.yml
Labels: S:automerge

#8007 p2p: relax pong timeout
  internal/p2p/conn/connection.go
Labels: S:automerge

#8006 Add manual e2e workflow to v0.35.x.
  .github/workflows/e2e-manual.yml
Labels: S:automerge

#8008 Forward port v0.34.16 changelog to master.
  CHANGELOG.md
Labels: S:automerge

#7961 state: synchronize the ProcessProposal implementation with the latest version of the spec
  abci/client/socket_client.go
  abci/example/kvstore/kvstore.go
  abci/types/application.go
  abci/types/mocks/application.go
  abci/types/mocks/base.go
  abci/types/result.go
  abci/types/types.pb.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  test/e2e/app/app.go
  types/evidence.go
Labels: S:automerge

#8011 p2p: ignore transport close error during cleanup
  internal/p2p/transport_mconn_test.go
Labels: S:automerge

#7990 abci: revert buffer limit change
  abci/client/socket_client.go
Labels: S:automerge

#7989 proxy: fix endblock metric
  internal/proxy/app_conn.go
Labels: S:automerge

#8013 consensus: make orchestration more reliable for invalid precommit test
  internal/consensus/invalid_test.go
Labels: S:automerge

#8021 docs: fix some broken markdown links
  docs/architecture/adr-044-lite-client-with-weak-subjectivity.md
  docs/architecture/adr-045-abci-evidence.md
  docs/roadmap/roadmap.md
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: S:automerge

#8030 p2p: plumb rudamentary service discovery to rectors and update statesync
  internal/p2p/p2ptest/network.go
  internal/p2p/p2ptest/require.go
  internal/p2p/peermanager.go
  internal/p2p/peermanager_test.go
  internal/p2p/router.go
  internal/statesync/reactor.go
  internal/statesync/reactor_test.go
Labels: S:automerge
