Repository tendermint/tendermint, pull requests merged in 2022-04, with the labels that each got.

#8241 stop using %w in testing errors
  crypto/xchacha20poly1305/xchachapoly_test.go
Labels: S:automerge

#8238 node: remove channel and peer update initialization from construction
  internal/blocksync/reactor.go
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/invalid_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/evidence/reactor.go
  internal/evidence/reactor_test.go
  internal/mempool/reactor.go
  internal/mempool/reactor_test.go
  internal/p2p/p2ptest/network.go
  internal/p2p/peermanager.go
  internal/p2p/pex/reactor.go
  internal/p2p/pex/reactor_test.go
  internal/p2p/router.go
  internal/p2p/router_init_test.go
  internal/p2p/router_test.go
  internal/statesync/reactor.go
  internal/statesync/reactor_test.go
  internal/statesync/syncer.go
  node/node.go
  node/node_test.go
  node/public.go
  node/seed.go
  node/setup.go
Labels: S:automerge

#8267 statesync: tweak test performance
  internal/statesync/reactor_test.go
Labels: S:automerge

#8268 Fix broken links in the changelog.
  CHANGELOG.md
Labels: S:automerge

#8269 Fix broken links in the changelog.
  CHANGELOG.md
Labels: S:automerge

#8266 consensus: avoid panics during handshake
  internal/consensus/replay.go
  internal/consensus/replay_test.go
Labels: S:automerge

#8276 scmigrate: ensure target key is correctly renamed
  CHANGELOG_PENDING.md
  go.mod
  go.sum
  scripts/keymigrate/migrate.go
  scripts/keymigrate/migrate_test.go
  scripts/scmigrate/migrate.go
  scripts/scmigrate/migrate_test.go
Labels: S:backport-to-v0.35.x

#8279 Forward-port changelog for v0.34.19 to master.
  CHANGELOG.md
Labels: S:automerge

#8291 Forward-port v0.35.3 changelog to master.
  CHANGELOG.md
Labels: S:automerge

#8293 Fix release notes to match the prevailing style.
  .github/workflows/release.yml
Labels: S:automerge

#8294 keymigrate: fix decoding of block-hash row keys
  CHANGELOG_PENDING.md
  scripts/keymigrate/migrate.go
  scripts/keymigrate/migrate_test.go
Labels: S:backport-to-v0.35.x

#8216 abci++: only include meaningful header fields in data passed-through to application
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/kvstore_test.go
  abci/types/types.pb.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  internal/state/validation_test.go
  proto/tendermint/abci/types.proto
  proto/tendermint/abci/types.proto.intermediate
  proto/tendermint/privval/service.proto
  spec/abci++/abci++_methods_002_draft.md
  test/e2e/app/app.go
  types/evidence.go
Labels: S:automerge

#8315 state: remove unused weighted time
  internal/state/time.go
  internal/state/time_test.go
Labels: S:automerge

#8324 Revert CI cache override.
  .github/workflows/lint.yml
Labels: S:automerge

#8325 Remove resolved TODO comments.
  scripts/confix/confix.go
Labels: S:automerge

#8328 rpc: avoid leaking threads during checktx
  internal/rpc/core/mempool.go
Labels: S:backport-to-v0.35.x

#8316 pubsub: [minor] remove unused stub method
  internal/pubsub/pubsub.go
Labels: S:automerge

#8338 Update RFC ToC for RFC-015.
  docs/rfc/README.md
Labels: S:automerge

#8342 confix: convert tx-index.indexer from string to array
  scripts/confix/confix.go
  scripts/confix/plan.go
Labels: S:backport-to-v0.35.x

#8352 keymigrate: fix conversion of transaction hash keys
  scripts/keymigrate/migrate.go
  scripts/keymigrate/migrate_test.go
Labels: S:backport-to-v0.35.x

#8354 Update pending changelog for #8352.
  CHANGELOG_PENDING.md
Labels: S:automerge

#8364 Forward port changelog from v0.35.4 to master.
  CHANGELOG.md
Labels: S:automerge

#8363 build: clean up an unnecessary dependency
  Makefile
Labels: S:automerge

#8370 p2p: fix setting in conn-tracker
  internal/p2p/conn_tracker.go
  internal/p2p/conn_tracker_test.go
Labels: S:backport-to-v0.35.x

#8368 cleanup: pin get-diff-action uses to major version only, not minor/patch
  .github/workflows/build.yml
  .github/workflows/docs-toc.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/markdown-links.yml
  .github/workflows/tests.yml
Labels: S:automerge

#8378 node: cleanup setup for indexer and evidence components
  node/node.go
  node/node_test.go
  node/setup.go
Labels: S:automerge

#8377 rpc: reformat method signatures and use a context
  rpc/client/eventstream/eventstream.go
  rpc/client/http/http.go
  rpc/client/http/ws.go
  rpc/client/local/local.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/ws_handler.go
Labels: S:automerge

#8380 Add confix testdata for Tendermint v0.30.
  scripts/confix/confix_test.go
  scripts/confix/testdata/diff-30-31.txt
  scripts/confix/testdata/v30-config.toml
Labels: S:automerge, S:backport-to-v0.35.x

#8382 abci: avoid having untracked requests in the channel
  abci/client/grpc_client.go
  abci/client/socket_client.go
Labels: S:automerge

#8384 Add config testdata samples from TM v26, v27, v28, v29.
  scripts/confix/testdata/README.md
  scripts/confix/testdata/baseline.txt
  scripts/confix/testdata/diff-26-27.txt
  scripts/confix/testdata/diff-27-28.txt
  scripts/confix/testdata/diff-28-29.txt
  scripts/confix/testdata/diff-29-30.txt
  scripts/confix/testdata/v26-config.toml
  scripts/confix/testdata/v27-config.toml
  scripts/confix/testdata/v28-config.toml
  scripts/confix/testdata/v29-config.toml
Labels: S:automerge, S:backport-to-v0.35.x

#8383 abci: streamline grpc application construction
  abci/example/example_test.go
  abci/example/kvstore/kvstore_test.go
  abci/server/grpc_server.go
  abci/server/server.go
  abci/types/application.go
Labels: S:automerge

#8404 abci: interface should take pointers to arguments
  abci/client/grpc_client.go
  abci/client/mocks/client.go
  abci/client/socket_client.go
  abci/cmd/abci-cli/abci-cli.go
  abci/example/example_test.go
  abci/example/kvstore/helpers.go
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/kvstore_test.go
  abci/example/kvstore/persistent_kvstore.go
  abci/server/grpc_server.go
  abci/server/socket_server.go
  abci/tests/server/client.go
  abci/types/application.go
  abci/types/messages.go
  abci/types/mocks/application.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_stubs.go
  internal/consensus/replay_test.go
  internal/consensus/state_test.go
  internal/mempool/mempool.go
  internal/mempool/mempool_test.go
  internal/proxy/client.go
  internal/proxy/client_test.go
  internal/rpc/core/abci.go
  internal/rpc/core/mempool.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  internal/statesync/reactor.go
  internal/statesync/reactor_test.go
  internal/statesync/syncer.go
  internal/statesync/syncer_test.go
  node/node.go
  rpc/client/mock/abci.go
  test/e2e/app/app.go
Labels: S:automerge

#8410 p2p: add libp2p feature flag
  config/config.go
  internal/p2p/router.go
  internal/p2p/router_test.go
  node/node.go
Labels: B:libp2p

#8427 p2p: use nodeinfo less often
  internal/p2p/p2ptest/network.go
  internal/p2p/router.go
  internal/p2p/router_test.go
Labels: S:automerge

#8432 p2p: move transport options into struct
  internal/p2p/p2ptest/network.go
  internal/p2p/router.go
  internal/p2p/router_init_test.go
  internal/p2p/router_test.go
  node/setup.go
Labels: B:libp2p

#8446 p2p: make p2p.Channel an interface
  internal/blocksync/reactor.go
  internal/blocksync/reactor_test.go
  internal/consensus/invalid_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/evidence/reactor.go
  internal/evidence/reactor_test.go
  internal/mempool/reactor.go
  internal/mempool/reactor_test.go
  internal/p2p/channel.go
  internal/p2p/channel_test.go
  internal/p2p/p2ptest/network.go
  internal/p2p/p2ptest/require.go
  internal/p2p/pex/reactor.go
  internal/p2p/pex/reactor_test.go
  internal/p2p/router.go
  internal/p2p/router_test.go
  internal/statesync/dispatcher.go
  internal/statesync/dispatcher_test.go
  internal/statesync/reactor.go
  internal/statesync/reactor_test.go
  internal/statesync/stateprovider.go
  internal/statesync/syncer.go
Labels: B:libp2p
