Repository tendermint/tendermint, pull requests merged in 2022-10, with the labels that each got.

#9505 Use evidence period when pruning
  CHANGELOG_PENDING.md
  consensus/replay_test.go
  evidence/verify.go
  go.sum
  state/execution.go
  state/mocks/block_store.go
  state/mocks/store.go
  state/services.go
  state/store.go
  state/store_test.go
  store/store.go
  store/store_test.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9509 Extend the load report tool to include transactions' hashes
  test/loadtime/cmd/report/main.go
  test/loadtime/report/report.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9500 security/p2p: prevent peers who errored being added to the peer_set
  p2p/errors.go
  p2p/mock/peer.go
  p2p/mocks/peer.go
  p2p/peer.go
  p2p/peer_set.go
  p2p/peer_set_test.go
  p2p/switch.go
  p2p/switch_test.go
Labels: C:p2p, T:security, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9473 indexer: move deduplication functionality purely to the kvindexer
  node/node.go
  state/indexer/sink/psql/psql_test.go
  state/txindex/indexer_service.go
  state/txindex/indexer_service_test.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9518 blocksync: retry requests after timeout
  blocksync/pool.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9540 Fix TX payload for DO testnets
  test/loadtime/payload/payload.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9551 ci: Update Slack nightly failure messages
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-main.yml
Labels: S:automerge

#9499 QA Process report for v0.37.x (and baseline for v0.34.x)
  .gitignore
  docs/qa/README.md
  docs/qa/method.md
  docs/qa/v034/README.md
  docs/qa/v034/img/v034_200node_latencies.png
  docs/qa/v034/img/v034_200node_latencies_zoomed.png
  docs/qa/v034/img/v034_latency_throughput.png
  docs/qa/v034/img/v034_r200c2_heights.png
  docs/qa/v034/img/v034_r200c2_load-runner.png
  docs/qa/v034/img/v034_r200c2_load1.png
  docs/qa/v034/img/v034_r200c2_mempool_size.png
  docs/qa/v034/img/v034_r200c2_mempool_size_avg.png
  docs/qa/v034/img/v034_r200c2_peers.png
  docs/qa/v034/img/v034_r200c2_rounds.png
  docs/qa/v034/img/v034_r200c2_rss.png
  docs/qa/v034/img/v034_r200c2_rss_avg.png
  docs/qa/v034/img/v034_r200c2_total-txs.png
  docs/qa/v034/img/v034_report_tabbed.txt
  docs/qa/v034/img/v034_rotating_heights.png
  docs/qa/v034/img/v034_rotating_heights_ephe.png
  docs/qa/v034/img/v034_rotating_latencies.png
  docs/qa/v034/img/v034_rotating_latencies_uniq.png
  docs/qa/v034/img/v034_rotating_load1.png
  docs/qa/v034/img/v034_rotating_peers.png
  docs/qa/v034/img/v034_rotating_rss_avg.png
  docs/qa/v034/img/v034_rotating_total-txs.png
  docs/qa/v037/README.md
  docs/qa/v037/img/v037_200node_latencies.png
  docs/qa/v037/img/v037_latency_throughput.png
  docs/qa/v037/img/v037_r200c2_heights.png
  docs/qa/v037/img/v037_r200c2_load1.png
  docs/qa/v037/img/v037_r200c2_mempool_size.png
  docs/qa/v037/img/v037_r200c2_mempool_size_avg.png
  docs/qa/v037/img/v037_r200c2_peers.png
  docs/qa/v037/img/v037_r200c2_rounds.png
  docs/qa/v037/img/v037_r200c2_rss.png
  docs/qa/v037/img/v037_r200c2_rss_avg.png
  docs/qa/v037/img/v037_r200c2_total-txs.png
  docs/qa/v037/img/v037_report_tabbed.txt
  docs/qa/v037/img/v037_rotating_heights.png
  docs/qa/v037/img/v037_rotating_heights_ephe.png
  docs/qa/v037/img/v037_rotating_latencies.png
  docs/qa/v037/img/v037_rotating_load1.png
  docs/qa/v037/img/v037_rotating_peers.png
  docs/qa/v037/img/v037_rotating_rss_avg.png
  docs/qa/v037/img/v037_rotating_total-txs.png
  scripts/qa/reporting/README.md
  scripts/qa/reporting/latency_throughput.py
  scripts/qa/reporting/requirements.txt
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9582 Fix problems in QA report
  docs/qa/v037/README.md
Labels: S:backport-to-v0.37.x

#9583 Release v0.34.22
  CHANGELOG.md
  CHANGELOG_PENDING.md
  version/version.go
Labels: R:patch

#9579 Fix some broken links in docs
  docs/DOCS_README.md
  docs/architecture/adr-071-proposer-based-timestamps.md
Labels: S:automerge

#9588 Update changelog with v0.34.22 entry
  CHANGELOG.md
Labels: S:automerge

#9597 docs: remove outdated comment
  config/config.go
Labels: S:automerge

#9629 github: remove forked version of gosec
  .github/workflows/gosec.yml
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9600 ci: Only allow automated security-related dependency updates on release branches
  .github/dependabot.yml
Labels: S:automerge

#9596 ci: Add Slack notifications when releases and pre-releases are cut
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: S:automerge

#9622 p2p: add a per-message type send and receive metric
  .github/workflows/lint.yml
  blocksync/msgs.go
  blocksync/reactor.go
  cmd/tendermint/commands/debug/util.go
  cmd/tendermint/commands/rollback.go
  consensus/byzantine_test.go
  consensus/invalid_test.go
  consensus/msgs.go
  consensus/msgs_test.go
  consensus/reactor.go
  consensus/reactor_test.go
  evidence/reactor.go
  evidence/reactor_test.go
  go.mod
  go.sum
  libs/rand/random.go
  mempool/v0/reactor.go
  mempool/v0/reactor_test.go
  mempool/v1/reactor.go
  p2p/base_reactor.go
  p2p/conn/connection.go
  p2p/metrics.gen.go
  p2p/metrics.go
  p2p/mock/peer.go
  p2p/mock/reactor.go
  p2p/mocks/peer.go
  p2p/peer.go
  p2p/peer_set_test.go
  p2p/peer_test.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
  p2p/switch.go
  p2p/switch_test.go
  p2p/test_util.go
  p2p/transport.go
  p2p/types.go
  proto/tendermint/blocksync/message.go
  proto/tendermint/consensus/message.go
  proto/tendermint/mempool/message.go
  proto/tendermint/p2p/pex.go
  proto/tendermint/statesync/message.go
  statesync/messages.go
  statesync/messages_test.go
  statesync/reactor.go
  statesync/reactor_test.go
  statesync/syncer.go
  statesync/syncer_test.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9624 e2e: configurable IP addresses for e2e testnet generator (backport #9592)
  Makefile
  test/e2e/node/config.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/infra/provider.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/main.go
  test/e2e/runner/setup.go
  test/e2e/tests/e2e_test.go
Labels: S:automerge
