Repository tendermint/tendermint, pull requests merged in 2022-12, with the labels that each got.

#9695 docs: Fix metrics name rendering
  docs/tendermint-core/metrics.md
Labels: C:docs, S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9808 Fixes reference from recalled 0.36.x to 0.37.x
  spec/abci/abci++_app_requirements.md
Labels: S:backport-to-v0.37.x

#9806 Fix typo in new option in e2e manifest node
  test/e2e/pkg/manifest.go
  test/e2e/runner/main.go
Labels: S:automerge, S:backport-to-v0.37.x

#9809 Mention tx_max_bytes in the tutorials
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: S:automerge, S:backport-to-v0.37.x

#9814 e2e: create client when sending transaction
  test/e2e/runner/load.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9812 ci: Better Slack failures
  .github/workflows/docker.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-main.yml
  .github/workflows/fuzz-nightly.yml
Labels: S:automerge

#9822 e2e: add defer to ensure waitgroup is finished.
  test/e2e/runner/load.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9819 e2e: setup testing for multi-version
  .github/workflows/tendermint-docker.yml
  .github/workflows/testapp-docker.yml
  test/e2e/Makefile
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9821 fixes abci-cli console help
  abci/cmd/abci-cli/abci-cli.go
  state/execution.go
Labels: S:backport-to-v0.37.x

#9829 e2e: add multiversion flag to generator
  test/e2e/generator/generate.go
  test/e2e/generator/main.go
  test/e2e/generator/random.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9848 abci++: Vote extension cleanup
  consensus/common_test.go
  consensus/msgs.go
  consensus/reactor.go
  privval/file.go
  types/block.go
  types/evidence.go
  types/priv_validator.go
  types/vote.go
  types/vote_set.go
  types/vote_test.go
Labels: S:automerge

#9768 backport: set a minimum long-polling interval for Events in rpc (#8050)
  docs/architecture/adr-075-rpc-subscription.md
  rpc/client/eventstream/eventstream_test.go
  rpc/core/events.go
Labels: S:wip

#9850 workflow: correct the name for the e2e app in the workflow
  .github/workflows/testapp-docker.yml
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9706 rfc 27: report on bandwidth usage within Tendermint
  docs/rfc/README.md
  docs/rfc/images/receive-rate-all.png
  docs/rfc/images/send-rate-all.png
  docs/rfc/images/top-3-percent-receive.png
  docs/rfc/images/top-3-percent-send.png
  docs/rfc/rfc-027-p2p-message-bandwidth-report.md
Labels: S:automerge, S:wip

#9854 ci: Remove automatic dependabot updates for npm packages
  .github/dependabot.yml
Labels: C:docs, S:automerge

#9759 state/kvindexer: associate event attributes with events
  CHANGELOG_PENDING.md
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/persistent_kvstore.go
  docs/app-dev/indexing-transactions.md
  light/proxy/routes.go
  rpc/client/main_test.go
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/routes.go
  rpc/core/tx.go
  rpc/openapi/openapi.yaml
  spec/abci/abci.md
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
  state/txindex/kv/utils.go
  types/events.go
Labels: C:indexer

#9877 kvindexer: Fixing order or keywords in light client rpc
  light/proxy/routes.go
Labels: C:indexer

#9885 node: wire up logger to mempool reactor
  node/setup.go
Labels: S:automerge, S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9830 abci: Adapt unsynchronized local client to replicate remote client concurrency
  CHANGELOG_PENDING.md
  abci/client/unsync_local_client.go
  proxy/client.go
  test/e2e/app/app.go
  test/e2e/app/sync_app.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/node/config.go
  test/e2e/node/main.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: C:abci

#9896 e2e: Remove extraneous abci_protocol params in CI test
  test/e2e/networks/ci.toml
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x

#9903 ci: Add govulncheck workflow
  .github/workflows/govulncheck.yml
  Makefile
Labels: S:backport-to-v0.34.x, S:backport-to-v0.37.x, qa

#9820 docs: Update upgrading guidelines for v0.37.0
  UPGRADING.md
Labels: C:docs
