Repository tendermint/tendermint, pull requests merged in 2022-08, with the labels that each got.

#9107 cli: set node p2p external address with cmd flag
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/run_node.go
Labels: S:automerge

#9090 Optimize ABCI Response Information and flag to save ABCI results #8028 #8946
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/reindex_event.go
  config/config.go
  internal/blocksync/v0/reactor_test.go
  internal/blocksync/v2/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_file.go
  internal/consensus/replay_test.go
  internal/consensus/wal_generator.go
  internal/evidence/pool_test.go
  internal/inspect/inspect.go
  internal/rpc/core/blocks_test.go
  internal/state/errors.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  internal/state/mocks/store.go
  internal/state/rollback_test.go
  internal/state/state_test.go
  internal/state/store.go
  internal/state/store_test.go
  internal/state/validation_test.go
  node/node.go
  node/node_test.go
  node/setup.go
  proto/tendermint/state/types.pb.go
  proto/tendermint/state/types.proto
  test/e2e/generator/generate.go
Labels: S:backport-to-v0.34.x

#9153 config: p2p.external-address (backport #9107)
  CHANGELOG_PENDING.md
  cmd/tendermint/commands/run_node.go
Labels: S:automerge

#9156 metricsgen: port metrics code generation tool
  scripts/metricsgen/metricsdiff/metricsdiff.go
  scripts/metricsgen/metricsdiff/metricsdiff_test.go
  scripts/metricsgen/metricsgen.go
  scripts/metricsgen/metricsgen_test.go
  scripts/metricsgen/testdata/basic/metrics.gen.go
  scripts/metricsgen/testdata/basic/metrics.go
  scripts/metricsgen/testdata/commented/metrics.gen.go
  scripts/metricsgen/testdata/commented/metrics.go
  scripts/metricsgen/testdata/tags/metrics.gen.go
  scripts/metricsgen/testdata/tags/metrics.go
Labels: S:automerge

#9168 consensus: additional timing metrics (port of #7849)
  consensus/metrics.go
  consensus/state.go
  docs/tendermint-core/metrics.md
Labels: S:automerge

#9178 metrics: transition all metrics to using metricsgen generated constructors. (port of #8488)
  consensus/metrics.gen.go
  consensus/metrics.go
  consensus/state.go
  mempool/metrics.gen.go
  mempool/metrics.go
  p2p/metrics.gen.go
  p2p/metrics.go
  proxy/metrics.gen.go
  proxy/metrics.go
  state/metrics.gen.go
  state/metrics.go
Labels: S:automerge

#9175 remove lastresulthash from merklization in lastresult hash
  CHANGELOG_PENDING.md
  UPGRADING.md
  spec/core/data_structures.md
  types/results.go
Labels: S:automerge

#9199 e2e: fix out of sync configuration
  .github/workflows/e2e-nightly-34x.yml
Labels: S:automerge

#9196 tools: remove mockery from tools.go
  .github/workflows/check-generated.yml
  evidence/mocks/block_store.go
  go.mod
  go.sum
  light/rpc/mocks/light_client.go
  p2p/mocks/peer.go
  proxy/mocks/app_conn_consensus.go
  proxy/mocks/app_conn_mempool.go
  proxy/mocks/app_conn_query.go
  proxy/mocks/app_conn_snapshot.go
  proxy/mocks/client_creator.go
  scripts/mockery_generate.sh
  state/indexer/mocks/block_indexer.go
  state/mocks/block_store.go
  state/mocks/evidence_pool.go
  state/mocks/store.go
  state/txindex/mocks/tx_indexer.go
  statesync/mocks/state_provider.go
Labels: S:automerge

#9172 metrics: add metricsgen makefile target
  Makefile
Labels: S:automerge

#8457 RFC-024: block structure consolidation
  docs/rfc/README.md
  docs/rfc/rfc-024-block-structure-consolidation.md
Labels: S:automerge, stale

#9266 abci: Remove SetOption #5447 #9091
  CHANGELOG_PENDING.md
  abci/client/client.go
  abci/client/grpc_client.go
  abci/client/local_client.go
  abci/client/mocks/client.go
  abci/client/socket_client.go
  abci/cmd/abci-cli/abci-cli.go
  abci/example/kvstore/persistent_kvstore.go
  abci/server/socket_server.go
  abci/tests/server/client.go
  abci/tests/test_cli/ex2.abci.out
  abci/types/application.go
  abci/types/messages.go
  abci/types/mocks/application.go
  abci/types/types.go
  abci/types/types.pb.go
  docs/app-dev/abci-cli.md
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
  proto/tendermint/abci/types.proto
  proxy/app_conn.go
Labels: backlog-priority

#9259 config: backport the rename of fastsync to blocksync
  CHANGELOG_PENDING.md
  blocksync/msgs.go
  blocksync/msgs_test.go
  blocksync/pool.go
  blocksync/pool_test.go
  blocksync/reactor.go
  blocksync/reactor_test.go
  cmd/tendermint/commands/root.go
  cmd/tendermint/commands/run_node.go
  config/config.go
  config/config_test.go
  config/toml.go
  consensus/metrics.gen.go
  consensus/metrics.go
  consensus/reactor.go
  docs/tendermint-core/README.md
  docs/tendermint-core/block-sync.md
  docs/tendermint-core/configuration.md
  docs/tendermint-core/metrics.md
  docs/tendermint-core/state-sync.md
  node/node.go
  proto/tendermint/blocksync/types.pb.go
  proto/tendermint/blocksync/types.proto
  spec/abci/abci.md
  spec/p2p/messages/block-sync.md
  test/e2e/README.md
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: S:automerge, C:config

#9283 abci++: update PrepareProposal API to accept just a list of bytes
  abci/cmd/abci-cli/abci-cli.go
  abci/example/code/code.go
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/persistent_kvstore.go
  abci/tests/server/client.go
  abci/tests/test_cli/ex1.abci
  abci/tests/test_cli/ex1.abci.out
  abci/types/application.go
  abci/types/types.pb.go
  consensus/mempool_test.go
  proto/tendermint/abci/types.proto
  state/execution.go
  state/execution_test.go
  test/e2e/app/app.go
  types/tx.go
  types/tx_test.go
Labels: S:automerge
