Repository tendermint/tendermint, pull requests merged in 2022-05, with the labels that each got.

#8096 PBTS: system model made more precise
  spec/consensus/proposer-based-timestamp/pbts-sysmodel_002_draft.md
Labels: stale

#8454 docs: minor fixups to pbts overview
  docs/tendermint-core/consensus/proposer-based-timestamps.md
Labels: S:automerge

#8466 keymigrate: improve filtering for legacy transaction hashes
  UPGRADING.md
  scripts/keymigrate/migrate.go
  scripts/keymigrate/migrate_test.go
Labels: S:backport-to-v0.35.x

#8475 Convert explicit zero comparison to a method.
  light/verifier.go
Labels: S:automerge

#8468 Reintegrate docs deployment into the main TM repo
  .github/workflows/docs-deployment.yml
  Makefile
  docs/package.json
Labels: C:docs

#8476 p2p: base implementation of libp2p channel
  internal/p2p/channel.go
  internal/p2p/router.go
Labels: B:libp2p

#8479 scripts/metricsgen: add the initial version of metricsgen
  Makefile
  internal/state/indexer/metrics.gen.go
  internal/state/indexer/metrics.go
  scripts/metricsgen/metricsgen.go
  scripts/metricsgen/metricsgen_test.go
  scripts/metricsgen/testdata/basic/metrics.gen.go
  scripts/metricsgen/testdata/basic/metrics.go
  scripts/metricsgen/testdata/commented/metrics.gen.go
  scripts/metricsgen/testdata/commented/metrics.go
  scripts/metricsgen/testdata/tags/metrics.gen.go
  scripts/metricsgen/testdata/tags/metrics.go
Labels: S:automerge

#8493 blocksync: validate block before persisting it
  internal/blocksync/reactor.go
Labels: S:backport-to-v0.34.x, S:backport-to-v0.35.x

#8480 consensus: add additional metrics for abci++ data
  docs/nodes/metrics.md
  internal/consensus/metrics.go
  internal/consensus/state.go
  internal/state/execution.go
  internal/state/metrics.go
Labels: S:automerge

#8500 p2p: simple request and response framework
  internal/p2p/channel.go
Labels: B:libp2p

#8494 statesync: avoid potential race
  internal/statesync/stateprovider.go
Labels: S:automerge

#8501 scripts/metricsgen: add metricsdiff tool
  scripts/metricsgen/metricsdiff/metricsdiff.go
  scripts/metricsgen/metricsdiff/metricsdiff_test.go
Labels: S:automerge

#8548 p2p: avoid sending errors after context is canceled
  internal/mempool/reactor.go
  internal/p2p/channel.go
Labels: B:libp2p

#8544 p2p: collect errors from channel
  go.mod
  go.sum
  internal/p2p/channel.go
  internal/p2p/router.go
Labels: B:libp2p

#8562 p2p: cache libp2p streams
  internal/p2p/channel.go
Labels: B:libp2p

#8563 p2p: use more appropriate context
  internal/p2p/channel.go
  internal/p2p/router.go
Labels: B:libp2p

#8576 consensus: update state from store before use in reactor
  internal/consensus/reactor.go
  internal/consensus/state.go
Labels: S:automerge

#8592 p2p: libp2p constructor scafolding
  internal/p2p/host.go
  node/node.go
  node/node_test.go
  node/public.go
  node/seed.go
  node/setup.go
Labels: B:libp2p

#8609 makefile: update buf commands to use tools.go
  Makefile
  go.mod
  go.sum
  tools/tools.go
Labels: S:automerge

#8612 Update generated mocks after #8607.
  abci/client/mocks/client.go
  abci/types/mocks/application.go
  internal/consensus/mocks/cons_sync_reactor.go
  internal/evidence/mocks/block_store.go
  internal/mempool/mocks/mempool.go
  internal/p2p/mocks/connection.go
  internal/p2p/mocks/transport.go
  internal/state/indexer/mocks/event_sink.go
  internal/state/mocks/block_store.go
  internal/state/mocks/evidence_pool.go
  internal/state/mocks/store.go
  internal/statesync/mocks/state_provider.go
  libs/time/mocks/source.go
  light/provider/mocks/provider.go
  light/rpc/mocks/light_client.go
  rpc/client/mocks/client.go
Labels: S:automerge

#8613 migrate: reorder collection ordering
  cmd/tendermint/commands/key_migrate.go
Labels: S:automerge, S:backport-to-v0.35.x

#8627 Forward-port changelogs from v0.35.5 to master
  CHANGELOG.md
Labels: S:automerge

#8640 docs: add documentation for undocumented p2p metrics
  docs/nodes/metrics.md
Labels: S:automerge, S:backport-to-v0.35.x

#8651 consensus: restructure peer catchup sleep
  internal/consensus/reactor.go
Labels: S:automerge

#8657 pex: align max address thresholds
  internal/p2p/pex/params.go
  internal/p2p/pex/pex_reactor.go
  internal/p2p/pex/reactor.go
Labels: S:automerge
